// 이중 사전 (INFRA-004): 화면 라벨은 하드코딩하지 않고 이 사전을 거친다.
// fantasy 용어는 SHARED_GLOSSARY 의 게임↔업무 대조표를 따른다.
export const LEXICON = {
  business: {
    app_title: "개발팀 운영 콕핏",
    app_version_label: "UI",
    browser_version_label: "브라우저",
    nav_home: "프로젝트 홈",
    nav_items: "할 일",
    nav_mail: "메일 이력",
    nav_artifacts: "산출물",
    nav_search: "현장 검색",
    nav_projects: "프로젝트 관리",
    proj_year_label: "과제시작년도",
    proj_year_suffix: "년 시작",
    proj_year_none: "시작년도 미지정",
    proj_tree_loading: "불러오는 중…",
    proj_tree_empty: "해당 없음",
    proj_path_hint: "과제 클릭 → facet 열림",
    proj_path_cap: "과제 > facet",
    proj_start: "시작",
    proj_stage: "현재",
    proj_wl_overdue: "연체",
    proj_wl_today: "오늘",
    proj_wl_open: "열림",
    proj_wl_none: "열린 일 없음",
    nav_soon: "준비 중",
    soon_ai: "AI 제안→사람 승인 단일 표면. ai_proposal 착지면 owner 결정 후 활성됩니다.",
    soon_perm: "RBAC 권한·게이트모드(hard/soft) 설정 표면. 후속 슬라이스에서 활성됩니다.",
    project: "프로젝트",
    stage: "단계",
    item: "할 일",
    boss: "단계 종료(게이트)",
    open: "미완료",
    blocked: "차단",
    due_soon: "마감 임박",
    status_open: "대기",
    status_doing: "진행 중",
    status_waiting: "대기(외부)",
    status_blocked: "차단",
    status_done: "완료",
    status_unclassified: "분류 필요",
    mine_only: "내 일만",
    mine_all: "전체 보기",
    kpi_mail: "메일",
    mine_hint: "내 계정(로그인명 또는 내 이름)이 담당인 할 일만",
    triage_note: "메일/요청에서 자동 추출됐지만 과제·단계·산출물 연결이 없는 임시 할 일입니다. 분류해야 정식 실행 목록에 들어갑니다.",
    backlog_meter: "미처리 업무",
    freshness: "데이터 수집 시각",
    empty_items: "표시할 할 일이 없습니다",
    empty_mail: "메일 이력이 없습니다",
    mail_claim_drop: "메일을 여기로 끌어다 놓으면 내 할 일이 됩니다",
    mail_claim_drop_multi: "할 일·메일을 담당자에게 끌어다 놓으면 그 사람 할 일이 됩니다",
    mail_collect: "메일 수집",
    mail_collect_running: "메일 수집 중…",
    mail_collect_done: "메일 수집 완료",
    mail_collect_new: "신규",
    mail_collect_busy: "이미 수집 중입니다",
    mail_collect_admin: "관리자만 메일을 수집할 수 있습니다",
    mail_collect_fail: "메일 수집 실패",
    mailbox_owner: "메일함 주인",
    mailbox_shared: "공용함",
    mail_unassign: "분류 취소",
    mail_unassign_hint: "받은함으로 되돌리기",
    mail_unassigned: "분류를 취소했습니다(받은함)",
    mail_unassign_fail: "분류 취소 실패",
    mail_delete: "메일 삭제",
    mail_delete_hint: "이 메일을 목록에서 삭제(재수집돼도 다시 안 보임)",
    mail_delete_confirm: "이 메일을 삭제할까요? 목록에서 사라집니다(재수집돼도 다시 안 보임).",
    mail_deleted: "메일을 삭제했습니다",
    mail_delete_fail: "메일 삭제 실패",
    mail_edit: "메일 수정",
    mail_edit_save: "저장",
    mail_edit_cancel: "취소",
    mail_edit_need_subject: "제목을 입력하세요",
    mail_edited: "메일을 수정했습니다",
    mail_edit_fail: "메일 수정 실패",
    mailbox_disconnect: "해제",
    mailbox_disconnect_hint: "연결 해제 + 비번 파일 삭제(메일·할일 보존)",
    mailbox_disconnect_confirm: "메일함 연결을 해제할까요? 저장된 비밀번호 파일이 삭제됩니다. (메일·할일은 보존)",
    mailbox_disconnected: "메일함 해제됨",
    mailbox_disconnect_fail: "메일함 해제 실패",
    claim_assigned_suffix: " 님에게 배정했습니다",
    claim_me: "나",
    empty_artifacts: "산출물 포인터가 없습니다",
    deliv_section: "산출물 레지스터",
    deliv_empty: "ingest된 산출물이 없습니다 (tools/scan_se_foldertree.mjs --apply)",
    deliv_add: "산출물 추가",
    deliv_stage: "게이트",
    deliv_no: "번호",
    deliv_criteria: "완료기준",
    deliv_add_done: "추가됨",
    deliv_exists: "같은 게이트·번호 산출물이 이미 있습니다",
    di_open: "입력",
    di_hint: "산출물 입력파일(In 폴더) 관리",
    di_section: "입력파일",
    di_type: "종류",
    di_subfolder: "하위폴더",
    di_file: "파일명",
    di_pointer: "상대 포인터",
    di_source: "출처",
    di_status: "상태",
    di_register: "등록",
    di_none: "등록된 입력파일 없음",
    di_need: "파일명 또는 포인터 필요",
    di_added: "등록됨",
    di_abs: "상대경로만 가능",
    di_st_needed: "필요",
    di_st_received: "수집됨",
    di_st_used: "반영됨",
    di_upload: "파일 업로드",
    di_upload_hint: "선택한 하위폴더의 02_Input 에 올립니다",
    di_pick: "파일을 선택하세요",
    di_uploading: "업로드 중…",
    di_fileio_off: "파일 IO 비활성(DEV_ERP_FILEIO)",
    di_no_folder: "산출물 폴더 경로 미설정",
    di_too_large: "용량 초과",
    di_download: "다운로드",
    deliv_name: "산출물",
    deliv_submit: "제출유형",
    deliv_submit_draft: "초안",
    deliv_submit_final: "최종",
    deliv_state: "상태",
    deliv_state_todo: "미착수",
    deliv_state_produced: "작성됨",
    deliv_state_review: "검토중",
    deliv_state_done: "완료",
    deliv_due: "마감",
    deliv_pointer: "03_Out 포인터",
    deliv_due_save: "저장",
    deliv_due_owner: "수동",
    deliv_due_auto: "자동",
    deliv_due_ingest: "미정",
    deliv_due_saved: "저장됨",
    deliv_due_note: "일정(언제)은 자동으로 못 정해 비어 옵니다 — 직접 입력해 바꾸세요. 사람이 정한 일정은 재-스캔이 덮지 않습니다. 나중에 Codex가 분석해 채울 예정입니다.",
    deliv_rv_self: "본인검토",
    deliv_rv_team: "팀검토",
    deliv_rv_to_self: "본인검토 완료",
    deliv_rv_to_team: "팀검토 완료",
    deliv_rv_to_lead: "리드 승인(완료)",
    deliv_rv_back: "되돌리기",
    deliv_rv_need_file: "03_Out 파일(작성됨) 후 검토 진행",
    deliv_spawn_task: "할 일로",
    deliv_spawn_hint: "이 산출물을 '작성'하는 할 일 생성(단계·연결·마감 상속)",
    deliv_already_task: "이미 할일 있음",
    search_hint: "프로젝트명·업체명·제목으로 검색",
    th_status: "상태",
    th_due: "마감",
    th_assignee: "담당",
    th_automation: "자동화",
    th_time: "시각",
    th_direction: "방향",
    th_subject: "제목",
    th_counterpart: "상대",
    th_kind: "종류",
    th_updated: "갱신",
    th_pointer: "위치(포인터)",
    all_label: "전체",
    mail_in: "수신",
    mail_out: "발신",
    copy: "복사",
    mode_label: "표시 모드",
    search_placeholder: "검색",
    group_pinned: "내 메뉴",
    pin_toggle: "즐겨찾기",
    pin_add: "이 화면 바로가기 등록",
    pin_remove: "바로가기 해제",
    palette_placeholder: "빠른 이동: 화면·프로젝트 이름 입력 (Esc 닫기)",
    palette_empty: "일치하는 항목 없음",
    palette_kind_view: "화면",
    palette_kind_project: "프로젝트",
    palette_kind_action: "동작",
    palette_mode_switch: "표시 모드 전환",
    tile_projects: "프로젝트 현황",
    tile_today: "오늘·지난 마감",
    tile_blocked: "차단 목록",
    mine_login: "로그인하면 내 담당 할 일이 보입니다",
    tile_nudges: "먼저 할 일",
    col_person: "담당",
    tile_mail: "최근 메일",
    tile_events: "최근 변경",
    w_goto: "할일 화면으로",
    evt_empty: "최근 변경 없음",
    tile_kpi: "핵심 지표",
    tile_unassigned: "미배정 할일",
    tile_artifacts: "최근 산출물",
    tile_contacts: "연락처",
    tile_gatewait: "단계 게이트 대기",
    tile_artifact_progress: "산출물 진행률",
    tile_mine: "내 할 일(To-Do)",
    tile_deadline_cal: "일정·마감 캘린더",
    bucket_overdue: "연체",
    bucket_thisweek: "이번 주 마감",
    bucket_later: "이후 예정",
    tile_reports_w: "보고서",
    reports_open: "보고서 생성기 열기",
    tile_meetings_w: "회의록",
    tile_onboarding: "시작하기 체크리스트",
    tile_training: "교육·세미나 일정",
    tile_stddocs: "표준 문서",
    tile_inbox: "미분류 메일함",
    tile_approval: "결재 대기",
    tile_notices: "쪽지·알림",
    tile_announce: "공지·업그레이드 내역",
    tile_purchase_w: "발주·입고 예정",
    tile_stocklow: "재고 부족",
    tile_bomchg: "BOM 변경",
    tile_vendors: "거래처 현황",
    tile_buyapprove: "구매 승인 대기",
    tile_teamload: "팀원별 할일",
    tile_throughput: "처리량 추세",
    tile_requests_w: "요청·이슈 큐",
    tile_analytics_w: "분석 대시보드",
    widget_soon: "준비 중",
    tile_config: "타일 설정",
    widget_add: "위젯 추가",
    widget_remove: "위젯 삭제",
    widget_resize: "크기 조절 (드래그)",
    widget_hint: "헤더를 끌어 자유 이동 · 우하단 모서리로 크기 조절 · ⟳ 새로고침",
    widget_all_shown: "모든 위젯이 표시 중",
    widget_collapse: "접기",
    widget_expand: "펼치기",
    widget_menu: "위젯 메뉴",
    widget_refresh: "새로고침",
    widget_search_ph: "이 위젯에서 검색…",
    claim_done: "내 일로 가져왔습니다",
    claim_mail_done: "메일을 내 할 일로 만들었습니다",
    claim_fail: "가져오기 실패",
    claim_taken: "이미 다른 사람의 할 일입니다",
    claim_existing: "기존 할 일을 내 일로 가져왔습니다",
    widget_popout: "크게 보기",
    widget_create: "작성",
    widget_arrange: "정렬",
    widget_reset: "초기화",
    confirm_reset: "위젯 배치를 처음 상태로 되돌릴까요? 지금 배치는 사라집니다.",
    confirm_remove: "이 위젯을 보드에서 뺄까요?",
    btn_confirm: "확인",
    btn_cancel: "취소",
    widget_drag_hint: "끌어다 보드에 놓아 추가",
    widget_placed: "배치됨",
    login: "로그인",
    logout: "로그아웃",
    login_user: "아이디",
    login_pw: "비밀번호",
    login_fail: "로그인 실패",
    password_change: "비밀번호 변경",
    password_current: "현재 비밀번호",
    password_new: "새 비밀번호",
    password_confirm: "새 비밀번호 확인",
    password_changed: "비밀번호가 변경되었습니다",
    password_mismatch: "새 비밀번호가 서로 다릅니다",
    password_wrong: "현재 비밀번호가 맞지 않습니다",
    password_too_short: "비밀번호는 6자 이상이어야 합니다",
    password_reset: "비밀번호 초기화",
    password_reset_done: "비밀번호를 초기화했습니다",
    acct_delete: "삭제",
    acct_delete_confirm: "이 계정을 삭제할까요? 비밀번호·수집 설정은 제거되고, 메일·할일은 기록으로 남습니다.",
    acct_delete_done: "계정을 삭제했습니다 (메일·할일 보존)",
    cannot_delete_self: "본인 계정은 삭제할 수 없습니다",
    cannot_delete_last_admin: "마지막 관리자는 삭제할 수 없습니다",
    next_actions: "다음 행동",
    admin_panel: "관리자",
    acct_new: "계정 추가",
    acct_user: "아이디",
    acct_name: "이름",
    acct_email: "이메일",
    acct_pw: "비밀번호",
    acct_role: "역할",
    acct_role_admin: "관리자",
    acct_role_member: "팀원",
    acct_status: "상태",
    acct_active: "활성",
    acct_disabled: "비활성",
    acct_disable: "비활성화",
    acct_enable: "활성화",
    acct_save: "저장",
    acct_create_admin: "첫 관리자 만들기",
    acct_setup_hint: "팀에서 쓰려면 먼저 관리자 계정을 만드세요",
    gate_title: "개발1팀 작전판",
    gate_sub: "팀 전용 공간입니다 — 계정으로 들어오세요",
    gate_tab_login: "로그인",
    gate_tab_register: "회원가입",
    gate_login_btn: "로그인",
    gate_register_btn: "가입하고 시작",
    gate_master_title: "첫 관리자 등록",
    gate_master_sub: "이 작전판의 첫 사용자입니다 — 관리자 계정을 만드세요",
    gate_master_btn: "관리자 만들기",
    gate_to_register: "계정이 없나요? 회원가입",
    gate_to_login: "이미 계정이 있나요? 로그인",
    register_fail: "가입 실패 — 아이디가 이미 있거나 입력이 부족합니다",
    mail_group_project: "프로젝트별",
    mail_group_date: "날짜별",
    mail_group_thread: "대화별",
    mail_thread_kind: "대화 유형",
    mail_source_ref: "소스",
    mail_preview_meta: "식별 정보",
    mailbox_provider: "메일함",
    mailbox_connect: "메일 연결",
    mailbox_connect_title: "메일 연결 — 이메일·비밀번호",
    mailbox_host: "POP3 호스트",
    mailbox_connect_save: "연결 저장",
    mailbox_connect_done: "메일 연결 저장됨 — 수집기가 받아옵니다",
    mailbox_connect_hint: "받기(POP3)+보내기(SMTP)가 같은 계정으로 등록됩니다. 비밀번호는 env 파일에만 저장(DB·로그 미기록). 실제 수신/발송은 별도 수집기·발송기.",
    mailbox_connect_incomplete: "호스트·이메일·비밀번호를 모두 입력하세요",
    mailbox_testing: "저장됨 · 연결 테스트 중…",
    mailbox_test_ok: "✅ 연결 성공",
    mailbox_test_fail: "❌ 연결 실패",
    mailbox_overwrite_note: "이미 메일이 연결돼 있습니다 — 저장하면 기존 설정을 덮어씁니다.",
    mailbox_saved: "✅ 저장되었습니다",
    mailbox_test_prompt: "연결을 테스트할까요?",
    mailbox_test_btn: "연결 테스트",
    know_source: "공개 출처",
    know_pointer: "소스카드 포인터",
    know_note: "원문은 저장하지 않습니다 — canon 메타·요약·출처 포인터만 표시합니다.",
    empty_knowledge: "지식 없음",
    stage_config: "① 설정 준비", stage_config_ok: "준비됨", stage_config_off: "미완",
    stage_fetch: "② 메일 수집", stage_fetch_ok: "관측됨", stage_fetch_off: "수집 전",
    stage_team: "③ 팀 사용", stage_team_ok: "준비됨", stage_team_off: "막힘",
    team_ready_title: "팀 사용 준비",
    assignee_none: "미배정", reassign_hint: "담당 나누기(팀원 선택)",
    gate_mode_to_biz: "실무 화면으로",
    gate_mode_to_fant: "판타지 화면으로",
    acct_taken: "이미 쓰는 아이디/이메일입니다",
    view_scope: "보기 대상",
    view_team: "팀 전체",
    perm_locked: "권한 없음",
    meeting_new: "회의 기록 추가",
    meeting_title: "제목",
    meeting_date: "일시",
    meeting_attendees: "참석",
    meeting_summary: "요지 위치(포인터)",
    meeting_add: "추가",
    meeting_actions: "액션아이템(할일)",
    empty_meetings: "회의록이 없습니다",
    gate_pass: "통과",
    gate_passable: "통과 가능",
    gate_held: "미충족",
    gate_cleared: "통과됨",
    gate_mode_label: "게이트 모드",
    gate_hard: "엄격(차단)",
    gate_soft: "경고만",
    gate_force: "강제 통과",
    gate_force_confirm: "미충족 게이트를 강제로 통과시킬까요?",
    gate_reason_open_items: "미완 할일",
    gate_reason_blocked_items: "차단 할일",
    gate_reason_artifacts_incomplete: "산출물 미완",
    gate_reason_required_artifacts_missing: "필수 기술자료 누락",
    gate_missing_summary: "누락 기술자료 보기",
    gate_reason_blocking_items_open: "하드 차단 사유 미해결",
    sched_title: "SE 일정 적용",
    sched_open: "일정 템플릿 적용",
    embed_title: "Smartsheet 보기",
    embed_add: "임베드 등록",
    embed_url: "Smartsheet 게시 URL",
    embed_url_bad: "Smartsheet 게시 URL 만 허용됩니다",
    embed_open: "외부 보기 열기",
    embed_empty: "등록된 임베드 없음",
    sched_apply: "템플릿 적용",
    sched_anchor_apply: "마일스톤 날짜 적용",
    sched_milestone: "마일스톤",
    sched_deliverable: "산출물",
    sched_offset: "기준일 ±일",
    sched_created: "개 생성됨",
    sched_shifted: "개 마감 재계산",
    sched_pick_project: "과제 선택",
    sched_back: "게이트로",
    cal_export: "캘린더 내보내기",
    cal_export_hint: "선택 담당의 마감 일정을 .ics 로 내려받아 구글/아웃룩 캘린더에 추가",
    sched_offset_unit: "일",
    sched_save: "저장",
    sched_saved: "저장됨",
    sched_timing_note: "산출물(무엇)은 지식에서, 일정(언제)은 여기서 직접 편집 — 추후 Codex 분석",
    att_required: "필수 기술자료",
    att_name: "파일명",
    att_pointer: "경로/URL(원문 미저장)",
    att_type: "자료 유형",
    att_add: "첨부 등록",
    att_satisfied: "충족",
    att_missing: "미충족",
    att_list: "등록된 기술자료",
    at_bom: "BOM",
    at_gerber: "Gerber",
    at_digikey: "Digikey",
    at_schematic: "회로도",
    at_pcb: "PCB",
    at_block_diagram: "블록도",
    calc_title: "계산기",
    calc_formula: "공식",
    calc_run: "계산",
    calc_verify: "검증 실행",
    calc_activate: "활성화",
    calc_draft: "초안",
    calc_active: "활성",
    calc_unsafe: "허용되지 않은 식",
    calc_example: "검증 예제",
    calc_add: "계산기 등록",
    calc_name: "계산기 이름",
    empty_gates: "스테이지가 없습니다",
    risk_title: "납기/CDR 위험",
    risk_sev_watch: "주의",
    risk_sev_risk: "위험",
    risk_sev_critical: "연체",
    risk_days_left: "남은일",
    risk_pct: "진행률",
    risk_milestone: "마일스톤",
    empty_risk: "위험 항목 없음",
    input_generate_btn: "산출물 초안 생성",
    input_generate_blocked: "입력 미충족",
    input_pending_keystone: "승인 대기 — 제안 큐 적재됨",
    prop_queue_title: "제안 큐 (승인 필요)",
    prop_kind_digest: "완료 요약",
    prop_next_actions: "다음 할 일",
    prop_na_add: "+ 할일로",
    prop_na_added: "✓ 생성됨",
    prop_na_done: "할 일로 만들었어요",
    prop_na_fail: "생성 실패",
    prop_na_noproj: "프로젝트를 알 수 없어 생성할 수 없어요",
    prop_approve: "승인",
    prop_reject: "반려",
    tile_proposals: "제안 큐",
    rec_run: "추천 스캔",
    prop_empty: "대기 중 제안 없음",
    chat_title: "ERP 챗봇",
    chat_version_label: "챗봇",
    chat_placeholder: "메타 기반 질문 (원문 미전송)",
    chat_send: "보내기",
    chat_mic: "음성 입력 — 브라우저 음성인식 사용(민감 내용 구두 입력 주의)",
    mic_listening: "듣는 중 — 누르면 종료",
    mic_unsupported: "이 브라우저는 음성 인식을 지원하지 않아요 (Chrome/Edge 사용)",
    mic_insecure: "HTTP 접속에서는 브라우저가 마이크를 차단해요 — 이 PC Chrome의 flags(unsafely-treat-insecure-origin-as-secure)에 이 주소를 예외 등록(1회)하거나 HTTPS(Tailscale)로 접속하세요",
    mic_err_not_allowed: "마이크 권한이 차단됐어요 — 주소창 자물쇠(사이트 설정)에서 마이크를 허용해 주세요",
    mic_err_network: "음성 인식 서비스 연결 실패 — 네트워크/방화벽 확인",
    mic_err_audio: "마이크 장치를 찾을 수 없어요 — 연결/OS 입력장치 확인",
    know_tab_shelf: "서가 현황",
    know_tab_wiki: "위키",
    know_tab_trunk: "줄기 그래프",
    know_tab_faq: "FAQ·매뉴얼",
    know_open_3d: "지식 그래프(3D) 열기",
    know_shelf_common: "공통 지식 (체계공학·표준·회사)",
    know_shelf_domain: "엔지니어링 도메인",
    know_shelf_project: "과제별 지식",
    know_shelf_approx: "※ ≈ 는 깊은 하위폴더까지 다 세지 못한 근사치입니다",
    know_col_area: "분야",
    know_col_files: "문서",
    know_col_latest: "최근 갱신",
    know_col_project: "과제",
    know_col_bookshelf: "장서",
    know_col_ingests: "수집 영수증",
    know_col_last_ingest: "최근 적재",
    know_col_candidates: "지식 후보",
    know_assets: "지식 자산",
    know_usage: "사용 기록 (얼마나 쓰였나)",
    know_usage_total: "기록된 사용",
    know_usage_last: "최근 사용",
    know_usage_unwired: "※ 응답 경로 자동 기록은 아직 미배선 — 수동 기록만 집계된 수치입니다",
    know_wiki_title: "위키 페이지",
    know_wiki_empty: "위키 페이지가 아직 없습니다",
    know_wiki_login: "로그인해야 볼 수 있습니다",
    trunk_empty: "줄기 데이터가 있는 과제가 없습니다",
    trunk_open_reviews: "미결 리뷰",
    trunk_hint: "가지를 클릭하면 하위가 지도에 펼쳐지고(다시 클릭하면 접힘), 상세 목록이 아래에 열립니다",
    trunk_col_type: "종류",
    trunk_col_label: "내용",
    trunk_more: "가지 +{n}개는 중요도 하위라 화면에서 생략됨",
    trunk_node_cap: "노드 상한 도달(일부 생략)",
    trunk_none_hub: "이 과제의 줄기(메타 그래프)가 아직 없습니다 — 엔진이 백엔드에서 키우기 시작하면 여기 나타납니다",
    trunk_view_map: "지도",
    trunk_view_tree: "목록",
    trunk_view_triage: "우선순위",
    trunk_kind_skeleton: "골격",
    trunk_kind_work: "작업",
    trunk_kind_history: "이력",
    trunk_kind_legacy: "옛 가지",
    trunk_kind_proposed: "제안",
    trunk_closed_mark: "완료",
    trunk_legacy_show: "옛 가지 {n}개 보기",
    trunk_legacy_hide: "옛 가지 숨기기",
    trunk_legend_hint: "원 크기=자료량 · 가운데 숫자=자료+할일 · 빨간 배지=미결 리뷰 · 점선=확정 대기 제안",
    trunk_occ_label: "회차",
    trunk_drag_hint: "작업(초록) 가지를 끌어 골격 게이트 가지에 놓으면 그 일의 SE 단계가 이동합니다",
    trunk_drag_only_gate: "게이트 골격 가지에만 놓을 수 있습니다",
    trunk_drag_done: "이동 완료 — 이벤트로 기록됨(되돌리기 가능)",
    trunk_drag_fail: "이동 실패",
    trunk_col_reviews: "미결 리뷰",
    trunk_col_sources: "자료",
    trunk_col_tasks: "할일",
    trunk_col_updated: "최근 갱신",
    trunk_tree_empty: "가지가 없습니다",
    trunk_triage_hint: "행을 클릭하면 그 가지의 이벤트·할일이 아래에 열립니다 (미결 리뷰 많은 순)",
    trunk_type_event: "이벤트",
    trunk_type_task: "할일",
    trunk_type_milestone: "마일스톤",
    trunk_type_actor: "관계자",
    chat_note: "매뉴얼 검색 기반 · 로컬 모델 연결 후 자연스러운 답변",
    chat_empty: "매뉴얼에서 찾아 답합니다 · 무엇이든 물어보세요",
    chat_new: "새 대화",
    chat_unmatched: "매뉴얼 미정리(질문 기록됨)",
    chat_wait_queued: "전송됨 · 답변 대기중",
    chat_wait_preparing: "답변 준비중",
    chat_wait_working: "매뉴얼과 로컬 모델을 확인 중",
    chat_wait_slow: "조금 오래 걸리고 있어요",
    chat_wait_queued_status: "질문이 전송됐어요. 답변 대기열에 올렸습니다.",
    chat_wait_preparing_status: "답변을 준비하고 있어요. 잠시만 기다려 주세요.",
    chat_wait_working_status: "매뉴얼을 찾고 로컬 모델 답변을 준비하고 있어요.",
    chat_wait_slow_status: "조금 오래 걸리고 있어요. 연속으로 보내지 않아도 서버에서 처리 중입니다.",
    chat_empty_reply: "응답을 받지 못했어요. 같은 질문을 한 번만 다시 보내 주세요.",
    chat_error_retry: "챗봇 응답이 잠깐 실패했어요. 같은 질문을 한 번만 다시 보내고, 반복되면 새 대화로 다시 시작해 주세요.",
    chat_done_status: "답변 완료",
    chat_timeout_retry: "답변이 오래 걸려 중단했어요. 입력창은 다시 열렸으니 같은 질문을 한 번만 다시 보내 주세요.",
    chat_login_required: "로그인이 풀렸어요. 다시 로그인한 뒤 질문해 주세요.",
    faq_new: "매뉴얼 추가",
    faq_topic: "분류",
    faq_q: "질문/제목",
    faq_a: "답변",
    faq_kw: "키워드",
    faq_ptr: "원문 위치",
    faq_unanswered: "미응답 질문(야간 갱신 대상)",
    faq_freq: "횟수",
    empty_faq: "매뉴얼이 없습니다",
    gen_worklog: "업무일지",
    pstage_request: "요청",
    pstage_quote: "견적",
    pstage_order: "발주",
    pstage_receive: "입고",
    pstage_inspect: "검수",
    pstage_closed: "완료",
    po_new: "발주 추가",
    po_title: "발주명",
    po_amount: "금액",
    po_party: "거래처",
    po_due: "납기",
    po_advance: "다음 단계",
    party_add: "거래처 추가",
    party_name: "거래처명",
    party_ledger: "거래이력",
    po_count: "발주",
    po_total: "총액",
    po_open: "진행",
    all_parties: "전체 거래처",
    ct_new: "연락처 추가",
    ct_name: "이름",
    ct_org: "소속",
    ct_role_label: "역할",
    ct_email: "이메일",
    ct_phone: "전화",
    empty_contacts: "연락처가 없습니다",
    inv_new: "부품 추가",
    part_no: "품번",
    part_type: "유형",
    part_grp: "그룹",
    part_min: "안전재고",
    part_uom: "단위",
    on_hand: "가용재고",
    inv_low: "부족",
    stock_adjust: "재고 조정",
    loc_label: "위치",
    empty_parts: "부품이 없습니다",
    bom_parent: "보드/부모",
    bom_add: "구성 추가",
    bom_qty: "수량",
    bom_ref: "참조",
    empty_bom: "BOM 구성이 없습니다",
    sw_note: "외부 공급사 실시간 조회는 보류 — 내부 재고 기준 판정",
    empty_stocklow: "부족 품목이 없습니다",
    empty_purchases: "발주가 없습니다",
    gen_report: "보고서",
    gen_note: "연구노트",
    gen_days: "기간(일)",
    gen_run: "초안 생성",
    gate_boss_hp: "보스 체력",
    gate_boss_slain: "처치 완료",
    kpi_blocked: "차단",
    team_health_label: "팀 상태",
    team_health_ok: "정상",
    team_health_watch: "주의",
    team_health_risk: "위험",
    team_health_clear: "막힘·연체 없음 — 정상 운영",
    team_health_jump: "가장 시급한 과제로 이동",
    kpi_overdue: "연체",
    kpi_today: "오늘 마감",
    kpi_inbox: "미분류 메일",
    col_remaining: "남은 일",
    col_due: "마감(연체·오늘·주내)",
    col_last_activity: "마지막 움직임",
    col_last_mail: "최근 메일",
    overdue: "연체",
    today_due: "오늘",
    week_due: "주내",
    not_connected: "미연결",
    class_active: "진행 과제",
    class_inbox: "미분류함",
    class_internal: "내부",
    class_archive: "보관",
    view_mail: "메일 보기",
    days_ago: "일 전",
    today_word: "오늘",
    sec_today: "오늘",
    sec_week: "이번 주",
    sec_older: "이전",
    period_90: "최근 90일",
    period_365: "최근 1년",
    period_all: "전체",
    dir_all: "수신+발신",
    label_new_ph: "새 라벨 이름",
    label_add: "라벨 추가",
    label_delete: "라벨 삭제",
    label_delete_confirm: "라벨 '%s' 삭제? 모든 메일에서도 제거됩니다.",
    label_deleted: "라벨 삭제됨",
    label_delete_fail: "라벨 삭제 실패",
    label_need_name: "라벨 이름을 입력하세요",
    label_created: "라벨 생성됨",
    label_exists: "이미 있는 라벨입니다",
    label_create_fail: "라벨 생성 실패",
    label_rename: "이름 변경",
    label_color: "색 변경(클릭)",
    label_color_fail: "색 변경 실패",
    label_rename_ph: "라벨 이름 변경",
    label_renamed: "라벨 이름 변경됨",
    label_rename_fail: "라벨 변경 실패",
    unlabeled: "미분류",
    detail_pointer: "원문 위치",
    detail_labels: "라벨",
    filter_clear: "필터 해제",
    nav_guide: "작업 가이드",
    guide_pick: "과제 선택",
    guide_add: "산출물 추가",
    guide_add_ph: "산출물 이름 (예: 체계요구사항명세서(SSRS))",
    guide_empty: "이 단계에 등록된 산출물이 없습니다 — 아래에서 추가",
    guide_progress: "진행",
    recipe_title: "작성법 위저드",
    recipe_pick: "문서 종류",
    recipe_required: "필요 입력",
    recipe_steps: "작성 절차",
    recipe_open: "작성법 보기",
    recipe_readonly: "읽기 전용 안내 — 체크는 추후 연결",
    guide_next: "다음 할 일",
    guide_principle: "폴더 순서 = 업무 순서. 위에서 아래로 따라 하면 됩니다.",
    tab_overview: "개요",
    tab_guide: "산출물",
    tab_mail: "메일",
    tab_history: "이력",
    tab_schedule: "일정",
    hub_anchor_apply: "마일스톤 날짜 적용",
    hub_no_schedule: "적용된 SE 일정 없음 — 템플릿을 적용하세요",
    back_home: "← 홈",
    item_new_ph: "새 할 일 제목",
    item_add: "할 일 추가",
    assignee_ph: "담당 (선택)",
    act_start: "시작",
    codex_chat_locked: "먼저 '시작'을 눌러야 대화가 열립니다",
    child_progress: "세부할일 진행(완료/전체)",
    split_subtasks: "세부할일로 나누기",
    split_hint: "한 줄에 하나씩 세부할일을 적으세요",
    split_empty: "세부할일을 한 줄 이상 적으세요",
    split_done: "개 세부할일을 만들었습니다",
    split_failed: "개 실패",
    split_ai_btn: "🤖 AI 제안",
    split_ai_wait: "AI 분석 중…",
    split_ai_off: "로컬 AI(ollama) 미연결 — 수동으로 입력하세요",
    split_ai_notask: "AI: 처리할 업무가 아닐 수 있음(공지?)",
    split_ai_nosplit: "AI: 쪼갤 필요 없음",
    split_ai_suggested: "AI 제안",
    party_label: "파티(워크플로우 체인)",
    act_done: "완료",
    act_block: "차단",
    act_resume: "재개",
    act_reopen: "다시 열기",
    act_edit: "수정",
    item_done_toast: "완료 처리됨 — '완료' 탭에서 '다시 열기'로 되돌릴 수 있어요",
    item_status_toast: "상태가 변경되었습니다",
    item_status_fail: "상태 변경 실패",
    done_no_date: "완료일 미상(이전 완료분)",
    done_view_note: "완료한 일을 완료 날짜별로 모았습니다. 각 항목의 '다시 열기'로 되돌릴 수 있어요.",
    act_save: "저장",
    act_cancel: "취소",
    act_delete: "삭제",
    act_save_failed: "저장 실패",
    act_delete_failed: "삭제 실패",
    item_delete_confirm: "이 할 일을 삭제(보관)할까요? 활성 목록에서 사라집니다.",
    promote_item: "할일로 승격",
    block_reason_ph: "차단 사유 (선택)",
    guide_make_item: "+ 할 일",
    origin_mail_badge: "메일",
    th_actions: "동작",
    assign_to: "과제로 분류",
    assign_make_items: "할일도 생성",
    assign_btn: "분류",
    mail_prev: "이전",
    assign_unassigned: "미배정",
    assign_who: "담당",
    tl_remaining: "남은",
    tl_chat: "대화",
    tl_no_scope: "이 팀원으로 전환할 수 없어요(보기범위 미설정)",
    inbox_assign_ph: "팀원에게…",
    inbox_assign_done: "배정했어요",
    inbox_assign_fail: "배정 실패",
    claim_unassigned_done: "미배정 할일로 등록했어요",
    prio_label: "우선",
    prio_set: "⭐ 우선",
    prio_unset: "우선 해제",
    an_none: "최근 완료 없음",
    an_recent: "최근 30일 완료",
    an_done: "완료",
    an_bywt: "업무종류",
    an_untyped: "기타",
    an_recent_done: "최근 완료",
    qe_assign_ph: "담당 변경…",
    qe_title_hint: "할일 이름 — 메일 제목이 아니라 '무엇을 할지'로 고쳐 쓰세요",
    qe_title_save: "이름 저장",
    qe_title_save_hint: "할일 이름 저장",
    qe_title_saved: "이름 저장됨",
    qe_title_empty: "할일 이름을 입력하세요",
    qe_mail_head: "원본 메일 내용 (해석이 맞는지 확인)",
    qe_mail_loading: "불러오는 중…",
    qe_mail_body_empty: "본문이 저장되지 않은 메일입니다(제목·발신자만)",
    qe_mail_none: "메일을 불러오지 못했습니다",
    qe_project_ph: "과제 변경…",
    qe_project_hint: "과제가 잘못 분류됐으면 여기서 바꾸세요",
    qe_project_moved: "과제를 변경했습니다",
    qe_project_move_fail: "과제 변경 실패",
    mail_spam: "스팸",
    mail_spam_hint: "스팸/광고 메일 — 이 메일 숨김 또는 발신자 차단",
    mail_spam_title: "스팸/광고 메일 처리",
    mail_spam_block_sender: "이 발신자 차단(앞으로도)",
    mail_spam_hide_one: "이 메일만 숨기기",
    mail_spam_member_note: "발신자 영구 차단은 관리자만 — 이 메일만 숨깁니다",
    mail_spam_manage_hint: "차단 규칙 관리: 관리자 패널 › 메일 제외 규칙",
    mail_spam_blocked: "발신자 차단",
    mail_spam_hidden: "이 메일을 숨겼습니다",
    mail_spam_fail: "차단 실패",
    mail_body: "본문 발췌",
    mail_thread_count: "이 대화의 메일 수",
    thread_assign_ph: "이 대화 담당…",
    thread_assign_hint: "이 대화 전체를 한 사람에게 배정",
    thread_proj_ph: "이 대화 분류…",
    thread_proj_hint: "이 대화 전체를 다른 과제로 이동",
    thread_assign_done: "%n건 대화를 %who에게 배정",
    thread_proj_done: "%n건 대화를 %p로 분류",
    thread_op_fail: "대화 처리 실패",
    mail_recipients: "이 메일을 받은 팀원 수 (중복 메일 1건으로 합침)",
    mail_conv: "이 대화의 메일 수 (분류하면 대화 전체가 함께 처리됩니다)",
    mail_body_none: "본문 미수집 — 수집기가 본문을 넘기면 여기 표시됩니다. 지금 원문은 메일함(Hiworks 등)에서 확인하세요.",
    mail_details: "세부정보",
    my_memory: "내 메모리",
    my_memory_hint: "내 업무 메모리 — 할일 시작 시 AI에 주입됩니다",
    my_memory_desc: "내 업무 스타일·규칙·자주 쓰는 맥락 — 할일을 시작(Codex 대화)할 때 그 담당자 메모리로 자동 주입됩니다. 평가 아님.",
    my_memory_ph: "예: 메일 회신은 존댓말·간결하게. 보고서는 결론부터. 자주 쓰는 약어…",
    my_memory_saved: "메모리 저장됨",
    mem_items_title: "누적 메모리 항목",
    mem_items_hint: "완료 지식이 자동으로 쌓이고, 시작 시 관련 항목이 주입됩니다",
    mem_item_empty: "아직 누적된 항목이 없습니다. 일을 완료하면 지식이 항목으로 쌓입니다.",
    mem_item_del: "이 항목 보관(주입 제외)",
    mem_item_deleted: "항목 보관됨",
    mem_item_add: "+ 항목",
    mem_item_add_ph: "새 항목(규칙·맥락) 직접 추가…",
    mem_item_added: "항목 추가됨",
    mem_t_pref: "선호",
    mem_t_fact: "사실",
    mem_t_open: "진행중",
    mem_t_dec: "결정",
    prop_mem_add: "+ 메모리",
    prop_mem_add_hint: "메모리에 추가 — 다음 시작에 주입",
    prop_mem_added: "✓ 메모리",
    prop_mem_added_toast: "메모리에 추가됨 — 다음 시작에 주입",
    prop_mem_fail: "메모리 추가 실패",
    mail_next: "다음",
    assign_next: "분류하고 다음 ▶",
    assign_next_hint: "이 메일을 분류하고 바로 다음 메일로",
    mail_kbd_hint: "j/k 또는 ↑↓ 이동 · Enter 분류하고 다음",
    mrule_title: "메일 제외 규칙",
    mrule_hint: "급여명세서 등 개인메일·차단 발신자를 팀 ERP에 안 받기",
    mrule_from: "발신자",
    mrule_subject: "제목",
    mrule_mailbox: "수신함",
    mrule_contains: "포함",
    mrule_equals: "완전일치",
    mrule_ph: "예: 급여명세서 / hr@회사.com",
    mrule_add: "규칙 추가",
    mrule_del: "삭제",
    mrule_empty: "규칙 없음 — 추가하면 해당 메일은 수집돼도 ERP에 안 들어옵니다",
    mrule_added: "규칙 추가됨",
    mrule_hidden_unit: "건 숨김",
    mrule_deleted: "규칙 삭제됨",
    mrule_fail: "추가 실패",
    mrule_need_pattern: "차단할 값을 입력하세요",
    rrule_title: "메일 → 과제 라우팅 규칙",
    rrule_hint: "Outlook 규칙처럼 — 조건에 맞는 메일을 과제로 자동 분류",
    rrule_empty: "사용자 규칙 없음 — 추가하면 새로 오는 메일이 그 과제로 바로 들어갑니다",
    rrule_ph: "예: KVDS / lig.co.kr",
    rrule_need_project: "대상 과제를 선택하세요",
    rrule_apply: "기존 적용",
    rrule_apply_tip: "받은함의 기존 메일에도 이 규칙 적용",
    rrule_apply_all: "모든 규칙 기존 메일에 적용",
    rrule_apply_confirm: "받은함(미분류)의 기존 메일에도 이 규칙을 지금 적용할까요?",
    rrule_apply_all_confirm: "모든 사용자 규칙을 받은함(미분류) 전체에 지금 적용할까요?",
    rrule_applied: "기존 적용",
    rrule_applied_all: "전체 적용",
    rrule_moved: "메일",
    rrule_moved_unit: "건 이동",
    rrule_items_moved: "할일 동행",
    rrule_engine: "엔진 규칙(자동 분류 정본)",
    rrule_engine_unit: "개 — 읽기 전용, 수정은 엔진 레인",
    rrule_engine_note: "정본: _workmeta/system/bindings/mail_project_router.yaml · 사용자 규칙이 이 표보다 우선 적용됩니다",
    rrule_col_id: "규칙",
    rrule_col_conf: "신뢰도",
    rrule_col_cond: "조건(요약)",
    rrule_body: "본문",
    rrule_conf_exact: "확정",
    rrule_conf_hint: "힌트(검토대기)",
    rrule_conf_amb: "애매(문의)",
    assign_done: "분류 완료",
    assign_fail: "분류 실패",
    assign_need_target: "분류할 과제를 고르세요",
    assign_made_short: "할일 생성",
    assign_unit: "건",
    master_del: "삭제",
    master_del_confirm: "삭제할까요? 되돌릴 수 없습니다.",
    master_deleted: "삭제됨",
    master_del_fail: "삭제 실패",
    master_edit: "수정",
    master_edited: "수정됨",
    master_edit_fail: "수정 실패",
    master_edit_name_ph: "이름",
    master_edit_title_ph: "제목",
    group_work: "운영",
    group_records: "기록·이력",
    group_supply: "자재·구매",
    group_knowledge: "지식·도구",
    group_team: "사람·팀",
    group_project: "프로젝트",
    group_task: "할 일",
    group_doc: "산출물·문서",
    group_comm: "메일·소통",
    group_material: "자재·거래처",
    proj_provisional: "정션 미연결",
    proj_new_id_ph: "과제코드 (예: P26-099)",
    proj_new_title_ph: "과제명",
    proj_new_btn: "＋ 임시 과제",
    proj_edit: "수정",
    proj_archive: "보관",
    proj_unarchive: "복원",
    proj_edit_title_ph: "과제명 수정",
    proj_edit_need_title: "과제명을 입력하세요",
    proj_edited: "과제 수정됨",
    proj_edit_fail: "과제 수정 실패",
    proj_archive_confirm: "이 과제를 보관할까요? 목록에서 숨겨집니다(메일·할일 보존, 복원 가능).",
    proj_archived: "보관됨",
    proj_unarchived: "복원됨",
    proj_archive_inbox: "받은함은 보관할 수 없습니다",
    proj_archive_fail: "보관 실패",
    proj_archived_badge: "보관됨",
    proj_arch_show: "보관 보기",
    proj_arch_hide: "보관 숨기기",
    proj_new_hint: "정션 동기화 전까지 '정션 미연결'로 표시됩니다",
    proj_new_admin: "임시 과제 생성은 관리자만 가능합니다",
    proj_new_dup: "이미 있는 과제 코드입니다",
    proj_new_fmt: "코드 형식: 영문/숫자/-/_ (예 P26-099)",
    req_empty: "등록된 요청 없음",
    thr_recent: "최근 14일",
    thr_done: "건 완료",
    thr_peak: "최고",
    thr_day: "일",
    thr_none: "최근 완료 없음",
    col_title: "제목",
    col_assignee: "담당",
    cls_suggested: "제안",
    cls_work_type: "업무유형",
    cls_link_kind: "연결대상",
    cls_link_ref: "연결 대상(산출물/BOM/업체…)",
    cls_completion: "완료기준(무엇을 하면 닫히나)",
    cls_confirm: "정식 등록",
    cls_confirmed: "정식 등록됨",
    compose_title: "Outlook 메일 쓰기",
    compose_hint: "Outlook 작성창이 열립니다 — 검토 후 직접 발송",
    compose_to: "받는 사람 (이름 또는 메일주소)",
    compose_cc: "참조 (선택)",
    compose_subject: "제목",
    compose_body: "본문 (Codex 초안을 붙여넣으세요)",
    compose_open: "Outlook로 열기",
    compose_copy: "전체 복사",
    compose_copied: "복사됨 — Outlook에 붙여넣기",
    compose_copy_fail: "복사 실패",
    compose_too_long: "본문이 길어 잘릴 수 있어요 — '전체 복사' 후 붙여넣기 권장",
    codex_fa_warn: "이 대화에서 Codex가 로컬 프로그램 실행·파일 쓰기를 하게 됩니다(Outlook 등). 메일 내용에 의한 위험이 있으니 필요할 때만 켜고, 끝나면 끄세요. 켤까요?",
    codex_fa_on: "전체권한 켜짐 — 다음 메시지부터 적용",
    codex_fa_off: "전체권한 꺼짐",
    mine_qa_ph: "빠른 할 일 추가…",
    mine_qa_add: "추가",
    mine_qa_need: "할 일 내용을 입력하세요",
    mine_qa_need_proj: "과제를 고르세요",
    mine_qa_done: "할 일을 추가했어요",
    mine_qa_fail: "추가 실패",
    inbox_see_all: "전체 %n건 분류하러 가기 →",
    codex_fa_fail: "변경 실패",
    cls_none: "분류할 항목 없음",
    cls_need: "업무유형 + 연결대상(또는 단계)이 있어야 정식 등록됩니다",
    promote_need_project: "과제로 분류 후 할 일로 승격",
    mail_reg_open: "＋ 메일 등록",
    mail_reg_subject: "제목",
    mail_reg_from: "상대(보낸/받는 사람)",
    req_no_project: "미연결",
    mail_reg_ptr: "원문 위치 포인터(Outlook/파일 경로)",
    mail_reg_body: "메일 본문",
    mail_reg_add: "등록",
    mail_reg_note: "메일 본문은 ERP 런타임 DB에 저장합니다. 원장·_workmeta에는 본문을 넣지 않습니다.",
    promote_already: "이미 할 일로 등록된 메일입니다",
    promote_done: "할 일로 등록됨",
    promote_done_next: "할 일로 등록됨 — '분류 필요'에서 분류하세요",
    promote_done_go: "할 일로 등록 — 분류로 이동",
    promote_go_triage: "분류하러 가기 →",
    mail_reg_need_subject: "제목을 입력하세요",
    mail_reg_done: "메일이 등록되었습니다",
    mail_reg_fail: "메일 등록에 실패했습니다",
    copied: "복사됨",
    copy_unsupported: "이 브라우저에서 복사가 지원되지 않습니다",
    risk_overdue: "지남",
    hub_triage_pre: "이 과제에 분류 필요 할 일",
    hub_triage_post: "건 — 업무 관리 › 내 할 일 › 분류 필요에서 처리",
    col_stage: "단계",
    col_link: "유형·연결",
    col_status: "상태",
    ct_role: "역할",
    hub_no_contacts: "연결된 연락처 없음",
    gate_reason: "사유",
    gate_blocked: "차단",
    hub_no_gates: "단계 없음",
    col_date: "일자",
    mt_actions: "액션",
    hub_no_meetings: "회의 없음",
    bom_parts: "부품·BOM",
    col_part: "부품",
    col_type: "유형",
    col_onhand: "재고",
    bom_purchase: "구매·발주",
    col_item: "품목",
    hub_no_bom: "자재·BOM 없음",
    risk_score: "위험도",
    hub_no_risk: "위험 항목 없음",
    req_note: "산출물별 필수 입력(요구사항) 충족 현황.",
    req_scope: "산출물",
    req_need: "필요",
    req_have: "충족",
    req_partial: "미충족",
    hub_no_req: "요구사항(입력 규칙) 없음",
    gate_admin_only: "게이트 모드는 관리자만 변경할 수 있습니다",
    gate_force_reason: "강제 통과 사유를 입력하세요 (기록에 남습니다)",
    req_promote: "할 일로",
    req_need_project: "과제 연결 필요",
    req_title_ph: "개발 요청 내용",
    req_requester_ph: "요청자",
    req_category_ph: "분류",
    req_cat_requirement: "요구사항",
    req_cat_feature: "기능 아이디어",
    req_cat_improve: "개선",
    req_cat_bug: "버그",
    req_cat_etc: "기타",
    req_add: "요청 등록",
    req_intake_note: "팀원 인입함 — 개발 요청·요구사항·업데이트하면 좋은 기능 아이디어·개선·버그를 자유롭게 적습니다(분류로 구분). 그대로 목록에 쌓이고, 과제에 연결해 '할 일로' 승격하면 분류 필요로 들어가 SE 기준점(단계·산출물·업무유형)에 거는 분류를 거칩니다.",
    req_col_title: "요청",
    req_col_who: "요청자",
    req_col_cat: "분류",
    status_archived: "보관함",
    status_unassigned: "미배정",
    act_restore: "복구",
    act_restore_failed: "복구 실패",
    item_delete_reason: "삭제(보관) 사유 — 비워도 됩니다. 이력에 남습니다. (취소하려면 Esc)",
    archived_note: "보관(삭제)된 할 일입니다. '복구'를 누르면 활성 목록으로 되돌아갑니다. 이력은 event_log에 그대로 남습니다.",
    nav_audit: "전체 이력(감사로그)",
    al_kind: "종류",
    al_actor: "행위자",
    al_desc: "설명",
    al_d7: "최근 7일",
    al_d30: "최근 30일",
    al_d90: "최근 90일",
    al_all: "전체 기간",
    al_noise: "조회·잡음 포함",
    al_more: "최근 300건만 — 필터로 좁혀보세요",
    widget_preset: "배치 불러오기",
    widget_my_saved: "내 저장 배치",
    widget_save_mine: "배치 저장",
    widget_saved_ok: "현재 배치를 저장했습니다.",
    widget_preset_group: "기본 프리셋",
    widget_del_slot: "선택한 저장 배치 삭제",
    widget_save_name: "저장할 배치 이름",
    widget_del_pick: "삭제할 저장 배치를 드롭다운에서 먼저 고르세요",
    widget_del_confirm: "이 저장 배치를 삭제할까요?"
  },
  fantasy: {
    app_title: "길드 작전판",
    app_version_label: "UI",
    browser_version_label: "브라우저",
    nav_home: "던전 지도",
    nav_items: "몬스터",
    nav_mail: "전령 기록",
    nav_artifacts: "전리품 창고",
    nav_search: "정찰",
    nav_projects: "원정 관리",
    proj_year_label: "착수 연대",
    proj_year_suffix: "년 착수",
    proj_year_none: "착수년 미지정",
    proj_tree_loading: "소환 중…",
    proj_tree_empty: "없음",
    proj_path_hint: "원정 클릭 → facet 열림",
    proj_path_cap: "원정 > facet",
    proj_start: "착수",
    proj_stage: "현재",
    proj_wl_overdue: "지연",
    proj_wl_today: "오늘",
    proj_wl_open: "진행",
    proj_wl_none: "진행 중 없음",
    nav_soon: "준비 중",
    soon_ai: "신탁(AI 제안)→길드장 승인 단일 표면. 착지면 owner 결정 후 활성됩니다.",
    soon_perm: "길드 율법(권한)·관문 모드(엄격/유연) 설정 표면. 후속 원정에서 활성됩니다.",
    project: "던전",
    stage: "스테이지",
    item: "몬스터",
    boss: "보스전",
    open: "출몰 중",
    blocked: "봉인됨",
    due_soon: "둠클락 임박",
    status_open: "출몰",
    status_doing: "교전 중",
    status_waiting: "대치 중",
    status_blocked: "봉인",
    status_done: "처치",
    status_unclassified: "미식별",
    mine_only: "내 퀘스트만",
    mine_all: "전체 보기",
    kpi_mail: "전령",
    mine_hint: "내 모험가(로그인명 또는 내 이름)가 맡은 퀘스트만",
    triage_note: "전령/의뢰에서 자동 포착됐지만 원정·관문·전리품 연결이 없는 임시 몬스터입니다. 식별해야 정식 사냥 목록에 들어갑니다.",
    backlog_meter: "몹 무리",
    freshness: "정찰 시각",
    empty_items: "출몰한 몬스터가 없습니다",
    empty_mail: "전령 기록이 없습니다",
    mail_claim_drop: "전령을 여기로 끌어다 놓으면 내 할 일이 됩니다",
    mail_claim_drop_multi: "임무·전령을 담당자에게 끌어다 놓으면 그 사람 할 일이 됩니다",
    mail_collect: "전령 수집",
    mail_collect_running: "전령 수집 중…",
    mail_collect_done: "전령 수집 완료",
    mail_collect_new: "신규",
    mail_collect_busy: "이미 수집 중입니다",
    mail_collect_admin: "길드마스터만 전령을 수집할 수 있습니다",
    mail_collect_fail: "전령 수집 실패",
    mailbox_owner: "전령함 주인",
    mailbox_shared: "공용 전령함",
    mail_unassign: "분류 취소",
    mail_unassign_hint: "받은함으로 되돌리기",
    mail_unassigned: "분류를 취소했다(받은함)",
    mail_unassign_fail: "분류 취소 실패",
    mail_delete: "메일 삭제",
    mail_delete_hint: "이 메일을 목록에서 삭제(재수집돼도 다시 안 보임)",
    mail_delete_confirm: "이 메일을 삭제할까요? 목록에서 사라집니다(재수집돼도 다시 안 보임).",
    mail_deleted: "메일을 삭제했습니다",
    mail_delete_fail: "메일 삭제 실패",
    mail_edit: "메일 수정",
    mail_edit_save: "저장",
    mail_edit_cancel: "취소",
    mail_edit_need_subject: "제목을 입력하세요",
    mail_edited: "메일을 수정했습니다",
    mail_edit_fail: "메일 수정 실패",
    mailbox_disconnect: "해제",
    mailbox_disconnect_hint: "연결 해제 + 비번 파일 삭제(전령·임무 보존)",
    mailbox_disconnect_confirm: "전령함 연결을 해제할까요? 저장된 비밀번호 파일이 삭제됩니다. (전령·임무는 보존)",
    mailbox_disconnected: "전령함 해제됨",
    mailbox_disconnect_fail: "전령함 해제 실패",
    claim_assigned_suffix: " 님에게 배정했습니다",
    claim_me: "나",
    empty_artifacts: "전리품이 없습니다",
    deliv_section: "전리품 도감",
    deliv_empty: "획득한 전리품이 없습니다 (tools/scan_se_foldertree.mjs --apply)",
    deliv_add: "전리품 추가",
    deliv_stage: "관문",
    deliv_no: "번호",
    deliv_criteria: "처치조건",
    deliv_add_done: "추가됨",
    deliv_exists: "같은 관문·번호 전리품이 이미 있습니다",
    di_open: "재료",
    di_hint: "전리품 재료(In) 관리",
    di_section: "재료",
    di_type: "종류",
    di_subfolder: "하위칸",
    di_file: "파일명",
    di_pointer: "상대 포인터",
    di_source: "출처",
    di_status: "상태",
    di_register: "등록",
    di_none: "등록된 재료 없음",
    di_need: "파일명 또는 포인터 필요",
    di_added: "등록됨",
    di_abs: "상대경로만 가능",
    di_st_needed: "필요",
    di_st_received: "수집됨",
    di_st_used: "반영됨",
    di_upload: "파일 올리기",
    di_upload_hint: "선택한 하위칸의 02_Input 에 올립니다",
    di_pick: "파일을 선택하세요",
    di_uploading: "올리는 중…",
    di_fileio_off: "파일 IO 비활성(DEV_ERP_FILEIO)",
    di_no_folder: "전리품 폴더 경로 미설정",
    di_too_large: "용량 초과",
    di_download: "내려받기",
    deliv_name: "전리품",
    deliv_submit: "등급",
    deliv_submit_draft: "미가공",
    deliv_submit_final: "각인완료",
    deliv_state: "상태",
    deliv_state_todo: "미발견",
    deliv_state_produced: "획득",
    deliv_state_review: "감정중",
    deliv_state_done: "봉인완료",
    deliv_due: "둠클락",
    deliv_pointer: "전리품 보관함",
    deliv_due_save: "봉인",
    deliv_due_owner: "수동각인",
    deliv_due_auto: "신탁",
    deliv_due_ingest: "미정",
    deliv_due_saved: "봉인됨",
    deliv_due_note: "둠클락(언제)은 도감에 없어 비어 옵니다 — 직접 새겨 바꾸세요. 수동각인한 둠클락은 재정찰이 덮지 않습니다. 나중에 신탁(Codex)이 분석해 채웁니다.",
    deliv_rv_self: "본인감정",
    deliv_rv_team: "원탁감정",
    deliv_rv_to_self: "본인감정 완료",
    deliv_rv_to_team: "원탁감정 완료",
    deliv_rv_to_lead: "길드장 봉인(완료)",
    deliv_rv_back: "되돌리기",
    deliv_rv_need_file: "전리품 획득(작성됨) 후 감정",
    deliv_spawn_task: "퀘스트로",
    deliv_spawn_hint: "이 전리품을 제작하는 퀘스트 생성(관문·연결·둠클락 상속)",
    deliv_already_task: "이미 퀘스트 있음",
    search_hint: "던전·상대·몬스터 이름으로 정찰",
    th_status: "상태",
    th_due: "둠클락",
    th_assignee: "담당 유닛",
    th_automation: "자동사냥",
    th_time: "시각",
    th_direction: "방향",
    th_subject: "전갈 제목",
    th_counterpart: "상대",
    th_kind: "종류",
    th_updated: "갱신",
    th_pointer: "보관 위치",
    all_label: "전체",
    mail_in: "도착",
    mail_out: "발신",
    copy: "복사",
    mode_label: "표시 모드",
    search_placeholder: "정찰",
    group_pinned: "내 장비",
    pin_toggle: "애용",
    pin_add: "이 화면 단축 등록",
    pin_remove: "단축 해제",
    palette_placeholder: "신속 이동: 장소·던전 이름 입력 (Esc 닫기)",
    palette_empty: "찾을 수 없음",
    palette_kind_view: "장소",
    palette_kind_project: "던전",
    palette_kind_action: "명령",
    palette_mode_switch: "표시 모드 전환",
    tile_projects: "던전 현황",
    tile_today: "둠클락 임박",
    tile_blocked: "봉인 목록",
    mine_login: "입장하면 내 퀘스트가 보입니다",
    tile_nudges: "급선무",
    col_person: "대원",
    tile_mail: "최근 전령",
    tile_events: "최근 전황",
    w_goto: "퀘스트로 이동",
    evt_empty: "최근 전황 없음",
    tile_kpi: "전황 지표",
    tile_unassigned: "미편성 몬스터",
    tile_artifacts: "최근 전리품",
    tile_contacts: "인명록",
    tile_gatewait: "보스전 대기",
    tile_artifact_progress: "공략률",
    tile_mine: "내 몬스터",
    tile_deadline_cal: "둠클락 달력",
    bucket_overdue: "기한 초과",
    bucket_thisweek: "금주 관문",
    bucket_later: "다가올 운명",
    tile_reports_w: "보고 두루마리",
    reports_open: "연대기 작성소 열기",
    tile_meetings_w: "회의 연대기",
    tile_onboarding: "신병 훈련",
    tile_training: "집회 공지",
    tile_stddocs: "비전 서고",
    tile_inbox: "의뢰 접수처",
    tile_approval: "승인 의뢰",
    tile_notices: "길드 전갈",
    tile_announce: "길드 포고",
    tile_purchase_w: "보급 예정",
    tile_stocklow: "재고 경보",
    tile_bomchg: "설계 변경",
    tile_vendors: "상단 현황",
    tile_buyapprove: "보급 승인",
    tile_teamload: "유닛별 전선",
    tile_throughput: "토벌 추세",
    tile_requests_w: "의뢰 게시판",
    tile_analytics_w: "점성술 탑",
    widget_soon: "준비 중",
    tile_config: "타일 설정",
    widget_add: "위젯 편성",
    widget_remove: "위젯 해제",
    widget_resize: "크기 조절 (드래그)",
    widget_hint: "머리를 끌어 자유 이동 · 우하단 모서리로 크기 조절 · ⟳ 새로고침",
    widget_all_shown: "모든 위젯이 배치됨",
    widget_collapse: "접기",
    widget_expand: "펼치기",
    widget_menu: "위젯 메뉴",
    widget_refresh: "새로고침",
    widget_search_ph: "이 위젯에서 검색…",
    claim_done: "내 일로 가져왔습니다",
    claim_mail_done: "메일을 내 할 일로 만들었습니다",
    claim_fail: "가져오기 실패",
    claim_taken: "이미 다른 사람의 할 일입니다",
    claim_existing: "기존 할 일을 내 일로 가져왔습니다",
    widget_popout: "크게 보기",
    widget_create: "소환",
    widget_arrange: "정렬",
    widget_reset: "초기화",
    confirm_reset: "위젯 배치를 처음 상태로 되돌릴까요? 지금 배치는 사라집니다.",
    confirm_remove: "이 위젯을 보드에서 뺄까요?",
    btn_confirm: "확인",
    btn_cancel: "취소",
    widget_drag_hint: "끌어다 보드에 놓아 편성",
    widget_placed: "배치됨",
    login: "입장",
    logout: "퇴장",
    login_user: "아이디",
    login_pw: "비밀번호",
    login_fail: "입장 실패",
    password_change: "암호 변경",
    password_current: "현재 암호",
    password_new: "새 암호",
    password_confirm: "새 암호 확인",
    password_changed: "암호가 변경되었습니다",
    password_mismatch: "새 암호가 서로 다릅니다",
    password_wrong: "현재 암호가 맞지 않습니다",
    password_too_short: "암호는 6자 이상이어야 합니다",
    password_reset: "암호 초기화",
    password_reset_done: "암호를 초기화했습니다",
    acct_delete: "삭제",
    acct_delete_confirm: "이 계정을 삭제할까요? 암호·수집 설정은 거두고, 전령·할일은 기록으로 남습니다.",
    acct_delete_done: "계정을 삭제했습니다 (전령·할일 보존)",
    cannot_delete_self: "본인 계정은 삭제할 수 없습니다",
    cannot_delete_last_admin: "마지막 관리자는 삭제할 수 없습니다",
    next_actions: "다음 행동",
    admin_panel: "길드마스터",
    acct_new: "대원 등록",
    acct_user: "아이디",
    acct_name: "이름",
    acct_email: "이메일",
    acct_pw: "비밀번호",
    acct_role: "역할",
    acct_role_admin: "길드마스터",
    acct_role_member: "대원",
    acct_status: "상태",
    acct_active: "활성",
    acct_disabled: "비활성",
    acct_disable: "비활성화",
    acct_enable: "활성화",
    acct_save: "저장",
    acct_create_admin: "첫 길드마스터 만들기",
    acct_setup_hint: "파티로 쓰려면 먼저 길드마스터를 만드세요",
    gate_title: "달빛 길드 작전판",
    gate_sub: "길드원만 들어설 수 있는 곳 — 문장을 보이세요",
    gate_tab_login: "입성",
    gate_tab_register: "길드 가입",
    gate_login_btn: "입성",
    gate_register_btn: "길드 입단",
    gate_master_title: "초대 길드마스터 등극",
    gate_master_sub: "이 길드의 첫 주인입니다 — 길드마스터로 등극하세요",
    gate_master_btn: "길드마스터 등극",
    gate_to_register: "아직 길드원이 아닌가요? 가입",
    gate_to_login: "이미 길드원인가요? 입성",
    register_fail: "가입 실패 — 이름이 겹치거나 정보가 부족합니다",
    mail_group_project: "던전별",
    mail_group_date: "날짜별",
    mail_group_thread: "서신줄기별",
    mail_thread_kind: "서신 유형",
    mail_source_ref: "표식",
    mail_preview_meta: "식별 표식",
    mailbox_provider: "전령함",
    mailbox_connect: "전령함 연결",
    mailbox_connect_title: "전령함 연결 — 이메일·비밀번호",
    mailbox_host: "POP3 호스트",
    mailbox_connect_save: "연결 저장",
    mailbox_connect_done: "전령함 연결 저장됨 — 수집대가 받아옵니다",
    mailbox_connect_hint: "받기(POP3)+보내기(SMTP)가 같은 계정으로 등록됩니다. 비밀번호는 env 파일에만 봉인(DB·기록 미기록). 실제 수신/발송은 별도 수집대·발송대.",
    mailbox_connect_incomplete: "호스트·이메일·비밀번호를 모두 입력하세요",
    mailbox_testing: "저장됨 · 연결 테스트 중…",
    mailbox_test_ok: "✅ 연결 성공",
    mailbox_test_fail: "❌ 연결 실패",
    mailbox_overwrite_note: "이미 메일이 연결돼 있습니다 — 저장하면 기존 설정을 덮어씁니다.",
    mailbox_saved: "✅ 저장되었습니다",
    mailbox_test_prompt: "연결을 테스트할까요?",
    mailbox_test_btn: "연결 테스트",
    know_source: "공개 출처",
    know_pointer: "소스카드 포인터",
    know_note: "원문은 봉인 — 전승의 요지·출처 표식만 보입니다.",
    empty_knowledge: "전승 없음",
    stage_config: "① 편성 준비", stage_config_ok: "준비됨", stage_config_off: "미완",
    stage_fetch: "② 전령 수집", stage_fetch_ok: "관측됨", stage_fetch_off: "수집 전",
    stage_team: "③ 파티 출진", stage_team_ok: "준비됨", stage_team_off: "막힘",
    team_ready_title: "파티 출진 준비",
    assignee_none: "미배정", reassign_hint: "유닛 배정(파티원 선택)",
    gate_mode_to_biz: "실무 화면으로",
    gate_mode_to_fant: "판타지 화면으로",
    acct_taken: "이미 쓰는 아이디/이메일입니다",
    view_scope: "보기 대상",
    view_team: "파티 전체",
    perm_locked: "권한 없음",
    meeting_new: "원탁 기록 추가",
    meeting_title: "안건",
    meeting_date: "일시",
    meeting_attendees: "참석 유닛",
    meeting_summary: "기록물 위치",
    meeting_add: "기록",
    meeting_actions: "결의(몬스터)",
    empty_meetings: "원탁 기록이 없습니다",
    gate_pass: "돌파",
    gate_passable: "돌파 가능",
    gate_held: "봉인 중",
    gate_cleared: "돌파함",
    gate_mode_label: "관문 규칙",
    gate_hard: "엄격",
    gate_soft: "경고",
    gate_force: "강제 돌파",
    gate_force_confirm: "미충족 관문을 강제로 돌파할까요?",
    gate_reason_open_items: "미처치 몬스터",
    gate_reason_blocked_items: "봉인 몬스터",
    gate_reason_artifacts_incomplete: "전리품 미완",
    gate_reason_required_artifacts_missing: "필수 장비 누락",
    gate_missing_summary: "결여 장비 보기",
    gate_reason_blocking_items_open: "봉인 해제 실패",
    sched_title: "운명 직조",
    sched_open: "운명 직조 시작",
    embed_title: "외부 점술판",
    embed_add: "점술판 봉입",
    embed_url: "점술판 표식(게시 URL)",
    embed_url_bad: "허락된 점술판만 가능합니다",
    embed_open: "점술판 펼치기",
    embed_empty: "봉입된 점술판 없음",
    sched_apply: "운명 새기기",
    sched_anchor_apply: "기준일 봉인",
    sched_milestone: "기준 관문",
    sched_deliverable: "전리품",
    sched_offset: "기준 ±일",
    sched_created: "개 출몰",
    sched_shifted: "개 운명 이동",
    sched_pick_project: "던전 선택",
    sched_back: "관문으로",
    cal_export: "원정 일지 내보내기",
    cal_export_hint: "선택 대원의 마감 일정을 .ics 로 내려받아 달력에 추가",
    sched_offset_unit: "일",
    sched_save: "각인",
    sched_saved: "각인됨",
    sched_timing_note: "전리품(무엇)은 전승에서, 기일(언제)은 여기서 직접 새김 — 추후 분석",
    att_required: "필수 장비",
    att_name: "물품명",
    att_pointer: "위치 표식",
    att_type: "장비 종류",
    att_add: "장비 등재",
    att_satisfied: "갖춤",
    att_missing: "결여",
    att_list: "보관 장비",
    at_bom: "부품목록",
    at_gerber: "제작판",
    at_digikey: "조달표",
    at_schematic: "설계도",
    at_pcb: "기판",
    at_block_diagram: "배치도",
    calc_title: "계산 마법구",
    calc_formula: "주문",
    calc_run: "시전",
    calc_verify: "검증",
    calc_activate: "각인",
    calc_draft: "미각인",
    calc_active: "각인됨",
    calc_unsafe: "금지된 주문",
    calc_example: "검증 시료",
    calc_add: "마법구 각인",
    calc_name: "마법구 이름",
    empty_gates: "관문이 없습니다",
    risk_title: "원정 위기",
    risk_sev_watch: "경계",
    risk_sev_risk: "위급",
    risk_sev_critical: "낙오",
    risk_days_left: "남은일",
    risk_pct: "공략률",
    risk_milestone: "기준 관문",
    empty_risk: "위기 없음",
    input_generate_btn: "전리품 제작",
    input_generate_blocked: "재료 부족",
    input_pending_keystone: "제작 승인 대기 — 제안 큐 적재됨",
    prop_queue_title: "제안 두루마리 (승인 필요)",
    prop_kind_digest: "완료 보고",
    prop_next_actions: "다음 임무",
    prop_na_add: "+ 임무로",
    prop_na_added: "✓ 소환됨",
    prop_na_done: "임무로 소환했어요",
    prop_na_fail: "소환 실패",
    prop_na_noproj: "원정대를 알 수 없어 소환 불가",
    prop_approve: "윤허",
    prop_reject: "기각",
    tile_proposals: "제안 두루마리",
    rec_run: "정찰 소집",
    prop_empty: "대기 중 제안 없음",
    chat_title: "길드 조언자",
    chat_version_label: "조언자",
    chat_placeholder: "메타 기반 질문 (원문 미전송)",
    chat_send: "전송",
    chat_mic: "음성 주문 — 브라우저 음성인식 사용(민감 내용 구두 입력 주의)",
    mic_listening: "귀 기울이는 중 — 누르면 멈춤",
    mic_unsupported: "이 브라우저는 음성 마법을 지원하지 않는다 (Chrome/Edge 사용)",
    mic_insecure: "HTTP 관문에서는 음성 마법이 봉인된다 — 이 PC Chrome의 flags(unsafely-treat-insecure-origin-as-secure)에 이 주소를 예외 등록(1회)하거나 HTTPS(Tailscale) 관문으로 입장하라",
    mic_err_not_allowed: "마이크 권한이 봉인됐다 — 주소창 자물쇠(사이트 설정)에서 마이크를 허용하라",
    mic_err_network: "음성 전달망 연결 실패 — 네트워크/방화벽 확인",
    mic_err_audio: "마이크 장치를 찾을 수 없다 — 연결/OS 입력장치 확인",
    know_tab_shelf: "서고 현황",
    know_tab_wiki: "전승록",
    know_tab_trunk: "세계수",
    know_tab_faq: "문답·지침서",
    know_open_3d: "지식 성좌도(3D) 열기",
    know_shelf_common: "공용 비전 (체계공학·율법·길드)",
    know_shelf_domain: "비술 계보",
    know_shelf_project: "원정별 전승",
    know_shelf_approx: "※ ≈ 는 깊은 계보까지 다 세지 못한 어림수다",
    know_col_area: "계보",
    know_col_files: "두루마리",
    know_col_latest: "최근 갱신",
    know_col_project: "원정",
    know_col_bookshelf: "장서",
    know_col_ingests: "수집 인장",
    know_col_last_ingest: "최근 봉인",
    know_col_candidates: "전승 후보",
    know_assets: "서고 자산",
    know_usage: "열람 흔적 (얼마나 쓰였나)",
    know_usage_total: "기록된 열람",
    know_usage_last: "최근 열람",
    know_usage_unwired: "※ 응답 경로 자동 기록은 아직 미배선 — 수동 기록만 집계된 수치다",
    know_wiki_title: "전승록 페이지",
    know_wiki_empty: "전승록이 아직 비어 있다",
    know_wiki_login: "입장(로그인)해야 열람할 수 있다",
    trunk_empty: "세계수가 자란 원정이 없다",
    trunk_open_reviews: "미결 심판",
    trunk_hint: "가지를 클릭하면 하위가 지도에 펼쳐지고(다시 클릭하면 접힌다), 상세 목록이 아래에 열린다",
    trunk_col_type: "종류",
    trunk_col_label: "내용",
    trunk_more: "가지 +{n}개는 중요도 하위라 화면에서 생략됨",
    trunk_node_cap: "노드 상한 도달(일부 생략)",
    trunk_none_hub: "이 원정의 세계수가 아직 자라지 않았다 — 엔진이 백엔드에서 키우기 시작하면 여기 나타난다",
    trunk_view_map: "성좌도",
    trunk_view_tree: "계보록",
    trunk_view_triage: "우선순위",
    trunk_kind_skeleton: "기둥",
    trunk_kind_work: "퀘스트 가지",
    trunk_kind_history: "연대기",
    trunk_kind_legacy: "낡은 가지",
    trunk_kind_proposed: "제안",
    trunk_closed_mark: "완수",
    trunk_legacy_show: "낡은 가지 {n}개 보기",
    trunk_legacy_hide: "낡은 가지 숨기기",
    trunk_legend_hint: "원 크기=전승량 · 가운데 숫자=전승+의뢰 · 붉은 인장=미결 심판 · 점선=봉인 대기 제안",
    trunk_occ_label: "연대기 장",
    trunk_drag_hint: "퀘스트(초록) 가지를 끌어 기둥 관문에 놓으면 그 의뢰의 단계가 이동한다",
    trunk_drag_only_gate: "관문 기둥에만 놓을 수 있다",
    trunk_drag_done: "이동 완수 — 연대기에 기록됨(되돌릴 수 있다)",
    trunk_drag_fail: "이동 실패",
    trunk_col_reviews: "미결 심판",
    trunk_col_sources: "전승",
    trunk_col_tasks: "의뢰",
    trunk_col_updated: "최근 갱신",
    trunk_tree_empty: "가지가 없다",
    trunk_triage_hint: "줄을 클릭하면 그 가지의 사건·의뢰가 아래에 열린다 (미결 심판 많은 순)",
    trunk_type_event: "사건",
    trunk_type_task: "의뢰",
    trunk_type_milestone: "이정표",
    trunk_type_actor: "관계자",
    chat_note: "매뉴얼 검색 기반 · 로컬 모델 연결 후 자연스러운 답변",
    chat_empty: "기록에서 찾아 답한다 · 무엇이든 물어보라",
    chat_new: "새 대화",
    chat_unmatched: "기록 미정리(질문 기록됨)",
    chat_wait_queued: "전송됨 · 답변 대기중",
    chat_wait_preparing: "답변 준비중",
    chat_wait_working: "기록과 로컬 모델 확인 중",
    chat_wait_slow: "조금 오래 걸리고 있음",
    chat_wait_queued_status: "질문이 전송됐다. 답변 대기열에 올렸다.",
    chat_wait_preparing_status: "답변을 준비하고 있다. 잠시만 기다려 달라.",
    chat_wait_working_status: "기록을 찾고 로컬 모델 답변을 준비하고 있다.",
    chat_wait_slow_status: "조금 오래 걸리고 있다. 연속으로 보내지 않아도 서버에서 처리 중이다.",
    chat_empty_reply: "응답을 받지 못했다. 같은 질문을 한 번만 다시 보내 달라.",
    chat_error_retry: "조언자 응답이 잠깐 실패했다. 같은 질문을 한 번만 다시 보내고, 반복되면 새 대화로 다시 시작해 달라.",
    chat_done_status: "답변 완료",
    chat_timeout_retry: "답변이 오래 걸려 중단했다. 입력창은 다시 열렸으니 같은 질문을 한 번만 다시 보내 달라.",
    chat_login_required: "로그인이 풀렸다. 다시 로그인한 뒤 질문해 달라.",
    faq_new: "기록 추가",
    faq_topic: "분류",
    faq_q: "질문/제목",
    faq_a: "답변",
    faq_kw: "키워드",
    faq_ptr: "원문 위치",
    faq_unanswered: "미응답 질문(야간 갱신 대상)",
    faq_freq: "횟수",
    empty_faq: "기록이 없습니다",
    gen_worklog: "일지",
    pstage_request: "의뢰",
    pstage_quote: "견적",
    pstage_order: "발주",
    pstage_receive: "입고",
    pstage_inspect: "검수",
    pstage_closed: "완료",
    po_new: "발주 추가",
    po_title: "발주명",
    po_amount: "금액",
    po_party: "상단",
    po_due: "도착 예정",
    po_advance: "다음 단계",
    party_add: "상단 등록",
    party_name: "상단명",
    party_ledger: "거래이력",
    po_count: "발주",
    po_total: "총액",
    po_open: "진행",
    all_parties: "전체 상단",
    ct_new: "인물 등록",
    ct_name: "이름",
    ct_org: "소속",
    ct_role_label: "역할",
    ct_email: "이메일",
    ct_phone: "전화",
    empty_contacts: "인명록이 비었습니다",
    inv_new: "물자 등록",
    part_no: "품번",
    part_type: "유형",
    part_grp: "그룹",
    part_min: "안전재고",
    part_uom: "단위",
    on_hand: "가용",
    inv_low: "부족",
    stock_adjust: "재고 조정",
    loc_label: "위치",
    empty_parts: "물자가 없습니다",
    bom_parent: "장비/부모",
    bom_add: "구성 추가",
    bom_qty: "수량",
    bom_ref: "참조",
    empty_bom: "구성이 없습니다",
    sw_note: "외부 상단 실시간 조회는 보류 — 내부 재고 기준",
    empty_stocklow: "부족 물자 없음",
    empty_purchases: "발주가 없습니다",
    gen_report: "전황보고",
    gen_note: "연구기록",
    gen_days: "기간(일)",
    gen_run: "초안 생성",
    gate_boss_hp: "보스 체력",
    gate_boss_slain: "처치 완료",
    kpi_blocked: "봉인",
    team_health_label: "원정대 상태",
    team_health_ok: "평온",
    team_health_watch: "경계",
    team_health_risk: "위급",
    team_health_clear: "봉인·지체 없음 — 평온",
    team_health_jump: "가장 급한 원정으로 이동",
    kpi_overdue: "둠클락 경과",
    kpi_today: "오늘 둠클락",
    kpi_inbox: "미배정 전령",
    col_remaining: "남은 몬스터",
    col_due: "둠클락(경과·오늘·주내)",
    col_last_activity: "마지막 전황",
    col_last_mail: "최근 전령",
    overdue: "경과",
    today_due: "오늘",
    week_due: "주내",
    not_connected: "미정찰",
    class_active: "원정 중 던전",
    class_inbox: "의뢰 접수처",
    class_internal: "길드 내부",
    class_archive: "봉인 서고",
    view_mail: "전령 보기",
    days_ago: "일 전",
    today_word: "오늘",
    sec_today: "오늘",
    sec_week: "이번 주",
    sec_older: "이전",
    period_90: "최근 90일",
    period_365: "최근 1년",
    period_all: "전체",
    dir_all: "도착+발신",
    label_new_ph: "새 문장(紋章) 이름",
    label_add: "문장 추가",
    label_delete: "문장 삭제",
    label_delete_confirm: "문장 '%s' 삭제? 모든 전령에서도 제거됩니다.",
    label_deleted: "문장 삭제됨",
    label_delete_fail: "문장 삭제 실패",
    label_need_name: "문장 이름을 입력하세요",
    label_created: "문장 생성됨",
    label_exists: "이미 있는 문장입니다",
    label_create_fail: "문장 생성 실패",
    label_rename: "이름 변경",
    label_color: "색 변경(클릭)",
    label_color_fail: "색 변경 실패",
    label_rename_ph: "문장 이름 변경",
    label_renamed: "문장 이름 변경됨",
    label_rename_fail: "문장 변경 실패",
    unlabeled: "미배정",
    detail_pointer: "원문 위치",
    detail_labels: "문장",
    filter_clear: "필터 해제",
    nav_guide: "공략 진행",
    guide_pick: "던전 선택",
    guide_add: "전리품 추가",
    guide_add_ph: "전리품 이름 (예: 체계요구사항명세서(SSRS))",
    guide_empty: "이 층에 등록된 전리품이 없습니다 — 아래에서 추가",
    guide_progress: "공략률",
    recipe_title: "제작 비법서",
    recipe_pick: "기록 종류",
    recipe_required: "필요 재료",
    recipe_steps: "제작 단계",
    recipe_open: "비법 펼치기",
    recipe_readonly: "열람 전용 — 표식은 추후 연결",
    guide_next: "다음 공략",
    guide_principle: "층 순서 = 공략 순서. 위에서 아래로 따라가면 됩니다.",
    tab_overview: "전황",
    tab_guide: "전리품",
    tab_mail: "전령",
    tab_history: "연대기",
    tab_schedule: "운명표",
    hub_anchor_apply: "기준일 봉인",
    hub_no_schedule: "직조된 운명 없음 — 운명을 직조하세요",
    back_home: "← 지도",
    item_new_ph: "새 몬스터 이름",
    item_add: "몬스터 소환",
    assignee_ph: "담당 유닛 (선택)",
    act_start: "교전",
    codex_chat_locked: "먼저 '교전'을 눌러야 대화가 열립니다",
    child_progress: "하위 임무 진행(처치/전체)",
    split_subtasks: "하위 임무로 쪼개기",
    split_hint: "한 줄에 하나씩 하위 임무를 적으세요",
    split_empty: "하위 임무를 한 줄 이상 적으세요",
    split_done: "개 하위 임무를 만들었습니다",
    split_failed: "개 실패",
    split_ai_btn: "🤖 AI 제안",
    split_ai_wait: "AI 점술 중…",
    split_ai_off: "로컬 AI(ollama) 미연결 — 직접 적으세요",
    split_ai_notask: "AI: 처리할 임무가 아닐 수 있음(공지?)",
    split_ai_nosplit: "AI: 쪼갤 필요 없음",
    split_ai_suggested: "AI 제안",
    party_label: "파티(워크플로우 체인)",
    act_done: "처치",
    act_block: "봉인",
    act_resume: "해제",
    act_reopen: "부활",
    act_edit: "수정",
    item_done_toast: "처치 완료 — '처치' 탭에서 '부활'로 되돌릴 수 있어요",
    item_status_toast: "상태가 변경되었습니다",
    item_status_fail: "상태 변경 실패",
    done_no_date: "처치일 미상(이전 처치분)",
    done_view_note: "처치한 몬스터를 처치 날짜별로 모았습니다. 각 항목의 '부활'로 되돌릴 수 있어요.",
    act_save: "저장",
    act_cancel: "취소",
    act_delete: "보관",
    act_save_failed: "저장 실패",
    act_delete_failed: "보관 실패",
    item_delete_confirm: "이 항목을 보관할까요? 활성 목록에서 사라집니다.",
    promote_item: "몬스터로 소환",
    block_reason_ph: "봉인 사유 (선택)",
    guide_make_item: "+ 몬스터",
    origin_mail_badge: "전령",
    th_actions: "명령",
    assign_to: "던전에 편입",
    assign_make_items: "몬스터로 출몰",
    assign_btn: "편입",
    mail_prev: "이전",
    assign_unassigned: "미배정",
    assign_who: "담당",
    tl_remaining: "남은",
    tl_chat: "대화",
    tl_no_scope: "이 팀원으로 전환할 수 없어요(보기범위 미설정)",
    inbox_assign_ph: "팀원에게…",
    inbox_assign_done: "배정했어요",
    inbox_assign_fail: "배정 실패",
    claim_unassigned_done: "미배정 할일로 등록했어요",
    prio_label: "우선",
    prio_set: "⭐ 우선",
    prio_unset: "우선 해제",
    an_none: "최근 완료 없음",
    an_recent: "최근 30일 완료",
    an_done: "완료",
    an_bywt: "업무종류",
    an_untyped: "기타",
    an_recent_done: "최근 완료",
    qe_assign_ph: "담당 변경…",
    qe_title_hint: "할일 이름 — 메일 제목이 아니라 '무엇을 할지'로 고쳐 쓰세요",
    qe_title_save: "이름 저장",
    qe_title_save_hint: "할일 이름 저장",
    qe_title_saved: "이름 저장됨",
    qe_title_empty: "할일 이름을 입력하세요",
    qe_mail_head: "원본 메일 내용 (해석이 맞는지 확인)",
    qe_mail_loading: "불러오는 중…",
    qe_mail_body_empty: "본문이 저장되지 않은 메일입니다(제목·발신자만)",
    qe_mail_none: "메일을 불러오지 못했습니다",
    qe_project_ph: "과제 변경…",
    qe_project_hint: "과제가 잘못 분류됐으면 여기서 바꾸세요",
    qe_project_moved: "과제를 변경했습니다",
    qe_project_move_fail: "과제 변경 실패",
    mail_spam: "스팸",
    mail_spam_hint: "스팸/광고 메일 — 이 메일 숨김 또는 발신자 차단",
    mail_spam_title: "스팸/광고 메일 처리",
    mail_spam_block_sender: "이 발신자 차단(앞으로도)",
    mail_spam_hide_one: "이 메일만 숨기기",
    mail_spam_member_note: "발신자 영구 차단은 관리자만 — 이 메일만 숨깁니다",
    mail_spam_manage_hint: "차단 규칙 관리: 관리자 패널 › 메일 제외 규칙",
    mail_spam_blocked: "발신자 차단",
    mail_spam_hidden: "이 메일을 숨겼습니다",
    mail_spam_fail: "차단 실패",
    mail_body: "본문 발췌",
    mail_thread_count: "이 대화의 메일 수",
    thread_assign_ph: "이 대화 담당…",
    thread_assign_hint: "이 대화 전체를 한 사람에게 배정",
    thread_proj_ph: "이 대화 분류…",
    thread_proj_hint: "이 대화 전체를 다른 과제로 이동",
    thread_assign_done: "%n건 대화를 %who에게 배정",
    thread_proj_done: "%n건 대화를 %p로 분류",
    thread_op_fail: "대화 처리 실패",
    mail_recipients: "이 메일을 받은 팀원 수 (중복 메일 1건으로 합침)",
    mail_conv: "이 대화의 메일 수 (분류하면 대화 전체가 함께 처리됩니다)",
    mail_body_none: "본문 미수집 — 수집기가 본문을 넘기면 여기 표시됩니다. 지금 원문은 메일함(Hiworks 등)에서 확인하세요.",
    mail_details: "세부정보",
    my_memory: "내 메모리",
    my_memory_hint: "내 업무 메모리 — 할일 시작 시 AI에 주입됩니다",
    my_memory_desc: "내 업무 스타일·규칙·자주 쓰는 맥락 — 할일을 시작(Codex 대화)할 때 그 담당자 메모리로 자동 주입됩니다. 평가 아님.",
    my_memory_ph: "예: 메일 회신은 존댓말·간결하게. 보고서는 결론부터. 자주 쓰는 약어…",
    my_memory_saved: "메모리 저장됨",
    mem_items_title: "누적 메모리 항목",
    mem_items_hint: "완료 지식이 자동으로 쌓이고, 시작 시 관련 항목이 주입됩니다",
    mem_item_empty: "아직 누적된 항목이 없습니다. 일을 완료하면 지식이 항목으로 쌓입니다.",
    mem_item_del: "이 항목 보관(주입 제외)",
    mem_item_deleted: "항목 보관됨",
    mem_item_add: "+ 항목",
    mem_item_add_ph: "새 항목(규칙·맥락) 직접 추가…",
    mem_item_added: "항목 추가됨",
    mem_t_pref: "선호",
    mem_t_fact: "사실",
    mem_t_open: "진행중",
    mem_t_dec: "결정",
    prop_mem_add: "+ 메모리",
    prop_mem_add_hint: "메모리에 추가 — 다음 시작에 주입",
    prop_mem_added: "✓ 메모리",
    prop_mem_added_toast: "메모리에 추가됨 — 다음 시작에 주입",
    prop_mem_fail: "메모리 추가 실패",
    mail_next: "다음",
    assign_next: "편입하고 다음 ▶",
    assign_next_hint: "이 전갈을 편입하고 바로 다음 전갈로",
    mail_kbd_hint: "j/k 또는 ↑↓ 이동 · Enter 편입하고 다음",
    mrule_title: "전갈 차단 규칙",
    mrule_hint: "급여서신 등 사적 전갈·차단 발신자를 길드 기록에 안 받기",
    mrule_from: "발신자",
    mrule_subject: "제목",
    mrule_mailbox: "수신함",
    mrule_contains: "포함",
    mrule_equals: "완전일치",
    mrule_ph: "예: 급여명세서 / hr@회사.com",
    mrule_add: "규칙 추가",
    mrule_del: "삭제",
    mrule_empty: "규칙 없음 — 추가하면 해당 전갈은 수집돼도 기록에 안 들어옵니다",
    mrule_added: "규칙 추가됨",
    mrule_hidden_unit: "건 숨김",
    mrule_deleted: "규칙 삭제됨",
    mrule_fail: "추가 실패",
    mrule_need_pattern: "차단할 값을 입력하세요",
    rrule_title: "전갈 → 던전 배정 규칙",
    rrule_hint: "조건에 맞는 전갈을 던전으로 자동 배정",
    rrule_empty: "사용자 규칙 없음 — 추가하면 새로 오는 전갈이 그 던전으로 바로 들어갑니다",
    rrule_ph: "예: KVDS / lig.co.kr",
    rrule_need_project: "배정할 던전을 고르세요",
    rrule_apply: "기존 적용",
    rrule_apply_tip: "수신함의 기존 전갈에도 이 규칙 적용",
    rrule_apply_all: "모든 규칙 기존 전갈에 적용",
    rrule_apply_confirm: "수신함(미편입)의 기존 전갈에도 이 규칙을 지금 적용할까요?",
    rrule_apply_all_confirm: "모든 사용자 규칙을 수신함(미편입) 전체에 지금 적용할까요?",
    rrule_applied: "기존 적용",
    rrule_applied_all: "전체 적용",
    rrule_moved: "전갈",
    rrule_moved_unit: "건 이동",
    rrule_items_moved: "임무 동행",
    rrule_engine: "길드 자동 배정 규칙(정본)",
    rrule_engine_unit: "개 — 읽기 전용, 수정은 엔진 레인",
    rrule_engine_note: "정본: _workmeta/system/bindings/mail_project_router.yaml · 사용자 규칙이 이 표보다 우선 적용됩니다",
    rrule_col_id: "규칙",
    rrule_col_conf: "신뢰도",
    rrule_col_cond: "조건(요약)",
    rrule_body: "본문",
    rrule_conf_exact: "확정",
    rrule_conf_hint: "힌트(검토대기)",
    rrule_conf_amb: "애매(문의)",
    assign_done: "편입 완료",
    assign_fail: "편입 실패",
    assign_need_target: "편입할 던전을 고르세요",
    assign_made_short: "몬스터 출몰",
    assign_unit: "마리",
    master_del: "삭제",
    master_del_confirm: "삭제할까요? 되돌릴 수 없습니다.",
    master_deleted: "삭제됨",
    master_del_fail: "삭제 실패",
    master_edit: "수정",
    master_edited: "수정됨",
    master_edit_fail: "수정 실패",
    master_edit_name_ph: "이름",
    master_edit_title_ph: "제목",
    group_work: "전장",
    group_records: "기록 보관소",
    group_supply: "병참",
    group_knowledge: "도서관·공방",
    group_team: "길드",
    group_project: "던전",
    group_task: "몬스터",
    group_doc: "전리품·기록",
    group_comm: "전령",
    group_material: "병참",
    proj_provisional: "정션 미연결",
    proj_new_id_ph: "과제코드 (예: P26-099)",
    proj_new_title_ph: "과제명",
    proj_new_btn: "＋ 임시 과제",
    proj_edit: "수정",
    proj_archive: "보관",
    proj_unarchive: "복원",
    proj_edit_title_ph: "과제명 수정",
    proj_edit_need_title: "과제명을 입력하세요",
    proj_edited: "과제 수정됨",
    proj_edit_fail: "과제 수정 실패",
    proj_archive_confirm: "이 과제를 보관할까요? 목록에서 숨겨집니다(메일·할일 보존, 복원 가능).",
    proj_archived: "보관됨",
    proj_unarchived: "복원됨",
    proj_archive_inbox: "받은함은 보관할 수 없습니다",
    proj_archive_fail: "보관 실패",
    proj_archived_badge: "보관됨",
    proj_arch_show: "보관 보기",
    proj_arch_hide: "보관 숨기기",
    proj_new_hint: "정션 동기화 전까지 '정션 미연결'로 표시됩니다",
    proj_new_admin: "임시 과제 생성은 관리자만 가능합니다",
    proj_new_dup: "이미 있는 과제 코드입니다",
    proj_new_fmt: "코드 형식: 영문/숫자/-/_ (예 P26-099)",
    req_empty: "등록된 요청 없음",
    thr_recent: "최근 14일",
    thr_done: "건 처치",
    thr_peak: "최고",
    thr_day: "일",
    thr_none: "최근 처치 없음",
    col_title: "제목",
    col_assignee: "담당 유닛",
    cls_suggested: "제안",
    cls_work_type: "업무유형",
    cls_link_kind: "연결대상",
    cls_link_ref: "연결 대상(산출물/BOM/업체…)",
    cls_completion: "완료기준(무엇을 하면 닫히나)",
    cls_confirm: "정식 등록",
    cls_confirmed: "정식 등록됨",
    compose_title: "Outlook 메일 쓰기",
    compose_hint: "Outlook 작성창이 열립니다 — 검토 후 직접 발송",
    compose_to: "받는 사람 (이름 또는 메일주소)",
    compose_cc: "참조 (선택)",
    compose_subject: "제목",
    compose_body: "본문 (Codex 초안을 붙여넣으세요)",
    compose_open: "Outlook로 열기",
    compose_copy: "전체 복사",
    compose_copied: "복사됨 — Outlook에 붙여넣기",
    compose_copy_fail: "복사 실패",
    compose_too_long: "본문이 길어 잘릴 수 있어요 — '전체 복사' 후 붙여넣기 권장",
    codex_fa_warn: "이 대화에서 Codex가 로컬 프로그램 실행·파일 쓰기를 하게 됩니다(Outlook 등). 메일 내용에 의한 위험이 있으니 필요할 때만 켜고, 끝나면 끄세요. 켤까요?",
    codex_fa_on: "전체권한 켜짐 — 다음 메시지부터 적용",
    codex_fa_off: "전체권한 꺼짐",
    mine_qa_ph: "빠른 할 일 추가…",
    mine_qa_add: "추가",
    mine_qa_need: "할 일 내용을 입력하세요",
    mine_qa_need_proj: "과제를 고르세요",
    mine_qa_done: "할 일을 추가했어요",
    mine_qa_fail: "추가 실패",
    inbox_see_all: "전체 %n건 분류하러 가기 →",
    codex_fa_fail: "변경 실패",
    cls_none: "분류할 몬스터 없음",
    cls_need: "업무유형 + 연결대상(또는 단계)이 있어야 정식 등록됩니다",
    promote_need_project: "던전에 분류 후 몬스터로 소환",
    mail_reg_open: "＋ 전령 등록",
    mail_reg_subject: "제목",
    mail_reg_from: "상대(보낸/받는 사람)",
    req_no_project: "미연결",
    mail_reg_ptr: "원문 위치 포인터(Outlook/파일 경로)",
    mail_reg_body: "전령 본문",
    mail_reg_add: "등록",
    mail_reg_note: "전령 본문은 ERP 런타임 DB에 저장합니다. 원장·_workmeta에는 본문을 넣지 않습니다.",
    promote_already: "이미 몬스터로 소환된 전령입니다",
    promote_done: "몬스터로 소환됨",
    promote_done_next: "몬스터로 소환됨 — '분류 필요'에서 분류하세요",
    promote_done_go: "몬스터로 소환 — 분류로 이동",
    promote_go_triage: "분류하러 가기 →",
    mail_reg_need_subject: "제목을 입력하세요",
    mail_reg_done: "전령이 등록되었습니다",
    mail_reg_fail: "전령 등록에 실패했습니다",
    copied: "복사됨",
    copy_unsupported: "이 브라우저에서 복사가 지원되지 않습니다",
    risk_overdue: "지남",
    hub_triage_pre: "이 던전에 분류 필요 몬스터",
    hub_triage_post: "건 — 업무 관리 › 내 할 일 › 분류 필요에서 처리",
    col_stage: "스테이지",
    col_link: "유형·연결",
    col_status: "상태",
    ct_role: "역할",
    hub_no_contacts: "연결된 연락처 없음",
    gate_reason: "사유",
    gate_blocked: "차단",
    hub_no_gates: "단계 없음",
    col_date: "일자",
    mt_actions: "액션",
    hub_no_meetings: "회의 없음",
    bom_parts: "부품·BOM",
    col_part: "부품",
    col_type: "유형",
    col_onhand: "재고",
    bom_purchase: "구매·발주",
    col_item: "품목",
    hub_no_bom: "자재·BOM 없음",
    risk_score: "위험도",
    hub_no_risk: "위험 항목 없음",
    req_note: "산출물별 필수 입력(요구사항) 충족 현황.",
    req_scope: "산출물",
    req_need: "필요",
    req_have: "충족",
    req_partial: "미충족",
    hub_no_req: "요구사항(입력 규칙) 없음",
    gate_admin_only: "게이트 모드는 관리자만 변경할 수 있습니다",
    gate_force_reason: "강제 통과 사유를 입력하세요 (기록에 남습니다)",
    req_promote: "몬스터로",
    req_need_project: "과제 연결 필요",
    req_title_ph: "개발 요청 내용",
    req_requester_ph: "요청자",
    req_category_ph: "분류",
    req_cat_requirement: "요구사항",
    req_cat_feature: "기능 아이디어",
    req_cat_improve: "개선",
    req_cat_bug: "버그",
    req_cat_etc: "기타",
    req_add: "요청 등록",
    req_intake_note: "팀원 인입함 — 개발 요청·요구사항·업데이트하면 좋은 기능 아이디어·개선·버그를 자유롭게 적습니다(분류로 구분). 그대로 목록에 쌓이고, 과제에 연결해 '할 일로' 승격하면 분류 필요로 들어가 SE 기준점(단계·산출물·업무유형)에 거는 분류를 거칩니다.",
    req_col_title: "요청",
    req_col_who: "요청자",
    req_col_cat: "분류",
    status_archived: "봉인고",
    status_unassigned: "주인 없음",
    act_restore: "되살리기",
    act_restore_failed: "되살리기 실패",
    item_delete_reason: "봉인 사유 — 비워도 됩니다. 연대기에 남습니다. (취소하려면 Esc)",
    archived_note: "봉인된 몬스터입니다. '되살리기'를 누르면 활성 목록으로 돌아갑니다. 이력은 연대기에 그대로 남습니다.",
    nav_audit: "대연대기(전체 기록)",
    al_kind: "종류",
    al_actor: "행위자",
    al_desc: "설명",
    al_d7: "최근 7일",
    al_d30: "최근 30일",
    al_d90: "최근 90일",
    al_all: "전체 기간",
    al_noise: "조회·잡음 포함",
    al_more: "최근 300건만 — 필터로 좁혀보세요",
    widget_preset: "진형 불러오기",
    widget_my_saved: "내 저장 진형",
    widget_save_mine: "진형 저장",
    widget_saved_ok: "현재 진형을 저장했습니다.",
    widget_preset_group: "기본 진형",
    widget_del_slot: "선택한 저장 진형 삭제",
    widget_save_name: "저장할 진형 이름",
    widget_del_pick: "삭제할 저장 진형을 드롭다운에서 먼저 고르세요",
    widget_del_confirm: "이 저장 진형을 삭제할까요?"
  }
};

export function getLexicon(mode = "business") {
  return LEXICON[mode] ?? LEXICON.business;
}
