#!/usr/bin/env node

import { promises as fs } from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import YAML from "yaml";
import { pathExists } from "../shared/io.mjs";

const __filename = fileURLToPath(import.meta.url);

export const MORNING_REPORT_VERSION = "soulforge.morning_project_report.v0";

const CORE_NIGHTLY_CHECKS = [
  "ui:validate",
  "ui:lint:all",
  "ui:docs:check",
  "ui:build",
  "ui:done:check",
];
const CONDITIONAL_CHECKS = ["ui:smoke:theme-pack"];
const ACTIVE_STATUSES = new Set(["active", "held", "started", "in_progress", "ready", "running"]);
const BLOCKED_STATUSES = new Set(["blocked", "failed"]);
const COMPLETED_STATUSES = new Set(["completed", "done", "closed"]);
const SAFE_PATH_SEGMENT_PATTERN = /^[A-Za-z0-9][A-Za-z0-9_.-]*$/u;
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/u;
const SECRET_TEXT_PATTERNS = [
  /-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/iu,
  /\bBearer\s+[A-Za-z0-9._~+/=-]{12,}/iu,
  /\b(token|password|passwd|secret|cookie|session|authorization)\s*[:=]\s*["']?[^"',\s)]+/iu,
  /<!doctype html|<html[\s>]|<body[\s>]|<\/body>|<\/html>/iu,
];
const UNSAFE_SOURCE_REF_PATTERNS = [
  /^https?:\/\//iu,
  /^file:\/\//iu,
  /[?&](token|signature|expires|X-Amz-Signature)=/iu,
];

export async function buildMorningReport(options = {}) {
  const repoRoot = path.resolve(options.repoRoot ?? process.cwd());
  const workmetaRoot = path.resolve(options.workmetaRoot ?? path.join(repoRoot, "_workmeta"));
  const projectCode = validateProjectCode(options.projectCode ?? options.project_code);
  const generatedAt = options.generatedAt instanceof Date ? options.generatedAt : new Date();
  const reportDate = normalizeDate(options.date ?? localDateFromDate(generatedAt));
  const generatedBy = sanitizeReportText(options.generatedBy ?? options.generated_by ?? "nightly_sweep_v0", "generated_by", 80);
  const missionBundle = options.missions
    ? buildProvidedMissionBundle(options.missions)
    : await readProjectMissions({ repoRoot, workmetaRoot, projectCode });
  const missions = missionBundle.missions;
  const battleLedger = options.battleLedger ?? (await readBattleLedger({ workmetaRoot, projectCode, date: reportDate }));
  const checks = normalizeChecks(options.checks ?? buildDefaultChecks(battleLedger));
  const summary = summarizeReport({ missions, battleLedger, checks });
  const topActions = normalizeActionList(options.topActions ?? deriveTopActions({ missions, battleLedger, checks }));

  return {
    schema_version: MORNING_REPORT_VERSION,
    report_date: reportDate,
    project_code: projectCode,
    generated_at: generatedAt.toISOString(),
    generated_by: generatedBy,
    source_refs: {
      ...missionBundle.source_refs,
      battle_log_daily: battleLedger.daily_path ? relativeLocalPath(workmetaRoot, battleLedger.daily_path) : null,
      battle_log_latest: battleLedger.latest_path ? relativeLocalPath(workmetaRoot, battleLedger.latest_path) : null,
    },
    summary,
    missions,
    checks,
    battle_ledger: battleLedger,
    top_actions: topActions,
    notes: [
      "Local-only briefing. It does not promote canon, approve readiness, or replace owner review.",
      "Raw run truth, mail bodies, attachments, and secret-bearing payloads are not copied into this report.",
      "v0 red flags are derived from current project-local inputs; prior-day delta comparison is not computed yet.",
      "Top-level typecheck/test contract is not locked yet; UI bundle checks are shown as the nightly code-health surface.",
    ],
  };
}

export function renderMorningReportMarkdown(report) {
  const missionRows = report.missions.map((mission) => [
    mission.mission_id,
    mission.current_status,
    mission.blocker_kind,
    mission.mission_level_hint,
    mission.promotion_review_needed ? "yes" : "no",
  ]);
  const checkRows = report.checks.map((check) => [
    check.name,
    check.result,
    check.check_bucket,
    check.short_note,
  ]);
  const battleRows = report.battle_ledger.events.map((event) => [
    event.time,
    event.mission_id,
    event.stage,
    event.result,
    event.intervention_count,
    event.next_action_note,
  ]);

  const lines = [
    `# Morning Project Report - ${report.project_code} - ${report.report_date}`,
    "",
    `- Schema: \`${report.schema_version}\``,
    `- Report date: \`${report.report_date}\``,
    `- Project: \`${report.project_code}\``,
    `- Generated by: \`${report.generated_by}\``,
    `- Generated at: \`${report.generated_at}\``,
    "",
    "## Executive Snapshot",
    "",
    `- Active missions: ${report.summary.active_mission_count}`,
    `- Blocked missions: ${report.summary.blocked_mission_count}`,
    `- Completed missions: ${report.summary.completed_mission_count}`,
    `- New red flags: ${report.summary.red_flag_count}`,
    "",
    "Today first look:",
    ...renderBulletList(report.top_actions),
    "",
    "## Mission Review Needed",
    "",
    ...renderTable(
      ["Mission", "Status", "Blocker kind", "Mission level hint", "Promotion review"],
      missionRows.filter((row) => row[1] === "blocked" || row[1] === "failed" || row[4] === "yes"),
      "_No mission review items were derived._",
    ),
    "",
    "## Code Health",
    "",
    ...renderTable(["Check", "Result", "Bucket", "Note"], checkRows, "_No code-health checks were projected._"),
    "",
    "## Boundary And Docs Health",
    "",
    `- Workspace sample boundary: \`${report.summary.workspace_boundary_status}\``,
    `- Owner boundary drift: \`${report.summary.owner_boundary_status}\``,
    `- Broken docs links: \`${report.summary.docs_link_status}\``,
    `- Contract mismatch: \`${report.summary.contract_status}\``,
    "",
    "## Battle Ledger",
    "",
    `- Daily events: ${report.battle_ledger.daily_event_count}`,
    `- Results: ${formatCountObject(report.battle_ledger.result_counts)}`,
    `- Bottlenecks: ${formatCountObject(report.battle_ledger.bottleneck_counts)}`,
    "",
    ...renderTable(
      ["Time", "Mission", "Stage", "Result", "Interventions", "Next action"],
      battleRows,
      "_No battle events were found for this report date._",
    ),
    "",
    "## Promotion Review Hints",
    "",
    ...renderBulletList(report.missions.map((mission) => {
      const review = mission.promotion_review_needed ? "review needed" : "no immediate review";
      return `\`${mission.mission_id}\`: \`${mission.mission_level_hint}\`, ${review}.`;
    })),
    "",
    "## Today Actions",
    "",
    ...renderBulletList(report.top_actions),
    "",
    "## Source Refs",
    "",
    `- Mission source: \`${report.source_refs.mission_source_type ?? "public_mission_index"}\``,
    `- Mission index: \`${report.source_refs.mission_index ?? "not_used"}\``,
    `- Mission root: \`${report.source_refs.mission_root ?? "not_recorded"}\``,
    `- Mission surfaces: \`${formatSourceRefList(report.source_refs.mission_surfaces)}\``,
    `- Battle daily: \`${report.source_refs.battle_log_daily ?? "not_found"}\``,
    `- Battle latest: \`${report.source_refs.battle_log_latest ?? "not_found"}\``,
    "",
    "## Notes",
    "",
    ...renderBulletList(report.notes),
  ];

  return `${lines.join("\n").replace(/\s+$/u, "")}\n`;
}

export async function writeMorningReport(options = {}) {
  const repoRoot = path.resolve(options.repoRoot ?? process.cwd());
  const workmetaRoot = path.resolve(options.workmetaRoot ?? path.join(repoRoot, "_workmeta"));
  const report = await buildMorningReport({ ...options, repoRoot, workmetaRoot });
  const outputRoot = path.join(workmetaRoot, report.project_code, "reports", "morning_report");
  const dailyPath = path.join(outputRoot, `${report.report_date}.md`);
  const latestPath = path.join(outputRoot, "latest.md");
  const markdown = renderMorningReportMarkdown(report);

  await fs.mkdir(outputRoot, { recursive: true });
  await fs.writeFile(dailyPath, markdown, "utf8");
  await fs.writeFile(latestPath, markdown, "utf8");

  return {
    report,
    daily_path: dailyPath,
    latest_path: latestPath,
  };
}

function buildProvidedMissionBundle(missions) {
  const normalizedMissions = Array.isArray(missions) ? missions : [];
  return {
    missions: normalizedMissions,
    source_refs: {
      mission_source_type: "provided",
      mission_index: null,
      mission_root: "provided",
      mission_surfaces: normalizedMissions.map((mission) => `provided/${validateMissionId(mission.mission_id)}/`),
    },
  };
}

async function readProjectMissions({ repoRoot, workmetaRoot, projectCode }) {
  const privateMissionBundle = await readPrivateProjectMissions({ workmetaRoot, projectCode });
  if (privateMissionBundle) {
    return privateMissionBundle;
  }

  return readPublicProjectMissions({ repoRoot, projectCode });
}

async function readPrivateProjectMissions({ workmetaRoot, projectCode }) {
  const missionRoot = path.join(workmetaRoot, projectCode, "missions");
  if (!(await pathExists(missionRoot))) {
    return null;
  }

  const entries = await fs.readdir(missionRoot, { withFileTypes: true });
  const missions = [];

  for (const entry of entries.filter((item) => item.isDirectory()).sort((left, right) => left.name.localeCompare(right.name))) {
    const missionId = validateMissionId(entry.name);
    const missionSurfacePath = path.join(missionRoot, missionId, "mission.yaml");
    const readinessSurfacePath = path.join(missionRoot, missionId, "readiness.yaml");
    const hasMissionSurface = await pathExists(missionSurfacePath);
    const hasReadinessSurface = await pathExists(readinessSurfacePath);
    if (!hasMissionSurface && !hasReadinessSurface) {
      continue;
    }

    const missionSurface = hasMissionSurface ? await readPrivateYamlFile(missionSurfacePath, "private_mission_surface") : {};
    const readinessSurface = hasReadinessSurface ? await readPrivateYamlFile(readinessSurfacePath, "private_readiness_surface") : {};
    const declaredMissionId = missionSurface?.mission_id ?? readinessSurface?.mission_id ?? missionId;
    if (validateMissionId(declaredMissionId) !== missionId) {
      throw new Error("private_mission_id_mismatch");
    }
    if (missionSurface?.project_code !== undefined && validateProjectCode(missionSurface.project_code) !== projectCode) {
      throw new Error("private_mission_project_code_mismatch");
    }

    missions.push(normalizeMissionRecord({
      missionId,
      entry: { mission_id: missionId, project_code: projectCode },
      missionSurface,
      readinessSurface,
    }));
  }

  return {
    missions,
    source_refs: {
      mission_source_type: "private_workmeta",
      mission_index: null,
      mission_root: `_workmeta/${projectCode}/missions/`,
      mission_surfaces: missions.map((mission) => `_workmeta/${projectCode}/missions/${mission.mission_id}/`),
    },
  };
}

async function readPublicProjectMissions({ repoRoot, projectCode }) {
  const indexPath = path.join(repoRoot, ".mission", "index.yaml");
  if (!(await pathExists(indexPath))) {
    return {
      missions: [],
      source_refs: {
        mission_source_type: "public_mission_index",
        mission_index: ".mission/index.yaml",
        mission_root: ".mission/",
        mission_surfaces: [],
      },
    };
  }

  const index = await readYamlFile(indexPath);
  const entries = Array.isArray(index?.entries) ? index.entries : [];
  const missions = [];

  for (const entry of entries.filter((item) => item?.project_code === projectCode)) {
    const missionId = validateMissionId(entry.mission_id);
    const missionRoot = path.join(repoRoot, ".mission", missionId);
    const missionSurface = await readOptionalYaml(path.join(missionRoot, "mission.yaml"));
    const readinessSurface = await readOptionalYaml(path.join(missionRoot, "readiness.yaml"));
    missions.push(normalizeMissionRecord({ missionId, entry, missionSurface, readinessSurface }));
  }

  return {
    missions,
    source_refs: {
      mission_source_type: "public_mission_index",
      mission_index: ".mission/index.yaml",
      mission_root: ".mission/",
      mission_surfaces: missions.map((mission) => `.mission/${mission.mission_id}/`),
    },
  };
}

function normalizeMissionRecord({ missionId, entry, missionSurface, readinessSurface }) {
  const currentStatus = sanitizeStatus(readinessSurface?.status ?? entry.readiness_status ?? missionSurface?.status ?? entry.status);
  const blockers = normalizeStringList(readinessSurface?.blockers, "blocker", 180);

  return {
    mission_id: missionId,
    title: sanitizeReportText(entry.title ?? missionSurface?.title ?? missionId, "mission_title", 160),
    current_status: currentStatus,
    mission_status: sanitizeStatus(missionSurface?.status ?? entry.status),
    readiness_status: sanitizeStatus(readinessSurface?.status ?? entry.readiness_status),
    blocker_kind: deriveBlockerKind({ currentStatus, blockers, readinessSurface, entry, missionSurface }),
    blocker_count: blockers.length,
    mission_level_hint: deriveMissionLevelHint({ currentStatus, entry, missionSurface }),
    promotion_review_needed: needsPromotionReview({ currentStatus, blockers, readinessSurface, entry, missionSurface }),
  };
}

async function readBattleLedger({ workmetaRoot, projectCode, date }) {
  const logRoot = path.join(workmetaRoot, projectCode, "log", "battle_log");
  const dailyPath = await firstExistingPath([
    path.join(logRoot, "daily", `${date}.md`),
    path.join(logRoot, `${date}.md`),
  ]);
  const latestPath = await firstExistingPath([path.join(logRoot, "latest.md")]);
  const dailyMarkdown = dailyPath ? await fs.readFile(dailyPath, "utf8") : "";
  const latestMarkdown = latestPath ? await fs.readFile(latestPath, "utf8") : "";
  const dailyEvents = parseBattleLogEvents(dailyMarkdown);

  assertBodySafe(dailyMarkdown, "battle_log_daily");
  assertBodySafe(latestMarkdown, "battle_log_latest");

  return {
    daily_path: dailyPath,
    latest_path: latestPath,
    daily_event_count: parseCountLine(dailyMarkdown, "Event count") ?? dailyEvents.length,
    latest_event_count: parseCountLine(latestMarkdown, "Event count") ?? parseBattleLogEvents(latestMarkdown).length,
    result_counts: parseCountMapLine(dailyMarkdown, "Results"),
    bottleneck_counts: parseCountMapLine(dailyMarkdown, "Bottlenecks"),
    events: dailyEvents,
  };
}

function parseBattleLogEvents(markdown) {
  const rows = [];
  for (const line of String(markdown ?? "").split(/\r?\n/u)) {
    if (!line.startsWith("| ")) {
      continue;
    }
    if (/^\| ---/u.test(line) || /^\| Time \|/u.test(line)) {
      continue;
    }
    const cells = line.slice(2, -2).split(" | ").map((cell) => sanitizeReportText(cell.replace(/\\\|/gu, "|"), "battle_log_cell", 220));
    if (cells.length < 9) {
      continue;
    }
    const sourceRef = cells[7].split(":").slice(1).join(":");
    if (UNSAFE_SOURCE_REF_PATTERNS.some((pattern) => pattern.test(sourceRef))) {
      throw new Error("unsafe_morning_report_source_ref");
    }
    rows.push({
      time: cells[0],
      mission_id: cells[1],
      stage: cells[2],
      result: sanitizeStatus(cells[5]),
      intervention_count: normalizeCount(cells[6]),
      next_action_note: cells[8],
    });
  }
  return rows;
}

function buildDefaultChecks(battleLedger) {
  const checks = CORE_NIGHTLY_CHECKS.map((name) => ({
    name,
    result: "not_recorded",
    short_note: "No nightly check result was found in the project-local morning report inputs.",
    check_bucket: "core_nightly",
  }));
  checks.push({
    name: CONDITIONAL_CHECKS[0],
    result: "not_recorded",
    short_note: "Conditional smoke check is reported separately when a local run surface is available.",
    check_bucket: "conditional",
  });
  checks.push({
    name: "top-level typecheck/test",
    result: "advisory",
    short_note: "Top-level typecheck/test contract is not locked yet.",
    check_bucket: "advisory",
  });

  if (Object.keys(battleLedger.bottleneck_counts).some((key) => key === "tool_or_validation_failure")) {
    checks.push({
      name: "dependency/runtime risk",
      result: "attention",
      short_note: "Battle ledger includes tool_or_validation_failure bottleneck signals.",
      check_bucket: "advisory",
    });
  }

  return checks;
}

function summarizeReport({ missions, battleLedger, checks }) {
  const blockedBattleEvents = battleLedger.events.filter((event) => BLOCKED_STATUSES.has(event.result)).length;
  const attentionChecks = checks.filter((check) => ["failed", "blocked", "attention"].includes(check.result)).length;
  const blockedMissions = missions.filter((mission) => BLOCKED_STATUSES.has(mission.current_status)).length;

  return {
    active_mission_count: missions.filter((mission) => ACTIVE_STATUSES.has(mission.current_status)).length,
    blocked_mission_count: blockedMissions,
    completed_mission_count: missions.filter((mission) => COMPLETED_STATUSES.has(mission.current_status)).length,
    failed_mission_count: missions.filter((mission) => mission.current_status === "failed").length,
    red_flag_count: blockedMissions + blockedBattleEvents + attentionChecks,
    workspace_boundary_status: "not_recorded",
    owner_boundary_status: "not_recorded",
    docs_link_status: "not_recorded",
    contract_status: "not_recorded",
  };
}

function deriveTopActions({ missions, battleLedger, checks }) {
  const actions = [];
  for (const mission of missions.filter((item) => BLOCKED_STATUSES.has(item.current_status)).slice(0, 3)) {
    actions.push(`Review blocked mission \`${mission.mission_id}\` (${mission.blocker_kind}).`);
  }
  for (const event of battleLedger.events.filter((item) => BLOCKED_STATUSES.has(item.result)).slice(0, 2)) {
    actions.push(`Review battle result \`${event.result}\` for \`${event.mission_id}\`: ${event.next_action_note || "no next action note recorded"}.`);
  }
  for (const check of checks.filter((item) => ["failed", "blocked", "attention"].includes(item.result)).slice(0, 2)) {
    actions.push(`Review code-health signal \`${check.name}\`: ${check.short_note}`);
  }
  if (actions.length === 0) {
    actions.push("No immediate owner action was derived from the project-local inputs.");
  }
  return actions.slice(0, 5);
}

function deriveBlockerKind({ currentStatus, blockers, readinessSurface, entry, missionSurface }) {
  if (!BLOCKED_STATUSES.has(currentStatus)) {
    return "none";
  }
  if (blockers.some((blocker) => /workflow_id|workflow/i.test(blocker)) || entry?.workflow_id === null || missionSurface?.workflow_id === null) {
    return "missing_owner_boundary";
  }
  if (blockers.some((blocker) => /human|confirm|approval|owner/i.test(blocker))) {
    return "human_confirmation_required";
  }
  const checks = readinessSurface?.checks && typeof readinessSurface.checks === "object" ? readinessSurface.checks : {};
  if (Object.values(checks).some((value) => String(value).trim() === "missing")) {
    return "missing_acceptance_check";
  }
  return "quality_review_needed";
}

function deriveMissionLevelHint({ currentStatus, entry, missionSurface }) {
  if (missionSurface?.mission_level) {
    return sanitizeReportText(missionSurface.mission_level, "mission_level", 80);
  }
  if (entry?.mission_level) {
    return sanitizeReportText(entry.mission_level, "mission_level", 80);
  }
  if (COMPLETED_STATUSES.has(currentStatus)) {
    return "completed_sample";
  }
  if (BLOCKED_STATUSES.has(currentStatus)) {
    return "blocked_sample_or_current_default_review";
  }
  if (ACTIVE_STATUSES.has(currentStatus)) {
    return "active_current";
  }
  return "sample_review_pending";
}

function needsPromotionReview({ currentStatus, blockers, readinessSurface, entry, missionSurface }) {
  if (readinessSurface?.promotion_review_needed !== undefined) {
    return Boolean(readinessSurface.promotion_review_needed);
  }
  if (entry?.promotion_review_needed !== undefined) {
    return Boolean(entry.promotion_review_needed);
  }
  if (missionSurface?.promotion_review_needed !== undefined) {
    return Boolean(missionSurface.promotion_review_needed);
  }
  return BLOCKED_STATUSES.has(currentStatus) || blockers.length > 0;
}

function normalizeChecks(checks) {
  if (!Array.isArray(checks)) {
    return [];
  }
  return checks.map((check) => ({
    name: sanitizeReportText(check.name, "check_name", 120),
    result: sanitizeStatus(check.result ?? "not_recorded"),
    short_note: sanitizeReportText(check.short_note ?? check.note ?? "", "check_note", 220),
    check_bucket: sanitizeReportText(check.check_bucket ?? "advisory", "check_bucket", 40),
  }));
}

function normalizeActionList(actions) {
  if (!Array.isArray(actions)) {
    return [];
  }
  return actions.map((action) => sanitizeReportText(action, "top_action", 260)).filter(Boolean).slice(0, 8);
}

function normalizeStringList(value, field, maxLength) {
  if (!Array.isArray(value)) {
    return [];
  }
  return value.map((item) => sanitizeReportText(item, field, maxLength)).filter(Boolean);
}

async function readYamlFile(filePath) {
  return YAML.parse(await fs.readFile(filePath, "utf8")) ?? {};
}

async function readPrivateYamlFile(filePath, field) {
  const text = await fs.readFile(filePath, "utf8");
  assertBodySafe(text, field);
  return YAML.parse(text) ?? {};
}

async function readOptionalYaml(filePath) {
  if (!(await pathExists(filePath))) {
    return {};
  }
  return readYamlFile(filePath);
}

async function firstExistingPath(filePaths) {
  for (const filePath of filePaths) {
    if (await pathExists(filePath)) {
      return filePath;
    }
  }
  return null;
}

function parseCountLine(markdown, label) {
  const match = String(markdown ?? "").match(new RegExp(`^- ${escapeRegExp(label)}: (\\d+)`, "mu"));
  return match ? Number.parseInt(match[1], 10) : null;
}

function parseCountMapLine(markdown, label) {
  const match = String(markdown ?? "").match(new RegExp(`^- ${escapeRegExp(label)}: (.+)$`, "mu"));
  if (!match || match[1] === "none") {
    return {};
  }
  const counts = {};
  for (const part of match[1].split(",")) {
    const [key, value] = part.trim().split("=");
    const count = Number.parseInt(value, 10);
    if (key && Number.isInteger(count)) {
      counts[sanitizeReportText(key, "count_key", 80)] = count;
    }
  }
  return counts;
}

function validateProjectCode(value) {
  const text = sanitizeReportText(value, "project_code", 120);
  if (!SAFE_PATH_SEGMENT_PATTERN.test(text)) {
    throw new Error("invalid_project_code");
  }
  return text;
}

function validateMissionId(value) {
  const text = sanitizeReportText(value, "mission_id", 180);
  if (!SAFE_PATH_SEGMENT_PATTERN.test(text)) {
    throw new Error("invalid_mission_id");
  }
  return text;
}

function normalizeDate(value) {
  const text = String(value ?? "").trim();
  if (!DATE_PATTERN.test(text) || Number.isNaN(Date.parse(`${text}T00:00:00Z`))) {
    throw new Error("invalid_morning_report_date");
  }
  return text;
}

function sanitizeStatus(value) {
  return sanitizeReportText(value ?? "unknown", "status", 80).toLowerCase();
}

function sanitizeReportText(value, field, maxLength) {
  const text = String(value ?? "").replace(/\s+/gu, " ").trim();
  if (!text) {
    return "";
  }
  if (SECRET_TEXT_PATTERNS.some((pattern) => pattern.test(text))) {
    throw new Error(`unsafe_morning_report_text: ${field}`);
  }
  return text.length > maxLength ? `${text.slice(0, maxLength - 15)}... [truncated]` : text;
}

function assertBodySafe(text, field) {
  if (SECRET_TEXT_PATTERNS.some((pattern) => pattern.test(String(text ?? "")))) {
    throw new Error(`unsafe_morning_report_text: ${field}`);
  }
}

function normalizeCount(value) {
  const parsed = Number.parseInt(String(value ?? "0"), 10);
  return Number.isInteger(parsed) && parsed >= 0 ? parsed : 0;
}

function renderTable(headers, rows, emptyText) {
  if (!rows || rows.length === 0) {
    return [emptyText];
  }
  const header = `| ${headers.join(" | ")} |`;
  const separator = `| ${headers.map(() => "---").join(" | ")} |`;
  return [
    header,
    separator,
    ...rows.map((row) => `| ${row.map(escapeMarkdownCell).join(" | ")} |`),
  ];
}

function renderBulletList(items) {
  if (!items || items.length === 0) {
    return ["- None."];
  }
  return items.map((item) => `- ${item}`);
}

function escapeMarkdownCell(value) {
  return String(value ?? "").replace(/\|/gu, "\\|").replace(/\r?\n/gu, " ").trim();
}

function formatCountObject(value) {
  const entries = Object.entries(value ?? {});
  return entries.length === 0 ? "none" : entries.map(([key, count]) => `${key}=${count}`).join(", ");
}

function formatSourceRefList(value) {
  return Array.isArray(value) && value.length > 0 ? value.join(", ") : "not_found";
}

function relativeLocalPath(workmetaRoot, filePath) {
  return path.join("_workmeta", path.relative(path.resolve(workmetaRoot), path.resolve(filePath))).split(path.sep).join("/");
}

function localDateFromDate(value) {
  const year = value.getFullYear();
  const month = String(value.getMonth() + 1).padStart(2, "0");
  const day = String(value.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function escapeRegExp(value) {
  return String(value).replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

function parseArgs(argv) {
  const args = {};

  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (!token.startsWith("--")) {
      continue;
    }
    const raw = token.slice(2);
    const separatorIndex = raw.indexOf("=");
    const key = separatorIndex === -1 ? raw : raw.slice(0, separatorIndex);
    const inlineValue = separatorIndex === -1 ? undefined : raw.slice(separatorIndex + 1);
    const next = argv[index + 1];
    const value = inlineValue ?? (next && !next.startsWith("--") ? next : true);

    if (inlineValue === undefined && value === next) {
      index += 1;
    }
    args[key] = value;
  }

  return args;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const repoRoot = path.resolve(args["repo-root"] ?? process.cwd());
  const workmetaRoot = path.resolve(args["workmeta-root"] ?? path.join(repoRoot, "_workmeta"));
  const result = await writeMorningReport({
    repoRoot,
    workmetaRoot,
    projectCode: args["project-code"] ?? args.project_code,
    date: args.date,
    generatedBy: args["generated-by"],
  });

  if (args.json === true || args.json === "true") {
    process.stdout.write(`${JSON.stringify({ status: "written", ...result }, null, 2)}\n`);
    return;
  }

  process.stdout.write([
    "morning report written",
    `daily: ${result.daily_path}`,
    `latest: ${result.latest_path}`,
    `red_flags: ${result.report.summary.red_flag_count}`,
  ].join("\n"));
  process.stdout.write("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
  main().catch((error) => {
    process.stderr.write(`${error.stack ?? error.message}\n`);
    process.exitCode = 1;
  });
}
