import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,ChevronDown,ChevronRight,FileText,FolderOpen,RefreshCw,Search,X} from 'lucide-react';
import {buildClaudeQuotaPresentation,selectCodexRateLimitObservation} from './core/provider-limits.mjs';
import {antigravityQuotaRows} from './core/antigravity-quota.mjs';
import './operations-workspace.css';

type Row=Record<string,any>;
export const when=(v:any)=>v&&Number.isFinite(Date.parse(v))?new Date(v).toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'미확인';
const size=(v:any)=>typeof v==='number'?v<1024?`${v} B`:`${(v/1024).toLocaleString('ko-KR',{maximumFractionDigits:1})} KB`:'—';
export async function localRead(url:string){const r=await fetch(url,{credentials:'omit',cache:'no-store',redirect:'error',signal:AbortSignal.timeout(45000)});if(!r.ok||!r.headers.get('content-type')?.includes('application/json'))throw Error('read');return r.json();}
const route=(kind:string,args:Row)=>`/operations-${kind}.json?${new URLSearchParams(args)}`;

export function Allowance({inputs,failed=[]}:{inputs:Row;failed?:string[]}){
  const limits=inputs.limits,codex=limits?.codex,claude=buildClaudeQuotaPresentation(limits),now=Date.now();
  const fresh=(at:any)=>Number.isFinite(Date.parse(at))&&now-Date.parse(at)>=0&&now-Date.parse(at)<10*60000;
  const rows:Row[]=['primary','secondary'].map(key=>{const live=codex?.[key]?{...codex[key],observed_at:codex.observed_at}:null,meter=inputs.usage?.history?.rate_limit;const candidate=meter?.window_minutes===(live?.window_minutes??(key==='primary'?300:10080))?meter:null;const w=selectCodexRateLimitObservation({meter:failed.includes('usage')?null:candidate,live:failed.includes('limits')?null:live}),reset=w?.resets_at_epoch_s?new Date(w.resets_at_epoch_s*1000).toISOString():null;return {id:`codex-${key}`,provider:'Codex',window:w?.window_minutes===300?'5시간':w?.window_minutes===10080?'주간':w?.window_minutes?`${w.window_minutes}분`:key==='primary'?'단기 창':'장기 창',remaining:typeof w?.used_percent==='number'&&w.used_percent>=0&&w.used_percent<=100?100-w.used_percent:null,reset,at:w?.observed_at,current:fresh(w?.observed_at)&&Date.parse(reset??'')>now};});
  for(const [key,label] of [['five_hour','5시간'],['seven_day','주간']]){const w=(claude.claude as Row)[key];rows.push({id:`claude-${key}`,provider:'Claude',window:label,remaining:typeof w?.utilization==='number'?100-w.utilization:null,reset:w?.resets_at,at:claude.claude.observed_at,current:!failed.includes('limits')&&claude.current&&fresh(claude.claude.observed_at)&&Date.parse(w?.resets_at)>now});}
  for(const [i,r] of antigravityQuotaRows(inputs.agQuota?.snapshot??inputs.agQuota).entries())rows.push({id:`ag-${i}`,provider:r.provider,window:r.window,remaining:r.remaining_percent,reset:r.resets_at,at:r.observed_at,current:!failed.includes('agQuota')&&r.freshness==='current'&&fresh(r.observed_at)&&Date.parse(r.resets_at??'')>now});
  return <section className="cx-card ow-allowance"><header className="cx-section-heading"><div><h2>얼마나 더 사용할 수 있나요?</h2><p>계정별 남은 사용 한도 · 사용한 토큰 합계와 별도입니다.</p></div></header><div className="ow-quota-grid">{rows.slice(0,4).map(r=><div className="ow-quota" key={r.id}><span>{r.provider} <small>{r.window}</small></span><strong>{r.current&&r.remaining!==null?`${Math.round(r.remaining)}%`:'미확인'}<small>남음</small></strong><div className="ow-meter" aria-label={`${r.provider} ${r.window} ${r.current?r.remaining+'% 남음':'현재 한도 미확인'}`}><span style={{width:r.current?`${r.remaining??0}%`:'0%'}}/></div><p>{r.current?'초기화':'마지막 초기화 예정'} {when(r.reset)}</p><small>{r.current?'관측':'이전 관측'} {when(r.at)}{!r.current&&r.remaining!==null?` · 당시 ${Math.round(r.remaining)}% 남음`:''}</small></div>)}</div>{rows.length>4&&<details className="ow-secondary-quota"><summary>Antigravity · {rows.length-4}개 한도 창 보기</summary>{rows.slice(4).map(r=><p key={r.id}><strong>{r.provider} {r.window}</strong> · {r.current?`${r.remaining}% 남음`:`현재 미확인 · 당시 ${r.remaining??'미확인'}%`} · 초기화 {when(r.reset)} · 관측 {when(r.at)}</p>)}</details>}<p className="cx-footnote">새 관측이 없거나 초기화 예정 시각이 지난 값은 현재 잔량으로 표시하지 않습니다. 남은 토큰 개수는 제공자에서 제공하지 않습니다.</p></section>;
}

export function WorkAndArrivals({inputs,failed,go}:{inputs:Row;failed:string[];go:(n:any)=>void}){
  const runtime=inputs.runtime,bots:Row[]=runtime?.bots??[],threads:Row[]=inputs.threads?.threads??[];
  const current=runtime?.refresh_state==='ready'&&!failed.includes('runtime');
  const active=bots.filter(b=>current&&b.state?.kind!=='unknown'&&['working','starting','waiting'].includes(b.state?.value));
  const validThreads=inputs.threads?.adapter?.health==='ready'&&!failed.includes('threads');
  const running=validThreads?threads.filter(t=>t.observed===true&&['running','working','waiting_for_user','waiting_for_approval'].includes(t.status)):[];
  return <><div className="ow-two"><section className="cx-card"><header className="cx-section-heading"><div><h2>지금 누가 일하고 있나요?</h2><p>실행 관측이 있는 작업만 활동으로 표시합니다.</p></div></header>{active.length||running.length?<>{active.map(b=><div className="ow-work" key={b.bot_id}><strong>{b.display_label}</strong><span>{b.state.value}</span><small>최근 활동 {when(b.heartbeat?.value)} · {b.model?.value??'모델 미확인'}</small></div>)}{running.slice(0,6).map(t=><div className="ow-work" key={t.thread_id}><strong>{t.display_label}</strong><span>{t.status}</span><small>{when(t.updated_at)}</small></div>)}</>:<div className="ow-empty"><strong>{current&&validThreads?'현재 활동으로 관측된 작업이 없습니다.':'현재 활동 여부를 확인할 수 없습니다.'}</strong><p>프로세스 존재나 등록된 이름만으로 작업 중이라고 판단하지 않습니다.</p></div>}<details><summary>연결된 관측과 마지막 작업 기록</summary>{bots.map(b=><p key={b.bot_id}><strong>{b.display_label}</strong> · {b.hold_code==='GATEWAY_DISCONNECTED'?'Hermes 연결 끊김':current?b.state?.value??'미확인':'현재 활동 미확인'}</p>)}<p>맥락이·강도담의 세부 작업 단계: 전용 실행 기록 연결 미확인</p><p>Codex 작업 관측: {validThreads?'조회됨':'최신 조회 불가 · 이전 기록'}</p>{threads.slice(0,5).map(t=><p key={t.thread_id}>{t.display_label} <small>{when(t.updated_at)} · {t.status}</small></p>)}</details></section>
  <section className="cx-card"><header className="cx-section-heading"><div><h2>최근 들어온 자료</h2><p>자료 도착과 RAG 반영은 따로 확인합니다.</p></div><button onClick={()=>go({screen:'directory',node:null})}>공간 열기 <ArrowRight size={14}/></button></header>{inputs.recent?.rows?.length?inputs.recent.rows.slice(0,4).map((r:Row)=><div className="ow-arrival" key={r.id}><span className="ow-source">{r.source}</span><div><strong>{r.date||'녹음'} · 녹음 자료</strong><small>{r.status} · 등록 {when(r.at)}</small><small>전사 {r.segments??'미확인'}개 · 음성 조각 {r.chunks??'미확인'}개</small></div></div>):<p className="ow-empty">PLAUD 등록 원장을 읽지 못했습니다.</p>}<p className="cx-footnote">{inputs.recent?.scope} · 기준 {when(inputs.recent?.observed_at)}</p><button onClick={()=>go({screen:'rag',node:null})}>Slack·메일·문서의 최근 처리 보기 <ArrowRight size={15}/></button></section></div></>;
}

export function RecentRag({go}:{go:(n:any)=>void}){
  const [summary,setSummary]=useState<Row|null>(null),[project,setProject]=useState(''),[detail,setDetail]=useState<Row|null>(null),[error,setError]=useState('');
  useEffect(()=>{let alive=true;void localRead('/rag-operations.json').then(d=>{if(alive){setSummary(d);setProject(d.projects?.[0]?.project??'');if(d.state!=='ready')setError('현재 DB 대조를 확인하지 못했습니다.');}},()=>{if(alive)setError('RAG 기록을 읽지 못했습니다.');});return()=>{alive=false;};},[]);
  useEffect(()=>{let alive=true;if(!project)return;setDetail(null);void localRead(`/rag-operations.json?project=${encodeURIComponent(project)}`).then(d=>{if(alive)setDetail(d);},()=>{if(alive)setDetail({state:'unavailable'});});return()=>{alive=false;};},[project]);
  const names:Row={slack:'Slack',voice:'PLAUD·음성',mail:'메일',document:'DOC',linear:'Linear',buzz:'Buzz'};
  const groups:Row={};for(const doc of detail?.documents??[]){if(!groups[doc.source])groups[doc.source]=[];groups[doc.source].push(doc);}
  const current=summary?.projects?.find((p:Row)=>p.project===project);
  return <section className="cx-card"><header className="cx-section-heading"><div><h2>최근 반영 판본에 어떤 자료가 있나요?</h2><p>{project} · DB 반영 {when(current?.database?.loaded_at)} · {current?.comparison==='counts_match'?'현재 저장 판본·DB 수량 일치':'현재 DB 대조 확인 필요'}</p></div><select aria-label="최근 처리 자료 과제" value={project} onChange={e=>setProject(e.target.value)}>{summary?.projects?.map((p:Row)=><option key={p.project}>{p.project}</option>)}</select></header>{error&&<p className="cx-notice">{error}</p>}{Object.entries(groups).map(([source,docs]:[string,any])=><div className="ow-arrival" key={source}><span className="ow-source">{names[source]??source}</span><div><strong>{docs.length}개 문서 · 준비 확인 {docs.filter((d:Row)=>d.preparation==='prepared').length}개</strong>{docs.slice(0,2).map((d:Row)=><small key={d.id}>{d.item} · {d.units??'미확인'}개 단위 · {d.origin??'처리 방식 미확인'}</small>)}</div></div>)}{!detail&&!error&&<p>현재 판본의 처리 기록을 읽는 중…</p>}{detail&&(!detail.documents?.length||detail.state!=='ready')&&<p>표시할 문서 근거가 없거나 읽지 못했습니다. 수집 0건으로 해석하지 않습니다.</p>}<p className="cx-footnote">선택 과제의 현재 판본 범위입니다. 문서별 도착 순서는 이 기록에 없으므로 최신순이라고 표시하지 않습니다.</p><button onClick={()=>go({screen:'rag',node:null})}>전처리·임베딩·재처리 이력 확인 <ArrowRight size={15}/></button></section>;
}

function Preview({selection,close,standalone=false}:{selection:Row;close:()=>void;standalone?:boolean}){
  const [data,setData]=useState<Row|null>(null),[error,setError]=useState('');
  useEffect(()=>{if(standalone)return;const key=(event:KeyboardEvent)=>{if(event.key==='Escape')close();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[close,standalone]);
  useEffect(()=>{let alive=true;setData(null);setError('');localRead(route('file',selection)).then(d=>{if(alive)setData(d);},()=>{if(alive)setError('파일 미리보기를 읽지 못했습니다.');});return()=>{alive=false;};},[selection]);
  const [blob,setBlob]=useState('');
  useEffect(()=>{if(!data?.base64){setBlob('');return;}const bytes=Uint8Array.from(atob(data.base64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:data.mime}));setBlob(url);return()=>URL.revokeObjectURL(url);},[data]);
  return <aside className={`ow-preview ${standalone?'standalone':''}`} aria-label="파일 미리보기"><header><div><small>읽기 전용 미리보기</small><h2>{selection.relative.split('/').at(-1)}</h2></div>{!standalone&&<button onClick={close} aria-label="미리보기 닫기"><X size={20}/></button>}</header><div className="ow-preview-tools"><span>{size(data?.size)} · 조회 {when(data?.read_at)}</span>{!standalone&&<a target="_blank" rel="noopener noreferrer" href={`/operations-console.html?preview=1&${new URLSearchParams(selection)}`}>별도 창 <ArrowUpRight size={14}/></a>}</div>{data?.note&&<p className="cx-footnote">{data.note}</p>}<div className="ow-preview-body">{error?<p>{error}</p>:!data?<p>파일 읽는 중…</p>:data.state!=='ready'?<p>{data.reason}</p>:data.kind==='text'?<pre>{data.text}</pre>:data.kind==='image'?<img src={blob} alt={data.name}/>:<p>표시 형식을 확인하지 못했습니다.</p>}</div>{data?.sha256&&<details><summary>파일 근거</summary><small>{data.sha256}</small><p>원문은 이 PC의 미리보기에만 표시됩니다.</p></details>}</aside>;
}
function SpacePanel({space,project,onFile}:{space:Row;project:string;onFile:(r:Row)=>void}){
  const [cache,setCache]=useState<Row>({}),[open,setOpen]=useState<Set<string>>(new Set([''])),[folded,setFolded]=useState(false),[pending,setPending]=useState<Set<string>>(new Set());
  const epoch=useRef(0);
  async function load(relative:string){const e=epoch.current;setPending(old=>new Set(old).add(relative));try{const d=await localRead(route('spaces',{space:space.id,project,relative}));if(e===epoch.current)setCache(old=>({...old,[relative]:d}));}catch{if(e===epoch.current)setCache(old=>({...old,[relative]:{state:'unavailable',reason:'목록을 읽지 못했습니다.'}}));}finally{if(e===epoch.current)setPending(old=>{const next=new Set(old);next.delete(relative);return next;});}}
  useEffect(()=>{epoch.current++;setCache({});setOpen(new Set(['']));void load('');return()=>{epoch.current++;};},[space.id,project]);
  const render=(parent:string,depth=0):React.ReactNode=>{const data=cache[parent];if(!data)return <p className="cx-muted">목록 읽는 중…</p>;return <>{data.entries?.map((entry:Row)=>{const relative=[parent,entry.name].filter(Boolean).join('/'),expanded=open.has(relative);return <div key={relative}><button className="ow-file-row" style={{paddingLeft:8+depth*14}} onClick={()=>{if(entry.browsable){setOpen(old=>{const n=new Set(old);n.has(relative)?n.delete(relative):n.add(relative);return n;});if(!cache[relative])void load(relative);}else if(entry.kind==='file')onFile({space:space.id,project,relative});}} disabled={entry.kind==='link'} title={entry.name}><span>{entry.browsable?(expanded?<ChevronDown size={13}/>:<ChevronRight size={13}/>):<FileText size={13}/>}<span>{entry.name}</span></span><small>{entry.browsable?'폴더':size(entry.size)}</small><time>{when(entry.modified_at)}</time></button>{entry.browsable&&expanded&&depth<20&&render(relative,depth+1)}</div>;})}{(!data.entries?.length||data.state!=='ready')&&<p className="ow-folder-note">{data.state==='ready'&&!data.entries?.length?`표시 가능한 항목이 없습니다${data.excluded?` · 보호 항목 ${data.excluded}개 제외`:''}.`:data.reason??'이 범위에 표시할 파일이 없습니다.'}</p>}</>;};
  return <section className="cx-card ow-space"><header><button aria-expanded={!folded} onClick={()=>setFolded(v=>!v)}>{folded?<ChevronRight size={17}/>:<ChevronDown size={17}/>}<FolderOpen size={19}/><h2>{space.label}</h2></button><button aria-label={`${space.label} 다시 읽기`} disabled={pending.size>0} onClick={()=>{for(const relative of open)void load(relative);}}><RefreshCw size={15}/></button></header><p className="cx-muted">{space.note}</p>{!folded&&<><div className="ow-file-head"><span>이름</span><span>크기</span><span>수정 시각</span></div><div className="ow-folder-body">{render('')}</div><footer>스캔 {when(cache['']?.scanned_at)} · {cache['']?.state==='partial'?'일부 목록':cache['']?.state==='ready'?'직접 하위 목록':'읽기 미확인'}<br/>폴더 전체 크기·전 디스크 합계는 계산하지 않습니다.</footer></>}</section>;
}
export function DataSpaces({active,memory=false}:{active:boolean;memory?:boolean}){
  const [catalog,setCatalog]=useState<Row|null>(null),[project,setProject]=useState(''),[selection,setSelection]=useState<Row|null>(null),[error,setError]=useState('');
  useEffect(()=>{if(!active)return;let alive=true;localRead(route('spaces',{project})).then(d=>{if(alive){setCatalog(d);setError(d.state==='ready'?'':d.reason||'허용된 데이터 공간을 확인하지 못했습니다.');if(!project&&d.projects?.length)setProject(d.projects[0]);}},()=>{if(alive)setError('데이터 공간을 읽지 못했습니다.');});return()=>{alive=false;};},[active,project]);
  const spaces=(catalog?.spaces??[]).filter((s:Row)=>!memory||['memory','context'].includes(s.id));
  return <><header className="cx-section-heading"><div><h2>{memory?'어떤 기억과 맥락이 남아 있나요?':'자주 보는 자료를 바로 펼쳐봅니다.'}</h2><p>{memory?'실제 과제의 기억·맥락 저장 공간입니다. 비어 있음과 읽기 실패를 구분합니다.':'PLAUD · Slack · DOC · 과제 자료 — 파일을 누르면 옆에 열립니다.'}</p></div><label>과제 <select aria-label="데이터 공간 과제" value={project} onChange={e=>{setProject(e.target.value);setSelection(null);}}>{catalog?.projects?.map((p:string)=><option key={p}>{p}</option>)}</select></label></header>{memory&&<p className="cx-notice">단기·장기·추론 기억의 분류와 활성 여부는 현재 저장 계약에 그 근거가 있을 때만 판단할 수 있습니다. 폴더가 있다는 이유로 기억이 만들어졌다고 표시하지 않습니다.</p>}{error&&<p role="alert">{error}</p>}<div className="ow-spaces-grid">{spaces.map((s:Row)=><SpacePanel key={`${s.id}:${project}`} space={s} project={project} onFile={setSelection}/>)}</div>{!catalog&&<p>허용된 데이터 공간을 읽는 중…</p>}{selection&&<Preview selection={selection} close={()=>setSelection(null)}/>}</>;
}
export function StandalonePreview(){const params=new URLSearchParams(location.search);const [selection]=useState({space:params.get('space')??'',relative:params.get('relative')??'',project:params.get('project')??''});return <div className="cx-app" data-theme="light"><Preview selection={selection} close={()=>{}} standalone/></div>;}

export function EvidenceSearch({active}:{active:boolean}){
  const [projects,setProjects]=useState<string[]>([]),[project,setProject]=useState(''),[question,setQuestion]=useState(''),[investigation,setInvestigation]=useState(()=>`ops-${crypto.randomUUID()}`),[data,setData]=useState<Row|null>(null),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Row|null>(null);
  useEffect(()=>{if(active&&!projects.length)void localRead('/operations-spaces.json').then(d=>{setProjects(d.projects??[]);setProject(d.projects?.[0]??'');});},[active,projects.length]);
  async function search(){setBusy(true);setData(null);setSelected(null);try{const response=await fetch('/operations-query.json',{method:'POST',credentials:'omit',redirect:'error',headers:{'Content-Type':'application/json'},body:JSON.stringify({project,question,investigation}),signal:AbortSignal.timeout(90000)});if(!response.ok)throw Error('read');setData(await response.json());}catch{setData({state:'unavailable',reason:'검색 응답을 확인하지 못했습니다. 다시 시도해도 기존 조사 예산에서 계산됩니다.'});}finally{setBusy(false);}}
  const result=data?.result?.results?.[0],evidence:Row[]=result?.evidence??[],groups:Row={};for(const row of evidence)groups[row.source_kind]=(groups[row.source_kind]??0)+1;
  return <><section className="cx-card"><header className="cx-section-heading"><div><h2>이 질문에 어떤 자료가 선택되나요?</h2><p>실제 Neo4j의 현재 과제 판본에서 기존 검색을 실행합니다.</p></div></header><form className="ow-query" onSubmit={e=>{e.preventDefault();void search();}}><select disabled={busy} aria-label="검색 과제" value={project} onChange={e=>{setProject(e.target.value);setData(null);}}>{projects.map(p=><option key={p}>{p}</option>)}</select><input disabled={busy} aria-label="질문 또는 검색어" placeholder="확인할 개념이나 정확한 검색어를 입력하세요" maxLength={2000} value={question} onChange={e=>setQuestion(e.target.value)}/><button className="cx-primary" disabled={busy||!project||!question.trim()}><Search size={16}/>{busy?'검색 중…':'근거 검색'}</button></form><p className="cx-footnote">단어 검색 · LLM·임베딩 호출 없음 · 결과 최대 12개 · 조사당 최대 6회. 생성 답변과 3D 그래프는 이번 범위에서 제외합니다.</p></section>{data?.state==='unavailable'||data?.state==='denied'||data?.state==='hold'?<p className="cx-notice">{data.reason}</p>:null}{data?.result&&<section className="cx-card"><header className="cx-section-heading"><div><h2>선택된 근거와 출처 분포</h2><p>판본 {data.result.generation?.generation_id} · {when(data.result.asked_at)} · 검색 상태 {result?.status??'미확인'} {result?.code??''}</p></div><span>남은 조회 {data.remaining??'미확인'}회</span></header><div className="ow-distribution">{Object.entries(groups).map(([key,count])=><div key={key}><span>{key}</span><div><i style={{width:`${Number(count)/Math.max(evidence.length,1)*100}%`}}/></div><strong>{String(count)} / {evidence.length}</strong></div>)}</div><p className="cx-footnote">선택 결과의 분포입니다. 전체 지식의 균형이나 검색 품질 점수는 아닙니다. DB 엣지의 실제 탐색 기록은 현재 검색 영수증에 없습니다.</p><div className="ow-evidence-list">{evidence.map((r,i)=><button key={`${r.unit_id}:${i}`} onClick={()=>setSelected(r)} aria-pressed={selected===r}><span className="ow-source">{r.source_kind}</span><div><strong>{r.title||r.item_id}</strong><p>{r.text}</p><small>순위 {r.rank} · 점수 {typeof r.score==='number'?r.score.toFixed(3):'미제공'}</small></div><ChevronRight size={15}/></button>)}{!evidence.length&&<p>이 검색에서 반환된 근거가 없습니다. 데이터 전체가 비어 있다는 뜻은 아닙니다.</p>}</div></section>}{selected&&<section className="cx-card"><h2>선택한 근거의 연결</h2><p>출처 <strong>{selected.source_kind}</strong> → 문서 <strong>{selected.item_id}</strong> → 선택된 청크 <strong>{selected.unit_id}</strong></p><p>{selected.text}</p><details><summary>원문 위치·판본 근거</summary><pre>{JSON.stringify({locator:selected.locator,revision_sha256:selected.revision_sha256,via:selected.via},null,2)}</pre></details></section>}<button disabled={busy} onClick={()=>{setInvestigation(`ops-${crypto.randomUUID()}`);setData(null);setSelected(null);}}>새 조사 시작</button><p className="cx-footnote">질문 원문과 검색 결과는 이 화면에만 유지합니다. 기존 조사 원장에는 호출·결과 코드만 남습니다.</p></>;
}
