import {type ReactNode} from 'react';
import {ChevronRight,ArrowUpRight,CircleHelp} from 'lucide-react';
import {when} from './operations-workspace';
type Row=Record<string,any>;
type Open=(title:string,body:ReactNode)=>void;
export function sourceChoices(inputs:Row){return [{id:'plaud',label:'PLAUD',state:'unavailable',basis:'등록일',scope:'녹음 라이브러리 등록 기록 · RAG 반영 별도',...inputs.recent},...(inputs.sources?.sources??['slack','mail','linear','docs'].map(id=>({id,label:{slack:'Slack',mail:'메일',linear:'Linear',docs:'DOC'}[id],state:'unavailable',rows:[],basis:'조회 미확인'})))];}
const short=(s:string)=>s?.slice(5).replace('-','/');
function SourceTabs({sources,value,select}:{sources:Row[];value:string;select:(id:string)=>void}){return <div className="vd-source-tabs" role="group" aria-label="자료 원천">{sources.map(s=><button key={s.id} aria-pressed={s.id===value} onClick={()=>select(s.id)}>{s.label}{s.state==='unavailable'&&<span aria-label="조회 미확인"> · —</span>}</button>)}</div>;}
export function SourcesChart({sources,sourceId,select,selectedDay,onDay,open,retained}:{sources:Row[];sourceId:string;select:(id:string)=>void;selectedDay:string|null;onDay:(d:string|null)=>void;open:Open;retained:boolean}){
  const source=sources.find(s=>s.id===sourceId)??sources[0],t=source.timeline,rows:Row[]=t?.daily??[],known=rows.filter(r=>typeof r.registrations==='number'),max=Math.max(1,...known.map(r=>r.registrations));
  return <section className="vd-panel vd-arrival-chart"><header><h2>자료 기록</h2><span className="vd-source-pill">{source.basis}</span><button className="vd-info" aria-label="자료 집계 범위" onClick={()=>open(`${source.label} · 집계 범위`,<><p>{source.scope}</p><p>조회 {when(source.observed_at??t?.as_of)}</p><p>원천마다 기준 시각과 단위가 다릅니다. 선택한 원천의 기록만 표시하며 서로 합산하지 않습니다. 빈 날짜의 —는 미확인입니다.</p></>)}><CircleHelp size={15}/></button></header>
    <SourceTabs sources={sources} value={sourceId} select={select}/>
    {known.length?<><div className="vd-chart-value"><strong>{t.state==='partial'?'≥ ':''}{t.total?.toLocaleString('ko-KR')}<small>건</small></strong><span>{short(t.start)}–{short(t.end)} · {retained?'보존값':sourceId==='mail'?'최근 실행 1회':t.state==='partial'?'일부 기록':'등록 기록'}</span></div><div className="vd-bars" aria-label={`${source.label} ${source.basis} 분포`}><div className="vd-bar-axis"><span>{max}</span><span>{Math.floor(max/2)}</span><span>0</span></div><div className="vd-bar-plot">{rows.map((r,i)=><button key={r.date} aria-label={`${source.label} ${r.date} ${r.registrations??'미확인'}건`} aria-pressed={selectedDay===r.date} className={`${selectedDay===r.date?'selected':''} ${r.registrations===null?'unknown':''}`} onClick={()=>onDay(selectedDay===r.date?null:r.date)}><span className="vd-bar-value">{r.registrations??'—'}</span><i style={{height:`${(r.registrations??0)/max*100}%`}}/><small>{i===0||i===rows.length-1||i%3===0?short(r.date):''}</small></button>)}</div></div></>:<div className="vd-chart-empty">{source.state==='unavailable'?'기록 조회 미확인':'조회 범위에 날짜별 기록 없음'}</div>}
    <div className="vd-chart-foot"><span>{source.basis} · {sourceId==='mail'?'새 메일 수 · 과거 실행 미조회':'RAG 완료량과 별도'}</span>{selectedDay&&<button onClick={()=>onDay(null)}>날짜 해제</button>}</div>
  </section>;
}
export function SourceRecent({sources,sourceId,selectedDay,open,go}:{sources:Row[];sourceId:string;selectedDay:string|null;open:Open;go:(n:any)=>void}){
  const source=sources.find(s=>s.id===sourceId)??sources[0];
  // Default is one recent record per source, so one busy source cannot hide others.
  const rows:Row[]=selectedDay?(source.timeline?.records??[]).filter((r:Row)=>new Date(Date.parse(r.at)+9*3600000).toISOString().slice(0,10)===selectedDay):sources.map(s=>s.rows?.[0]?{...s.rows[0],basis:s.basis}:({id:`empty-${s.id}`,source:s.label,title:s.state==='unavailable'?'조회 미확인':'조회 범위에 기록 없음',unavailable:true,scope:s.scope}));
  return <section className="vd-panel vd-recent"><header><h2>{selectedDay?`${source.label} · ${short(selectedDay)}`:'원천별 최근 기록'}</h2><button className="vd-header-link" onClick={()=>go({screen:'directory',node:null})}>데이터 공간<ArrowUpRight size={14}/></button></header>{rows.slice(0,8).map(r=><button className="vd-source-record" key={r.id} onClick={()=>open(`${r.source} · 기록`,<><dl className="vd-facts"><dt>기록</dt><dd>{r.title??`${r.date} 녹음`}</dd><dt>기준</dt><dd>{r.basis??'등록일'}</dd><dt>시각</dt><dd>{when(r.at)}</dd><dt>확인 내용</dt><dd>{r.status??r.scope??'미확인'}</dd>{typeof r.segments==='number'&&<><dt>전사 단위</dt><dd>{r.segments}</dd></>}</dl><p>이 기록만으로 RAG 반영·검색 성공을 판정하지 않습니다.</p><button onClick={()=>go({screen:'rag',node:null})}>RAG 처리 확인<ArrowUpRight size={14}/></button></>)}><span className="vd-source-pill">{r.source}</span><strong>{r.title??`${r.date} 녹음`}</strong><time>{r.unavailable?'—':when(r.at)}</time><ChevronRight size={13}/></button>)}{!rows.length&&<p className="vd-muted">선택 날짜의 제공 목록에 기록 없음</p>}<div className="vd-chart-foot">{selectedDay?'선택한 원천·날짜의 일부 기록':'원천마다 최근 1건 · 상세에서 시각 기준 확인'}</div></section>;
}
