import {ProjectText} from './project-labels';
import {useState,type ReactNode} from 'react';
import {ChevronRight,ArrowUpRight,CircleHelp} from 'lucide-react';
import {when} from './operations-workspace';
import {collectionProcessing} from './core/collection-processing.mjs';
type Row=Record<string,any>;
type Open=(title:string,body:ReactNode)=>void;
export function sourceChoices(inputs:Row){return [{id:'plaud',label:'PLAUD',state:'unavailable',basis:'등록일',scope:'녹음 라이브러리 등록 기록 · RAG 반영 별도',...inputs.recent},...(inputs.sources?.sources??['slack','mail','linear','docs'].map(id=>({id,label:{slack:'Slack',mail:'메일',linear:'Linear',docs:'DOC'}[id],state:'unavailable',rows:[],basis:'조회 미확인'})))];}
const short=(s?:string|null)=>s?.includes('T')?when(s):s?.slice(5).replace('-','/');
function SourceTabs({sources,value,select}:{sources:Row[];value:string;select:(id:string)=>void}){return <div className="vd-source-tabs" role="group" aria-label="자료 원천"><button aria-pressed={value==='all'} onClick={()=>select('all')}>종합</button>{sources.map(s=><button key={s.id} aria-pressed={s.id===value} onClick={()=>select(s.id)}>{s.label}{s.state==='unavailable'&&<span aria-label="조회 미확인"> · —</span>}</button>)}</div>;}
const number=(v:any)=>typeof v==='number'?v.toLocaleString('ko-KR'):'—';
const barText=(s:Row,d:Row)=>`${d.label} · 모은 자료 ${number(d.value)} · 검색에 포함 ${d.processed===null?'확인할 수 없음':number(d.processed)}`;
function CohortBar({point,max}:{point:Row;max:number}){if(point.value===null)return null;return <i className={`vd-cohort-outline ${point.processed===null?'unmatched':''}`} style={{height:point.value===null?'0%':`${point.value/max*100}%`}}><b className="vd-cohort-fill" style={{height:point.value>0&&point.processed!==null?`${point.processed/point.value*100}%`:'0%'}}/></i>;}
function SourceSummary({comparison,select,onDay}:{comparison:Row;select:(id:string)=>void;onDay:(day:string|null)=>void}){
  return <div className="vd-source-summary"><div className="vd-comparison-period"><strong>원천별 종합</strong><span>{comparison.buckets[0]?.label}–{comparison.buckets.at(-1)?.label} · KST</span></div>
    <table aria-label="모은 자료와 검색 포함 현황"><thead><tr><th>원천 · 기준</th><th>모은 자료 중 검색에 포함<small>현재 과제 검색 목록 기준</small></th><th>모음 / 검색</th></tr></thead><tbody>{comparison.rows.map((s:Row)=><tr key={s.id} data-source={s.id}><th scope="row"><button onClick={()=>select(s.id)}>{s.label}<ChevronRight size={11}/></button><small>{s.basis}</small></th><td><div className="vd-source-spark" aria-label={`${s.label} 자료와 검색 포함`}>{s.daily.map((d:Row)=><button key={d.date} className={d.value===null?'unknown':d.value===0?'zero':''} title={barText(s,d)} aria-label={`${s.label} ${barText(s,d)}`} onClick={()=>{select(s.id);onDay(d.date);}}><CohortBar point={d} max={s.max}/></button>)}</div><small className="vd-source-latest">{s.lastAt?`최근 ${when(s.lastAt)}`:'기록 시각 없음'}</small></td><td><strong>{s.partial&&s.total!==null?'≥ ':''}{number(s.total)}</strong><small>검색 {s.processedPartial&&s.processed>0?'≥ ':''}{number(s.processed)}</small></td></tr>)}</tbody></table>
  </div>;
}
export function SourcesChart({sources,rag,sourceId,select,selectedDay,onDay,open,retained,processing}:{rag?:Row;processing?:Row;sources:Row[];sourceId:string;select:(id:string)=>void;selectedDay:string|null;onDay:(d:string|null)=>void;open:Open;retained:boolean}){
  const [days,setDays]=useState(7),comparison=collectionProcessing(sources,rag,days);
  const source=comparison.rows.find((s:Row)=>s.id===sourceId)??comparison.rows[0],rows:Row[]=source?.daily??[],known=rows.filter(r=>r.value!==null),max=source?.max??1;
  return <section className="vd-panel vd-arrival-chart"><header><h2>자료 수집 · 검색 포함</h2><div className="op-period" role="group" aria-label="수집 조회 기간">{[1,7,30].map(d=><button key={d} aria-pressed={days===d} onClick={()=>{setDays(d);onDay(null);}}>{d}일</button>)}</div><button className="vd-info" aria-label="자료 수집과 검색 포함의 뜻" onClick={()=>open('자료와 검색 포함 기준',<><p>테두리: 선택 기간에 모은 자료 수입니다. 채움: 그중 같은 본문 버전이 현재 과제의 검색 목록에 들어 있는 자료 수입니다. 검색해서 답변에 쓰일 후보라는 뜻이며, 실제 검색 성공을 뜻하지는 않습니다.</p><p>조회 {rag?.expected??'—'}개 과제에서 같은 자료는 한 번만 셉니다. 본문 기준이며 댓글·첨부 전체의 처리가 끝났다는 뜻은 아닙니다.</p><p>빈 테두리: 검색에 포함됐다고 확인된 수에 들지 않은 자료입니다. 처리 대상이 아닌지, 처리되지 않았는지는 이 그래프만으로 알 수 없습니다. 사선: 모은 자료와 검색 목록을 연결할 기록이 부족해 포함 수를 계산할 수 없습니다.</p><p>가로축은 원천별 등록일·작성일·수정일·수집일이며 처리 완료일이 아닙니다. ≥는 최소 확인 수, —는 알 수 없는 값입니다. 원천별 집계 기준이 달라 합산하지 않습니다.</p></>)}><CircleHelp size={15}/></button></header>
    <SourceTabs sources={sources} value={sourceId} select={select}/>
    <div className="vd-cohort-legend"><span><i/>모은 자료</span><span><b/>검색에 포함</span><span><em/>포함 여부 모름</span></div>
    {sourceId==='all'?<SourceSummary comparison={comparison} select={select} onDay={onDay}/>:<>{known.length?<><div className="vd-chart-value"><strong>{source.partial&&source.total!==null?'≥ ':''}{number(source.total)}<small>모은 자료</small></strong><strong>{source.processedPartial&&source.processed>0?'≥ ':''}{number(source.processed)}<small>검색에 포함</small></strong></div><div className="vd-bars" aria-label={`${source.label} 자료와 검색 포함 분포`}><div className="vd-bar-axis"><span>{max}</span><span>{Math.floor(max/2)}</span><span>0</span></div><div className="vd-bar-plot">{rows.map((r,i)=><button key={r.date} title={barText(source,r)} aria-label={`${source.label} ${barText(source,r)}`} aria-pressed={selectedDay===r.date} className={`${selectedDay===r.date?'selected':''} ${r.value===null?'unknown':''}`} onClick={()=>onDay(selectedDay===r.date?null:r.date)}><span className="vd-bar-value">{number(r.value)} / {number(r.processed)}</span><CohortBar point={r} max={max}/><small>{i===0||i===rows.length-1||i%Math.ceil(rows.length/5)===0?r.label:''}</small></button>)}</div></div></>:<div className="vd-chart-empty">선택 기간의 자료 수를 확인할 수 없습니다</div>}
    <div className="vd-chart-foot"><span>{source.basis}{retained?' · 보존값':''}</span>{selectedDay&&<button onClick={()=>onDay(null)}>선택 해제</button>}</div></>}
    <p className="vd-chart-foot">빈 부분은 대상 제외·미처리를 구분할 수 없음 · ≥ 최소 확인 수 · — 알 수 없음 · {days===1?'시간':'일'}별 · KST</p>
    <div className="vd-source-explanations">{(sourceId==='all'?comparison.rows:[source]).filter((s:Row)=>s.total!==null&&s.total>0&&(s.processed===null||s.processedPartial)).map((s:Row)=><p className="vd-chart-foot" key={s.id}><strong>{s.label}</strong> · {rag?.state!=='ready'?'검색 목록을 읽지 못해 포함 수를 알 수 없습니다. 조회가 끝난 뒤에도 같으면 다시 읽기를 눌러주세요.':s.id==='mail'?'메일별 처리 기록이 연결되지 않아 검색 포함 수를 계산할 수 없습니다. 화면의 집계 연결 보완이 필요하며, 메일 재처리 여부는 이 표시로 판단할 수 없습니다.':'일부 자료의 검색 포함 여부를 계산할 기록이 부족합니다. 전체 수를 확인하려면 조회 범위와 처리 기록 연결을 점검해야 합니다.'}</p>)}</div>
    {processing&&<div className="oc-intake-progress" aria-label="PLAUD 수집 진행"><span className="cx-status is-blue">PLAUD · 진행 중</span><strong>최근 등록 {processing.collection.imported??'—'}건 · 원본 보관 확인</strong><small>기존 주기로 순차 처리 · {when(processing.observedAt)}</small></div>}
  </section>;
}
export function SourceRecent({sources,sourceId,selectedDay,open,go}:{sources:Row[];sourceId:string;selectedDay:string|null;open:Open;go:(n:any)=>void}){
  const source=sources.find(s=>s.id===sourceId)??sources[0];
  // Default is one recent record per source, so one busy source cannot hide others.
  const rows:Row[]=selectedDay?(selectedDay.includes('T')&&source.timeline?.hourly_records?source.timeline.hourly_records:source.timeline?.records??[]).filter((r:Row)=>(selectedDay.includes('T')?Date.parse(r.at)>=Date.parse(selectedDay)&&Date.parse(r.at)<Date.parse(selectedDay)+3600000:new Date(Date.parse(r.at)+9*3600000).toISOString().slice(0,10)===selectedDay)):sources.map(s=>s.rows?.[0]?{...s.rows[0],basis:s.basis}:({id:`empty-${s.id}`,source:s.label,title:s.state==='unavailable'?'조회 미확인':'조회 범위에 기록 없음',unavailable:true,scope:s.scope}));
  return <section className="vd-panel vd-recent"><header><h2>{selectedDay?`${source.label} · ${short(selectedDay)}`:'원천별 최근 기록'}</h2><button className="vd-header-link" onClick={()=>go({screen:'directory',node:null})}>데이터 공간<ArrowUpRight size={14}/></button></header>{rows.slice(0,8).map(r=><button className="vd-source-record" key={r.id} onClick={()=>open(`${r.source} · 기록`,<><dl className="vd-facts"><dt>기록</dt><dd><ProjectText text={r.title??`${r.date} 녹음`}/></dd><dt>기준</dt><dd>{r.basis??'등록일'}</dd><dt>시각</dt><dd>{when(r.at)}</dd><dt>확인 내용</dt><dd>{r.status??r.scope??'미확인'}</dd>{typeof r.segments==='number'&&<><dt>전사 단위</dt><dd>{r.segments}</dd></>}</dl><p>이 기록만으로 RAG 반영·검색 성공을 판정하지 않습니다.</p><button onClick={()=>go({screen:'rag',node:null})}>RAG 처리 확인<ArrowUpRight size={14}/></button></>)}><span className="vd-source-pill">{r.source}</span><strong><ProjectText text={r.title??`${r.date} 녹음`}/></strong><time>{r.unavailable?'—':when(r.at)}</time><ChevronRight size={13}/></button>)}{!rows.length&&<p className="vd-muted">선택 날짜의 제공 목록에 기록 없음</p>}<div className="vd-chart-foot">{selectedDay?'선택한 원천·날짜의 일부 기록':'원천마다 최근 1건 · 상세에서 시각 기준 확인'}</div></section>;
}
