import {ProjectNamesContext,ProjectLabel} from './project-labels';
import {projectLabel} from './core/project-label.mjs';
import {RagTrend} from './rag-trend';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,ArrowRight,Check,CircleHelp,Clock3,Database,FileText,History,Layers,RefreshCw,Search,ShieldCheck,X} from 'lucide-react';
import './rag-operations.css';

type Row=Record<string,any>;
const n=(value:any)=>typeof value==='number'&&Number.isFinite(value)?value.toLocaleString('ko-KR'):'미확인';
const at=(value:any)=>value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('ko-KR'):'미확인';
const seconds=(value:any)=>typeof value==='number'?`${(value/1000).toLocaleString('ko-KR',{maximumFractionDigits:1})}초`:'미확인';
const sourceName:Record<string,string>={voice:'PLAUD·음성',slack:'Slack',linear:'Linear',mail:'메일',document:'문서',buzz:'Buzz'};
const comparison:Record<string,string>={counts_match:'현재 판본·청크 수 일치',changed_during_read:'조회 중 변경 · 재조회 필요',store_unavailable:'저장 판본 확인 불가',not_in_database:'현재 DB에 없음',different_generation:'저장·DB 판본 다름',chunk_count_mismatch:'청크 수 불일치',embedding_missing:'임베딩 없는 청크 있음',database_unavailable:'DB 조회 불가',database_binding_mismatch:'DB 연결 범위 다름',unconfirmed:'대조 근거 부족'};
const statusName:Record<string,string>={SYNCED:'반영됨',UNCHANGED:'변경 없음',HOLD:'보류',FAILED:'실패',COMMITTED:'판본 생성',WRITTEN:'파생 판본 생성',complete:'기록상 완료',prepared:'준비 기록 확인',extracted:'새로 추출',carried:'이전 결과 재사용',reembedded:'재임베딩'};
async function read(project?:string){const url='/rag-operations.json'+(project?`?project=${encodeURIComponent(project)}`:'');const response=await fetch(url,{credentials:'omit',cache:'no-store',redirect:'error',signal:AbortSignal.timeout(45000)});if(!response.ok||!response.headers.get('content-type')?.includes('application/json'))throw Error('read_failed');return response.json();}
function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`rag-badge ${tone}`}>{tone==='ok'?<Check size={13}/>:tone==='warn'?<CircleHelp size={13}/>:null}{children}</span>;}
function Empty({children}:{children:React.ReactNode}){return <div className="rag-empty"><CircleHelp size={26}/><p>{children}</p></div>;}
function Stat({title,value,note}:{title:string;value:any;note?:string}){return <div className="rag-stat"><span>{title}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>;}

function App(){
  const [snapshot,setSnapshot]=useState<Row|null>(null),[detail,setDetail]=useState<Row|null>(null),[project,setProject]=useState(new URLSearchParams(location.search).get('project')??'');
  const [tab,setTab]=useState('documents'),[loading,setLoading]=useState(false),[detailLoading,setDetailLoading]=useState(false),[error,setError]=useState('');
  const [source,setSource]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Row|null>(null),[generation,setGeneration]=useState<Row|null>(null);
  const requestId=useRef(0),inFlight=useRef(false);
  const load=useCallback(async()=>{if(inFlight.current)return;inFlight.current=true;setLoading(true);setError('');try{const value=await read();setSnapshot(value);setProject(old=>old||value.projects?.[0]?.project||'');if(value.state!=='ready')setError(value.reason||'DB 조회 불가');}catch{setSnapshot(null);setDetail(null);setError('최신 조회를 완료하지 못했습니다. 현재 상태는 미확인으로 표시합니다.');}finally{inFlight.current=false;setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{
    const epoch=++requestId.current;if(!project)return;
    setDetail(null);setSelected(null);setGeneration(null);setSource('all');setQuery('');setDetailLoading(true);
    void read(project).then(value=>{if(epoch===requestId.current)setDetail(value);},()=>{if(epoch===requestId.current)setDetail({state:'unavailable',reason:'project_read_failed'});}).finally(()=>{if(epoch===requestId.current)setDetailLoading(false);});
    return()=>{requestId.current++;};
  },[project,snapshot?.observed_at]);
  const row=snapshot?.projects?.find((p:Row)=>p.project===project),db=row?.database,store=row?.store;
  const documents:Row[]=detail?.documents??[];
  const sources=[...new Set(documents.map(r=>r.source))];
  const rows=useMemo(()=>documents.filter(r=>(source==='all'||r.source===source)&&(!query||`${r.item} ${r.id}`.toLowerCase().includes(query.toLowerCase()))),[documents,source,query]);
  const total=(key:string)=>!error&&snapshot?.state==='ready'&&snapshot.projects?.length>0&&snapshot.projects.every((r:Row)=>typeof r.database?.[key]==='number')?snapshot.projects.reduce((sum:number,r:Row)=>sum+r.database[key],0):null;
  const displayDetail=detail?.state==='ready';
  const metadataStatus=detail?.preparation?.state;
  const names=Object.fromEntries((snapshot?.projects??[]).map((p:Row)=>[p.project,p.project_name]));
  return <ProjectNamesContext.Provider value={names}><div className={`rag-app ${new URLSearchParams(location.search).get('embedded')==='1'?'rag-embedded':''}`}><header className="rag-topbar"><a href="/operations-console.html"><ArrowLeft size={17}/>운영 미리보기</a><strong>Soulforge <span>RAG</span></strong><span>실제 로컬 DB · 읽기 전용</span></header>
    <main><div className="rag-title"><div><small>검색 준비부터 실제 반영까지</small><h1>RAG 처리 상태</h1><p>Neo4j의 현재 데이터와 저장된 전처리·임베딩 이력을 함께 확인합니다.</p></div><button className="rag-primary" disabled={loading} onClick={()=>void load()}><RefreshCw size={16}/>{loading?'읽는 중':'DB·기록 다시 조회'}</button></div>
      <div className="rag-connection"><Database size={18}/><strong>{error?'DB 현재성 확인 필요':snapshot?.state==='ready'?'Neo4j 실조회 연결':'DB 읽는 중'}</strong><span>조회 {at(snapshot?.observed_at)}</span><small>60초 캐시 · 재임베딩·색인 갱신은 실행하지 않음</small></div>
      {error&&<div className="rag-notice" role="status">{error}</div>}
      <section className="rag-global"><Stat title="설정된 과제의 DB 청크" value={n(total('chunks'))}/><Stat title="임베딩 속성이 있는 청크" value={n(total('embedded_chunks'))} note="벡터의 존재 확인 · 검색 품질과 별도"/><Stat title="벡터 색인" value={snapshot?.database?.vector_index?.state??'미확인'} note={`${n(snapshot?.database?.vector_index?.dimensions)}차원`}/><Stat title="DB 잔여 노드" value={n(snapshot?.database?.residue_nodes)} note="삭제 대상이나 쓰레기로 단정하지 않음"/></section>
      <div className="rag-layout"><aside className="rag-projects"><h2>과제 선택</h2><p>{snapshot?.projects?.length??0} / {snapshot?.expected??'미확인'} · 설정된 범위</p>{snapshot?.projects?.map((r:Row)=><button key={r.project} onClick={()=>setProject(r.project)} className={project===r.project?'selected':''} aria-pressed={project===r.project}><strong><ProjectLabel code={r.project}/></strong><span>{r.database?n(r.database.chunks)+' 청크':'DB 근거 없음'}</span><small>{comparison[r.comparison]??r.comparison}</small></button>)}{!snapshot?.projects?.length&&<p>등록된 조회 범위를 확인하지 못했습니다.</p>}</aside>
      <div className="rag-project-content"><section className="rag-panel"><header className="rag-section-title"><div><h2>{project?projectLabel(project,names):'과제를 선택하세요'}</h2><p>{store?.model?.embedder??'임베딩 모델 미확인'} <span className="rag-muted">· 저장 판본의 모델 기록</span></p></div><Badge tone={row?.comparison==='counts_match'?'ok':'warn'}>{comparison[row?.comparison]??'판본 대조 대기'}</Badge></header>
        <div className="rag-generation-pair"><div><small>저장소에서 선택한 판본</small><strong>{store?.generation??'미확인'}</strong></div><ArrowRight size={19}/><div><small>현재 Neo4j 적재 판본</small><strong>{db?.generation??'미확인'}</strong><span>적재 시각 {at(db?.loaded_at)}</span></div></div>
        <div className="rag-inline-stats"><span>DB 청크 <b>{n(db?.chunks)}</b></span><span>DB 임베딩 <b>{n(db?.embedded_chunks)}</b></span><span>임베딩 없음 <b>{n(db?.unembedded_chunks)}</b></span><span>저장 문서 <b>{n(store?.counts?.documents)}</b></span></div>
        <p className="rag-footnote">판본·청크 수 대조입니다. 전처리 품질·검색 성공·답변 품질을 보증하지 않습니다. 다른 작업이 갱신 중이면 조회값 사이에 시차가 있을 수 있습니다.</p>
      </section>
      {detail&&<RagTrend projects={[{project,runs:detail.runs,history_scope:detail.run_history}]} expected={1}/>}
      <nav className="rag-tabs" aria-label="RAG 기록 보기">{[['documents','자료·청크 상태',FileText],['generations','임베딩·판본 이력',Layers],['runs','처리 실행 이력',History]].map(([id,label,Icon]:any)=><button key={id} className={tab===id?'selected':''} aria-pressed={tab===id} onClick={()=>{setTab(id);setSelected(null);setGeneration(null);}}><Icon size={16}/>{label}</button>)}</nav>
      {detailLoading?<Empty>과제의 실제 기록을 읽고 있습니다.</Empty>:!displayDetail?<Empty>과제 기록을 확인하지 못했습니다. {detail?.reason??''}</Empty>:<>
        {tab==='documents'&&<section className="rag-panel"><header className="rag-section-title"><div><h2>문서별 준비·청크 기록</h2><p>현재 선택 판본의 메타데이터 · {n(detail?.documents_total)}개 중 {rows.length}개 표시</p></div><Badge tone={metadataStatus==='ready'?'ok':'warn'}>{metadataStatus==='ready'?'준비 근거 연결':'준비 근거 미확인'}</Badge></header>
          <div className="rag-filters"><select aria-label="자료 원천" value={source} onChange={e=>setSource(e.target.value)}><option value="all">모든 원천</option>{sources.map(s=><option key={s} value={s}>{sourceName[s]??s}</option>)}</select><label><Search size={15}/><input aria-label="자료 식별자 검색" placeholder="자료 식별자로 찾기" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
          {detail?.preparation?.limited&&<p className="rag-notice">표시 한도 500개 · 전체 자료 목록이 아닙니다.</p>}{metadataStatus!=='ready'&&<p className="rag-notice">전처리 검증 근거를 읽지 못했습니다. {detail?.preparation?.reason??''}</p>}
          <div className="rag-table-scroll"><table><thead><tr><th>원천·자료</th><th>전처리 기록</th><th>청크 기록</th><th>임베딩 기록</th><th>이번 판본</th></tr></thead><tbody>{rows.map((r:Row,i:number)=><tr key={r.id??i} className={selected?.id===r.id?'selected':''}><td><button className="rag-item-button" onClick={()=>setSelected(r)}><strong>{sourceName[r.source]??r.source}</strong><span>{r.item??r.id??'식별자 미제공'}</span></button></td><td><Badge tone={r.preparation==='prepared'?'ok':'neutral'}>{r.preparation==='prepared'?'준비 확인':'미확인'}</Badge></td><td>{n(r.stats.chunks)}</td><td>{n(r.stats.embedded_chunks)}</td><td>{statusName[r.origin]??r.origin??'미확인'}</td></tr>)}</tbody></table>{!rows.length&&<Empty>이 범위에서 표시할 자료 기록이 없습니다.</Empty>}</div><p className="rag-footnote">행의 청크·임베딩 수는 저장된 추출 기록입니다. 위쪽 DB 집계와 구분합니다. 항목별 DB 존재·검색 인용은 별도 근거가 필요합니다.</p>
          <details className="rag-pending"><summary>실패·제외·재시도 항목 ({detail?.pending_state==='ready'?detail.pending.length:'범위 미확인'})</summary><p className="rag-footnote">재시도 장부의 기록이며 정크 삭제 목록이 아닙니다. 상태 {detail?.pending_state}</p>{detail.pending?.map((r:Row,i:number)=><div key={i}><strong>{r.item??r.source_ref}</strong><span>{r.code} · 시도 {n(r.attempts)} · {r.state??'미확인'}</span><small>{at(r.last_seen)}</small></div>)}{detail?.pending_state!=='ready'&&<p>장부 근거 {detail?.pending_reason??'미확인'}</p>}</details>
        </section>}
        {tab==='generations'&&<section className="rag-panel"><header className="rag-section-title"><div><h2>임베딩과 판본 기록</h2><p>판본 ID 역순 · 최대 12개 · 수정 시각은 실행 시각이 아닙니다.</p></div><Badge>{detail.generation_history?.state==='ready'?'범위 내 읽기 완료':detail.generation_history?.state==='partial'?'제한된 판본 범위 표시':'기록 읽기 불가'}</Badge></header>
          <div className="rag-table-scroll"><table><thead><tr><th>판본</th><th>임베딩 모델</th><th>청크</th><th>변경 종류</th><th>기록 파일 수정</th></tr></thead><tbody>{detail.generations?.map((r:Row)=><tr key={r.generation}><td><button className="rag-item-button" onClick={()=>setGeneration(r)}><strong>{r.generation}</strong><span>{r.in_database?'현재 DB 적재':r.selected?'저장소 선택':'저장된 구판·파생판'}</span></button></td><td>{r.model.embedder??'미확인'}<small className="rag-block">{r.model.dimensions?`${n(r.model.dimensions)}차원`:'개별 차원 기록 없음'}</small></td><td>{n(r.counts.chunks)}</td><td>{r.operation==='reembed'?'재임베딩':'추출·재사용'}<small className="rag-block">{r.operation==='reembed'?`재임베딩 문서 ${n(r.counts.reembedded)}`:`새 추출 ${n(r.counts.extracted)} · 재사용 ${n(r.counts.carried)}`}</small></td><td>{at(r.file_modified_at)}</td></tr>)}</tbody></table></div>{!detail.generations?.length&&<Empty>판본 기록을 읽지 못했습니다. {detail.generation_history?.reason}</Empty>}<p className="rag-footnote">발견 폴더 {n(detail.generation_history?.observed_folders)} · 읽기 실패 {n(detail.generation_history?.failed)}. 구판이 존재한다는 것과 지금 DB가 사용한다는 것은 다릅니다.</p>
        </section>}
        {tab==='runs'&&<section className="rag-panel"><header className="rag-section-title"><div><h2>최근 처리 실행 기록</h2><p>저장된 Graph Sync 영수증 · 최근 최대 24회</p></div><Badge>{detail.run_history?.state==='ready'?'범위 내 읽기 완료':detail.run_history?.state==='partial'?'최근 24회 범위 표시':'기록 읽기 불가'}</Badge></header><div className="rag-run-list">{detail.runs?.map((r:Row,i:number)=><details key={`${r.at}:${i}`}><summary><Clock3 size={16}/><strong>{at(r.at)}</strong><Badge tone={r.status==='HOLD'||r.status==='FAILED'?'warn':'neutral'}>{statusName[r.status]??r.status}</Badge><span>반영 {n(r.totals.completed)} · 대기 {n(r.totals.pending)} · 실패 {n(r.totals.failed)}</span></summary><div><p>판본 <b>{r.generation??'미확인'}</b> · {r.verified?'이 실행에서 DB 수량 되읽기 대조':'반영 검증 근거 미확인'}</p><p>색인 단계: {statusName[r.index.status]??r.index.status??'미확인'} · 소요 {seconds(r.index.elapsed_ms)}</p><p>추출 모델 호출 {n(r.llm.calls)} · 임베딩 호출 {n(r.llm.embedder_calls)} · 오류 {n(r.llm.errors)}</p>{r.code&&<p>{r.code}</p>}{r.isolated?.map((item:Row,j:number)=><p key={j}>{item.item} · {item.code} · {item.state}</p>)}</div></details>)}</div>{!detail.runs?.length&&<Empty>실행 이력을 읽지 못했습니다. {detail.run_history?.reason}</Empty>}<p className="rag-footnote">발견 파일 {n(detail.run_history?.observed_files)} · 읽기 실패 {n(detail.run_history?.failed)}. 과거 영수증이며 현재 DB 상태는 위의 실조회 값을 확인하세요.</p></section>}
      </>}
      <div className="rag-scope-note"><ShieldCheck size={17}/><p>질문별 노드·엣지 선택과 단기·장기 기억은 이 집계에서 추정하지 않습니다. 실제 질문 실행·기억 기록이 연결된 뒤 별도로 표시합니다.</p></div>
      </div></div>
    </main>
    {(selected||generation)&&<aside className="rag-inspector" aria-label="선택 기록 상세"><header><strong>{selected?'자료·청크 근거':'판본·임베딩 근거'}</strong><button aria-label="기록 상세 닫기" onClick={()=>{setSelected(null);setGeneration(null);}}><X size={18}/></button></header>{selected?<><h2>{sourceName[selected.source]??selected.source}</h2><p className="rag-identifier">{selected.item}</p><dl><dt>자료 ID</dt><dd>{selected.id}</dd><dt>전처리</dt><dd>{selected.preparation==='prepared'?'선택 판본의 준비 근거 확인':'준비 근거 미확인'}</dd><dt>본문 단위</dt><dd>{n(selected.units)}</dd><dt>기록된 청크</dt><dd>{n(selected.stats.chunks)}</dd><dt>기록된 임베딩</dt><dd>{n(selected.stats.embedded_chunks)}</dd></dl><h3>추출 당시의 무결성 기록</h3>{[['chunks_mismatched','원문 단위 불일치'],['duplicate_ids','중복 ID'],['entities_without_chunk','출처 청크 없는 개체'],['relationships_outside_fragment','조각 범위 밖 관계']].map(([key,label])=><p className="rag-check" key={key}><span>{label}</span><b>{n(selected.stats[key])}</b></p>)}<p className="rag-footnote">수치가 없으면 미확인입니다. 원문을 새로 읽거나 전체 청크를 재검사한 결과는 아닙니다.</p></>:<><h2>{generation?.generation}</h2><Badge tone={generation?.in_database?'ok':'neutral'}>{generation?.in_database?'현재 DB 판본':'저장된 판본'}</Badge><dl><dt>임베딩 모델</dt><dd>{generation?.model.embedder??'미확인'}</dd><dt>임베딩 모델 digest</dt><dd>{generation?.model.embedder_digest??'미확인'}</dd><dt>개별 판본 차원 기록</dt><dd>{n(generation?.model.dimensions)}</dd><dt>추출 모델</dt><dd>{generation?.model.extractor??'미확인'}</dd><dt>파생 원본 판본</dt><dd>{generation?.derived_from??'기록 없음'}</dd><dt>재임베딩 청크</dt><dd>{n(generation?.embedding.chunks)}</dd><dt>재임베딩 호출·소요</dt><dd>{n(generation?.embedding.calls)}회 · {seconds(generation?.embedding.elapsed_ms)}</dd><dt>추출 호출·소요</dt><dd>{n(generation?.llm.calls)}회 · {seconds(generation?.llm.elapsed_ms)}</dd><dt>기록 파일 수정 시각</dt><dd>{at(generation?.file_modified_at)}</dd></dl><p className="rag-footnote">재임베딩 기록이 없는 일반 추출 판본은 그 값을 0으로 대체하지 않습니다. 현재 DB 벡터 색인 차원은 상단에서 따로 확인합니다.</p></>}</aside>}
  </div></ProjectNamesContext.Provider>;
}
createRoot(document.getElementById('root')!).render(<App/>);
