// Offline author adjudication of the frozen synthetic experiment, not a judge model.
// No runtime imports this file; it never calls a consumer or changes frozen inputs.
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import { digest, evaluateAnswer } from './context_memory_t4_experiment.mjs';

const root = new URL('../../../docs/architecture/workspace/examples/context-memory/', import.meta.url);
const read = name => JSON.parse(readFileSync(new URL(name, root), 'utf8'));
const ids = Array.from({length:24}, (_, i) => 'Q' + String(i + 1).padStart(2, '0'));
// Fixed post-consumption review binding for the manual table below. These pins
// are never regenerated by the report writer. A different run/answer requires
// a new explicit review; recomputing the caller's raw SHA cannot reuse scores.
// The exact experiment pin covers gold, sources, model payloads and selection.
const reviewedExperiment = 'sha256:bb19d853685321139e67b6877b5f204702960a314bbc572c361a948be27778f3';
const reviewedResponses = Object.freeze([
  'sha256:b18e3887f5812d4e300e199cbd12b5a7045964b3bf693a8d1a8a152a82151f1a',
  'sha256:6129bac5c9df341a200cfd15abda4eddd87962a22790322886480cd85caa55e6',
  'sha256:496cd397ed5af83e2d00bf4137fe45078e5973acd2048b2b5cb2eb4fc3ba1899',
  'sha256:f20d92235813785c02af159fefe7305d055328fa64d501213abf6b3431acbb2c',
  'sha256:ea1e7ee7840cc979b55167dac28285a6405086561e34372ff420ad75889d2866',
  'sha256:395c97dfbc713d7594a6b07668f4defc0a67c4e19262a16bc33080c293d76410',
]);
// These are the author's explicit reading of all six delivered answers against
// source-bound content requirements. They are NOT inferred from used_refs.
const author = [
  {pass:[1,3,4,8,10,12,16,19,20], fail:[2,5,7,9,11,13,14,15,17,18,21,22,23,24]},
  {pass:[1,3,4,5,8,9,10,11,12,13,14,16,18,19,20,22,23,24], fail:[2,7,15,17,21]},
  {pass:[1,3,4,5,8,10,11,12,15,16,17,19,20,23,24], fail:[2,7,9,13,14,18,21,22]},
  {pass:[1,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24], fail:[2,21]},
  {pass:[1,3,4,8,9,10,12,13,14,16,17,19,20,24], fail:[2,5,7,11,15,18,21,22,23]},
  {pass:[1,3,4,5,8,10,11,12,15,16,17,19,20,23,24], fail:[2,7,9,13,14,18,21,22]},
];
const notes = {
  Q01:'Request context itself contains P-A/T-A1. Correct contextual identity can coexist with missing retrieved F-TASK.',
  Q02:'Frozen oracle includes no D-CONFLICT body although its rubric mentions 30 V. This is an evaluator oracle-sufficiency limitation, not proof of a reasoning failure.',
  Q06:'Safe historical HOLD behavior was observed; historical answer remains NOT_RUN. Question August 2 effectiveness differs from valid_at August 1.',
  Q07:'Frozen rubric requires the 2 A constraint as well as excluding the old decision. A safe refusal alone does not satisfy that content requirement.',
  Q09:'Exact revision/paragraph supports the R-A attachment assertion. It does not establish an unprovided numeric measurement. Source dictionary citations are separately visible from fact-ID reference matching.',
  Q12:'All consumers reject non-retrieval as proof of historical absence. Their OK answer envelope differs from frozen HOLD; do not mislabel correct prose as unsafe absence inference.',
  Q13:'The source-bound depends_on proof is a separate requirement from repeating the 2 A constraint.',
  Q15:'C/D/graph-ranked use person A commitment while explicitly withholding exact actor-a binding. Original Q15 coverage remains HOLD: promise timing and fulfilled-commitment exclusion are also not fully exercised. C HOLD is not excessive.',
  Q18:'Decision values and a current-limit statement do not by themselves demonstrate use of the separately reviewed prerequisite relation.',
  Q20:'Fully supplied 60 C/calibration request is intentionally unchanged from T0; no recall is needed.',
  Q21:'Canonical intent includes omission reasons and mandatory conflict proof. Delivered summaries omit selector exclusion reasons; some also omit conflict sides or specimen traceability. T0 ten-observation stress equivalence remains unexecuted.',
  Q22:'Deterministic retrieval replay is separate from a consumer choosing stable reference order. No independent repeated-model trial is claimed.',
  Q23:'A refusal based only on absent authorization lacks the requested use of the supplied 28/30 V decisions. These decisions do not prove a physical maximum-voltage rating.',
  Q24:'Varied failures and success support a candidate improvement only; none of these answers activates a procedure.',
};

export function buildAuthorReport(experiment, consumers) {
  assert.equal(digest(experiment), reviewedExperiment, 'Experiment differs from manually reviewed input/gold/source binding');
  assert.equal(consumers.freeze_digest, experiment.freeze.digest);
  assert.equal(consumers.batches.length, 6);
  const seenQuestionInputs = new Map();
  const batches = consumers.batches.map((observation, index) => {
    const batch = experiment.batches[index];
    assert.equal(observation.batch_id, batch.batch_id);
    assert.equal(observation.input_digest, batch.input_digest);
    assert.equal(observation.requested.model, 'gpt-6-astra');
    assert.equal(observation.requested.reasoning, 'medium');
    const rawDigest = 'sha256:' + createHash('sha256').update(observation.raw_response).digest('hex');
    assert.equal(rawDigest, reviewedResponses[index], 'Response has no matching manual assessment');
    assert.equal(observation.response_digest, rawDigest, 'Raw response SHA mismatch');
    let parsed, format;
    try { parsed = JSON.parse(observation.raw_response); format = 'PASS'; }
    catch {
      // Only the exact pinned C response has this diagnostic-only repair.
      // A caller flag cannot turn malformed source bytes into a valid answer.
      assert.equal(index, 2, 'Unreviewed malformed response');
      parsed = JSON.parse(observation.raw_response + ']}');
      format = 'FAIL';
    }
    assert.equal(observation.format, format, 'Format flag differs from actual raw JSON parse');
    assert.deepEqual(observation.response, parsed, 'Parsed response differs from original raw response');
    assert.deepEqual(parsed.answers.map(a=>a.id), ids);
    assert.deepEqual([...author[index].pass,...author[index].fail,6].sort((a,b)=>a-b), Array.from({length:24},(_,i)=>i+1));
    const condition = experiment.conditions.find(c=>c.batch_id===batch.batch_id);
    const rows = parsed.answers.map((answer, i) => {
      const gold = experiment.gold[i], input = batch.consumer_payload.questions[i];
      const memory = batch.consumer_payload.memories[input.memory_digest];
      const items = memory.items.map(key=>batch.consumer_payload.items[key]);
      const expanded = {question:input.question, request_context:batch.consumer_payload.contexts[input.context_id],
        memory:{...memory,items:items.map(item=>({...item,source:batch.consumer_payload.sources[item.source_id]}))}};
      const inputChars = [...JSON.stringify({instructions:batch.consumer_payload.instructions,...expanded})].length;
      const answerChars = [...JSON.stringify(answer)].length;
      assert.ok(inputChars <= 12000 && answerChars <= 12000);
      assert.ok(answer.used_refs.length <= 12 && (memory.paths?.length||0) <= 6);
      const selected = condition.questions[i].retrieval.selected_refs;
      const missing = gold.include.filter(id=>!selected.includes(id));
      const semantic = i===5 ? 'NOT_RUN' : author[index].pass.includes(i+1) ? 'PASS' : 'FAIL';
      const metrics = evaluateAnswer(answer,gold,semantic,selected);
      const expandedDigest = digest(expanded);
      const prior = seenQuestionInputs.get(expandedDigest) || null;
      if (!prior) seenQuestionInputs.set(expandedDigest,{batch_id:batch.batch_id,id:answer.id});
      return {id:answer.id,source_bindings:gold.source_bindings,gold_digest:digest(gold),
        question_input_digest:condition.questions[i].input_digest,expanded_input_digest:expandedDigest,
        same_question_input_seen_before:prior,independent_model_repetitions:0,
        retrieval:missing.length?'FAIL':'PASS',missing_refs:missing,selected_refs:selected,
        returned_status:answer.status,...metrics,
        semantic_scope:i===5?'Historical answer NOT_RUN; safe withholding observed':'Author source/rubric comparison of delivered prose',
        hold_behavior:['HOLD','NOT_AVAILABLE'].includes(answer.status)?'APPROPRIATE_WITHHOLDING_OR_SUPPORTED_LIMITATION':'NOT_HOLD',
        excessive_hold_observed:false,format,
        outcome:format==='FAIL'?'FAIL':metrics.outcome,
        budget:{input_characters:inputChars,answer_characters:answerChars,evidence:answer.used_refs.length,paths:memory.paths?.length||0,...condition.questions[i].io},
        freshness:condition.questions[i].freshness,coverage:condition.questions[i].coverage,
        note:notes[answer.id] || (semantic==='FAIL'?'Required answer content is missing; read the preserved response and selected evidence together.':'Supplied content used without inventing additional authority.')};
    });
    const count = key => rows.filter(r=>r[key]==='PASS').length;
    return {batch_id:batch.batch_id,input_digest:batch.input_digest,actual_consumer_calls:1,
      observed_profile:'UNKNOWN',tokens:'UNKNOWN',billed_cost:'UNKNOWN',tier:'UNKNOWN',
      native_dispatch_to_delivery_ms:observation.elapsed_ms,provider_latency_ms:'UNKNOWN',
      format,rows,
      summary:{retrieval_pass:count('retrieval'),reference_use_pass:count('reference_use'),
        semantic_pass:count('semantic_utilization'),historical_not_run:1,outcome_pass:count('outcome'),
        held_answers:rows.filter(r=>r.hold_behavior!=='NOT_HOLD').length,excessive_hold_observed:0},
      hard_gate:{unauthorized_source_body_reads_observed:0,invalid_current_decision_use_observed:0,
        verification_failure_disguised_observed:0,operational_mutations_observed:0,
        answer_budget_exceeded:0,final_omission_explanation: 'FAIL',
        model_json_format:format,acceptance:'NOT_ACCEPTED'},
    };
  });
  return {freeze_digest:experiment.freeze.digest,assessment:'AUTHOR_REVIEW_ONLY',independent_review:'NOT_RUN',
    adoption:'HOLD',whole_W7_complete:false,actual_consumer_calls:6,delivered_question_answers:144,
    raw_answer_items:144,diagnostic_format_fail_items:24,accepted_answer_items:'NOT_CLAIMED',
    review_binding:{experiment_digest:reviewedExperiment,response_digests:reviewedResponses,manual_assessment_digest:digest(author)},
    original_question_coverage:{
      Q02:{status:'PARTIAL',oracle:'INSUFFICIENT_30V_CONTENT',cross_project_rejection:'OBSERVED',model_reasoning_failure:'NOT_ESTABLISHED'},
      Q09:{status:'PARTIAL',attachment_exact_locator:'OBSERVED',measurement_minute6_paragraph7:'NOT_RUN'},
      Q12:{safe_explanation:'PASS_6_OF_6',status_envelope:'FIXTURE_SEMANTICS_ISSUE',unsafe_absence_inference:false,excessive_hold:false},
      Q15:{status:'HOLD',person_A_commitment:'USED_BY_C_D_GRAPH_RANKED',actor_a_exact_binding:'MISSING',promise_timing_and_fulfilled_exclusion:'NOT_FULLY_EXERCISED'},
      Q21:{status:'NOT_PASS',final_selector_omission_reasons:'MISSING_6_OF_6',ten_observation_stress:'NOT_RUN'},
    },
    unique_expanded_question_inputs:seenQuestionInputs.size,independent_model_repetitions:0,
    source_and_gold_unchanged_after_consumption:true,
    limitations:['Vector recent/ranked-decision NOT_RUN','Historical answer NOT_RUN',
      'Frozen status envelopes are ambiguous for bounded answers versus run clearance; no post-hoc gold change',
      'Native consumer message readback is opaque; expected input digests and requested profile recorded, observed profile UNKNOWN',
      'Shared-dictionary question isolation is an instruction in a public synthetic batch, not a production access-control mechanism',
      'T4 selectors run on T3 already-filtered packs; this is downstream reranking, not an independent source-corpus retriever',
      'Typed graph is one-hop relation ranking; hybrid is BM25 plus typed priority, without vector',
      'Elapsed includes native orchestration; token conversion and billed-cost estimates were not made'],
    batches,matrix:experiment.matrix.map(cell=>({...Object.fromEntries(['id','retrieval','mode','mechanical','batch_id','input_digest','reused_model_input','reason','implementation'].filter(k=>k in cell).map(k=>[k,cell[k]])),
      semantic:cell.mechanical==='RUN'?'RUN_AUTHOR_REVIEW':'NOT_RUN',
      format:cell.batch_id?batches.find(b=>b.batch_id===cell.batch_id).format:'NOT_RUN'}))};
}

export function writeAuthorReport(experiment, consumers, target = new URL('t4-author-review.json',root)) {
  // Complete all binding/format validation before opening the existing report.
  const report = buildAuthorReport(experiment,consumers);
  writeFileSync(target,JSON.stringify(report)+'\n');
  return report;
}

if (process.argv[1] && import.meta.url===pathToFileURL(process.argv[1]).href) {
  const report = writeAuthorReport(read('t4-run.json'),read('t4-consumer-responses.json'));
  console.log(JSON.stringify({actual_consumer_calls:report.actual_consumer_calls,summary:report.batches.map(b=>({batch:b.batch_id,...b.summary,format:b.format}))}));
}
