// A single error type with a stable code, so callers branch on the code rather than on
// message text or on a class hierarchy that would leak into every consumer.

export class ContractError extends Error {
  constructor(code, message, detail = {}) {
    super(`${code}: ${message}`);
    this.name = 'ContractError';
    this.code = code;
    this.detail = detail;
  }
}

export const CODES = Object.freeze({
  // canonical serialization (PC-11)
  NULL_FORBIDDEN: 'NULL_FORBIDDEN',
  FLOAT_FORBIDDEN: 'FLOAT_FORBIDDEN',
  INTEGER_OUT_OF_SAFE_RANGE: 'INTEGER_OUT_OF_SAFE_RANGE',
  INTEGER_NOT_PLAIN_DECIMAL: 'INTEGER_NOT_PLAIN_DECIMAL',
  EXPONENT_IN_DECIMAL_STRING: 'EXPONENT_IN_DECIMAL_STRING',
  UNSUPPORTED_TYPE: 'UNSUPPORTED_TYPE',
  NFC_KEY_COLLISION: 'NFC_KEY_COLLISION',
  ARRAY_ORDER_RULE_MISSING: 'ARRAY_ORDER_RULE_MISSING',
  ARRAY_ORDER_RULE_UNKNOWN: 'ARRAY_ORDER_RULE_UNKNOWN',
  ARRAY_NOT_SORTED: 'ARRAY_NOT_SORTED',
  ARRAY_SORT_KEY_DUPLICATE: 'ARRAY_SORT_KEY_DUPLICATE',
  ARRAY_SORT_KEY_MISSING: 'ARRAY_SORT_KEY_MISSING',
  ARRAY_ELEMENT_NOT_OBJECT: 'ARRAY_ELEMENT_NOT_OBJECT',

  // time (PC-03)
  TIME_SHAPE_INVALID: 'TIME_SHAPE_INVALID',
  TIME_PRECISION_MISMATCH: 'TIME_PRECISION_MISMATCH',
  TIME_NOT_A_REAL_INSTANT: 'TIME_NOT_A_REAL_INSTANT',

  // fingerprint (PC-06, PC-07)
  FINGERPRINT_INPUT_NOT_OBJECT: 'FINGERPRINT_INPUT_NOT_OBJECT',
  FINGERPRINT_INPUT_KEY_MISSING: 'FINGERPRINT_INPUT_KEY_MISSING',
  FINGERPRINT_EXCLUDED_LAYER_PRESENT_IN_PROJECTION: 'FINGERPRINT_EXCLUDED_LAYER_PRESENT_IN_PROJECTION',
});
