import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { createDurableToolWorkshop } from '../src/tool_workshop_durable.mjs';
import { XLSX_WORKSHOP_PROFILE } from '../src/xlsx_workshop_runner.mjs';
import { sha256 } from '../src/workshop_files.mjs';
import { syntheticPresentationPacket } from '../../../docs/architecture/workspace/examples/tool_workshop/synthetic_pptx_packet.mjs';
import { PPTX_WORKSHOP_PROFILE, validatePresentationPacket, pinPptxRunnerBinding, pptxBindingDigest, verifyPptxRunnerBinding, createPptxWorkshopRunner } from '../src/pptx_workshop_runner.mjs';
test('PPTX packet binds two editable template slides and rejects injected command fields',()=>{
  const packet=syntheticPresentationPacket('a'.repeat(64));
  assert.equal(PPTX_WORKSHOP_PROFILE.workshop_class,'presentation');
  assert.deepEqual(validatePresentationPacket(packet),packet);
  assert.throws(()=>validatePresentationPacket({...packet,command:'arbitrary'}),{code:'unexpected_fields'});
  assert.throws(()=>validatePresentationPacket({...packet,provenance:undefined}),{code:'presentation_packet_invalid'});
  assert.throws(()=>validatePresentationPacket({...packet,slides:[{title:'W'.repeat(25),body:'too wide'},packet.slides[1]]}),{code:'presentation_text_out_of_profile'});
});

const configPath=process.env.SOULFORGE_PPTX_TEST_CONFIG;
test('real template author, independent native validator, render QA, restart and drift gates',{skip:!configPath},async()=>{
  const config=JSON.parse(readFileSync(configPath,'utf8'));
  const binding=pinPptxRunnerBinding(config);
  const root=mkdtempSync(path.join(tmpdir(),'workshop-pptx-'));
  const roots=Object.fromEntries(['stateRoot','inputRoot','workRoot','outputRoot'].map(key=>{const value=path.join(root,key);mkdirSync(value);return[key,value];}));
  const queue=createDurableToolWorkshop(roots);
  queue.registerWorkshop({...PPTX_WORKSHOP_PROFILE,binding_digest:pptxBindingDigest(binding)});
  const packet=Buffer.from(JSON.stringify(syntheticPresentationPacket(binding.template_sha256)));
  writeFileSync(path.join(roots.inputRoot,`${sha256(packet)}.json`),packet);
  const job={job_id:'job.pptx',workshop_id:'workshop.pptx',project_ref:'project.synthetic',task_ref:'task.synthetic',work_brief_ref:'brief.synthetic',approval_ref:'approval.synthetic',priority:2,required_tool_version:'tool.template_pptx:v1',input_bundle_manifest_digest:sha256(packet),timeout_seconds:180,max_retries:1};
  queue.submitJob(job);
  queue.registerWorkshop(XLSX_WORKSHOP_PROFILE);
  queue.submitJob({...job,job_id:'job.xlsx.independent',workshop_id:'workshop.xlsx',required_tool_version:'tool.project_history_xlsx:v1'});
  queue.acquireLease('workshop.xlsx',{lease_id:'lease.xlsx.independent'});
  const env={...roots,queue,binding,projectRef:'project.synthetic'};
  const result=await createPptxWorkshopRunner(env).runNext();
  assert.equal(result.state,'done_candidate');
  assert.equal(queue.getJob('job.xlsx.independent').state,'leased','the different tool keeps its independent capacity-one lease');
  assert.deepEqual(createDurableToolWorkshop({...roots,mode:'open_existing'}).getCustodyReceipt(job.job_id),result.receipt);
  const artifact=result.receipt.artifact;
  const manifest=readFileSync(path.join(roots.outputRoot,`${artifact.render_manifest_digest}.json`));
  assert.equal(sha256(manifest),artifact.render_manifest_digest);
  assert.equal(JSON.parse(manifest).length,2);
  for(const render of JSON.parse(manifest))assert.equal(sha256(readFileSync(path.join(roots.outputRoot,`${render.sha256}.png`))),render.sha256);
  assert.equal(sha256(readFileSync(path.join(roots.outputRoot,`${artifact.sha256}.pptx`))),artifact.sha256);
  assert.equal(readFileSync(path.join(roots.stateRoot,'workshop.sqlite')).includes(Buffer.from('Two approved synthetic records')),false);
  for(const overrides of [{template_sha256:'0'.repeat(64)},{python_version:'3.12.999'},{artifact_version:'0.0.0'}])assert.throws(()=>verifyPptxRunnerBinding({...binding,...overrides}),{code:'binding_drift'});
  const altered=structuredClone(binding);altered.python_files[0].sha256='0'.repeat(64);
  assert.throws(()=>verifyPptxRunnerBinding(altered),{code:'binding_drift'});
  queue.submitJob({...job,job_id:'job.cancel'});
  const running=createPptxWorkshopRunner(env).runNext();queue.cancelJob('job.cancel');
  assert.equal((await running).state,'cancelled');
  assert.equal(queue.getCustodyReceipt('job.cancel'),null);
  assert.equal(readdirSync(roots.outputRoot).filter(file=>file.endsWith('.pptx')).length,1);
  queue.submitJob({...job,job_id:'job.invalid',input_bundle_manifest_digest:'f'.repeat(64),max_retries:0});
  assert.equal((await createPptxWorkshopRunner(env).runNext()).state,'failed_terminal');
  assert.equal(queue.getCustodyReceipt('job.invalid'),null);
});
